/** Install data only into an explicitly chosen M06 DEVELOPMENT copy. No runtime JS changes. */
import path from'node:path';import fs from'node:fs';import{createHash,randomUUID}from'node:crypto';import{fileURLToPath}from'node:url';import{ROOT}from'./build.mjs';import{createStageCatalog}from'../vendor/m06/stage-catalog.mjs';import{safe,readOptional,writeAtomic}from'./lib/safe-path.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');const spec={maps:'map.json',characters:'character.json',stages:'stage.json',audio:'audio.json'};
export function integrationPlan(target,{root=ROOT,level=null,file=null}={}){target=path.resolve(target);safe(target,'package.json');const version=JSON.parse(readOptional(target,'package.json')||'{}').version;if(version!=='0.4.2')throw Error('仅接受M06 / 0.4.2开发源码副本');const lock=JSON.parse(readOptional(root,'data/runtime-lock.json'));const locations={'stage-catalog.mjs':'src/content','platform-stage.mjs':'src/simulation','platform-motor.mjs':'src/simulation','stage-session.mjs':'src/runtime','lifetime.mjs':'src/runtime'};const observed=[];
 const get=p=>{const b=readOptional(target,p);observed.push({path:p,before:b});return b;};
 for(const [name,h]of Object.entries(lock.files)){const p=locations[name]+'/'+name,b=get(p);if(!b||hash(Buffer.from(b.toString().replace(/\r\n/g,'\n')))!==h)throw Error('运行时已有新修改，需要先核对接口：'+p);}
 if(level&&!/^[1-8]-[1-4]$/.test(level))throw Error('未知关卡');if(file&&!/^content\/forks\/[a-z][a-z0-9-]{2,28}\.json$/.test(file))throw Error('只允许本工具创建的草稿路径');
 const pack=JSON.parse(readOptional(root,file||`data/generated/${level||'extensions'}.json`));createStageCatalog(pack);const merged={schemaVersion:1},changes=[],directories=[];
 for(const[type,name]of Object.entries(spec)){const dir=`content/extensions/${type}`;const names=fs.readdirSync(safe(target,dir)).sort();directories.push({path:dir,names});merged[type]=names.map(id=>{const p=dir+'/'+id+'/'+name;return JSON.parse(get(p));});
  for(const item of pack[type]){const p=`${dir}/${item.id}/${name}`,b=Buffer.from(JSON.stringify(item,null,2)+'\n'),before=get(p);if(before&&JSON.stringify(JSON.parse(before))!==JSON.stringify(item))throw Error('同名内容已有不同修改：'+p);if(!before){changes.push({path:p,before:null,after:b});merged[type].push(item);}}
 }
 createStageCatalog(merged);return{target,observed,directories,changes};}
export function applyIntegration(plan){for(const d of plan.directories)if(JSON.stringify(fs.readdirSync(safe(plan.target,d.path)).sort())!==JSON.stringify(d.names))throw Error('检查后目录变化');for(const o of plan.observed){const b=readOptional(plan.target,o.path);if((b?hash(b):null)!==(o.before?hash(o.before):null))throw Error('检查后文件变化');}if(!plan.changes.length)return null;const receipt=`.local/atlas-import-${randomUUID()}.json`,written=[];
 try{for(const c of plan.changes){if(readOptional(plan.target,c.path))throw Error('写入时冲突');writeAtomic(plan.target,c.path,c.after);written.push(c);}writeAtomic(plan.target,receipt,Buffer.from(JSON.stringify({version:'K01',target:fs.realpathSync(plan.target),files:written.map(c=>({path:c.path,sha256:hash(c.after)}))},null,2)+'\n'));return receipt;}catch(e){for(const c of written.reverse()){const b=readOptional(plan.target,c.path);if(b&&hash(b)===hash(c.after))fs.unlinkSync(safe(plan.target,c.path));}throw e;}}
export function undo(target,receipt,{apply=false}={}){if(!/^\.local\/atlas-import-[a-f0-9-]+\.json$/.test(receipt||''))throw Error('导入记录路径无效');const r=JSON.parse(readOptional(target,receipt));if(r.version!=='K01'||r.target!==fs.realpathSync(target))throw Error('导入记录不匹配');const seen=new Set();for(const f of r.files){if(seen.has(f.path)||!/^content\/extensions\/(maps|characters|stages|audio)\/[a-z0-9-]+\/(map|character|stage|audio)\.json$/.test(f.path))throw Error('导入记录越界');seen.add(f.path);const b=readOptional(target,f.path);if(!b||hash(b)!==f.sha256)throw Error('内容有后续修改，停止撤回：'+f.path);}if(apply){for(const f of r.files){fs.unlinkSync(safe(target,f.path));const dir=path.dirname(safe(target,f.path));if(fs.readdirSync(dir).length===0)fs.rmdirSync(dir);}fs.unlinkSync(safe(target,receipt));}return r.files.length;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))try{const a=process.argv.slice(2),v=k=>a.includes(k)?a[a.indexOf(k)+1]:null;if(!v('--target')||a.includes('--apply')&&a.includes('--check'))throw Error('用法：--target M06源码路径 [--level 1-1 | --file content/forks/id.json] --check/--apply');if(v('--undo'))console.log({removed:undo(v('--target'),v('--undo'),{apply:a.includes('--apply')})});else{const p=integrationPlan(v('--target'),{level:v('--level'),file:v('--file')});console.log({files:p.changes.length,mode:a.includes('--apply')?'apply':'check',receipt:a.includes('--apply')?applyIntegration(p):null,next:'在M06副本运行 npm run stage:check && npm run dev；访问 http://127.0.0.1:4193/play.html?dev=1 并显示开发草稿。'});}}catch(e){console.error(e.message);process.exitCode=1;}
