import fs from'node:fs';import path from'node:path';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{ROOT,build}from'./build.mjs';import{zip}from'./lib/zip.mjs';import{safe,readOptional,entryStat,writeAtomic}from'./lib/safe-path.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
export function entries(root=ROOT){const out=[];function visit(dir=''){for(const e of fs.readdirSync(dir?safe(root,dir):root,{withFileTypes:true})){if(['.git','.local','node_modules','SOURCE_SHA256SUMS.txt'].includes(e.name))continue;const p=dir?dir+'/'+e.name:e.name,st=entryStat(safe(root,p));if(/\.(ttf|ttc|otf|woff2?|eot)$/i.test(p)||e.name.startsWith('.env'))throw Error('禁止打包：'+p);if(st.isDirectory())visit(p);else if(st.isFile())out.push([p,readOptional(root,p)]);else throw Error('仅允许普通文件');}}visit();return out.sort((a,b)=>a[0].localeCompare(b[0],'en'));}
export function archiveBytes(root=ROOT){build(root,{check:true});const files=entries(root);files.push(['SOURCE_SHA256SUMS.txt',Buffer.from(files.map(([p,b])=>hash(b)+'  '+p).join('\n')+'\n')]);const result=[],out=new Map();const all=zip(files.map(([p,b])=>['MarioMix_Levels_K01/'+p,b]));out.set('MarioMix_Levels_K01_Source.zip',all);result.push({name:'MarioMix_Levels_K01_Source.zip',bytes:all.length,sha256:hash(all)});
 for(const {id} of JSON.parse(readOptional(root,'data/reference/world-1.json')).maps){const selected=files.filter(([p])=>p.startsWith('licenses/')||p==='NOTICE.md'||p.startsWith(`previews/${id}-`)||p.startsWith(`tiled/${id}-`)||p===`data/generated/${id}.json`);selected.push(['README.md',Buffer.from(`# ${id} · 地图模板 K01\n\n本包包含 M06 platform-v1 扩展数据、各房间结构预览和 Tiled 对象层。\n这是本关的数据快照，先解压同版本完整 MarioMix_Levels_K01_Source.zip。以下 --level 命令读取完整工具包中的同版模板，不读取另行编辑的ZIP副本。在该工程运行：\n\n\`\`\`sh\nnpm run integrate -- --target "M06源码路径" --level ${id} --check\nnpm run integrate -- --target "M06源码路径" --level ${id} --apply\n\`\`\`\n\n制作自己的关卡时，先运行 npm run fork -- --id my-stage --from ${id} --apply，再编辑 content/forks/my-stage.json，使用 integrate 的 --file content/forks/my-stage.json 参数导入。不要修改 data/generated 后直接重建。\n\n开发游戏通过 http://127.0.0.1:4193/play.html?dev=1 打开，在接入试验场中勾选开发草稿。\n本模板采用原版复刻项目的坐标转录，原版逐格与机关时序待复验；不含正式角色/BGM，不替换已发布关卡。\n`) ]);const ref=JSON.parse(readOptional(root,'data/reference/world-1.json'));selected.push(['reference.json',Buffer.from(JSON.stringify(ref.maps.find(m=>m.id===id),null,2)+'\n')]);const bytes=zip(selected.map(([p,b])=>[`MarioMix_${id}_Template_K01/`+p,b]));const name=`MarioMix_${id}_Template_K01.zip`;out.set(name,bytes);result.push({name,bytes:bytes.length,sha256:hash(bytes)});}
 return out;
}
export function pack(root=ROOT){const out=archiveBytes(root);for(const[name,b]of out)writeAtomic(root,'.local/'+name,b);return [...out].map(([name,b])=>({name,bytes:b.length,sha256:hash(b)}));}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))try{console.log(JSON.stringify(pack(),null,2));}catch(e){console.error(e.message);process.exitCode=1;}
