/** Compile only explicitly registered, reviewed reading documents. */
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readOptional,writeAtomic} from '../lib/safe-path.mjs';
import {normalizeText,equalText} from '../lib/text-records.mjs';
const ROOT=fileURLToPath(new URL('../../',import.meta.url));
export const OUTPUT='assets/journal/documents-data.mjs';
export function documentData(root=ROOT,{reader=p=>readOptional(root,p)}={}){
 const config=JSON.parse(reader('config/documents.json'));
 if(config.schemaVersion!==1||!Array.isArray(config.documents))throw Error('Invalid document registry');
 const sources=new Set(),ids=new Set();
 const rows=config.documents.map(d=>{
  if(!/^(?:packages\/mario-mix(?:-terra|-worlds)?\/|assets\/)[A-Za-z0-9_./-]+\.(md|txt)$/.test(d.source)||d.source.split('/').some(x=>x==='.'||x==='..')||sources.has(d.source))throw Error('Invalid or duplicate document source');
  for(const k of ['id','projectId','parent'])if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d[k]))throw Error('Invalid document ID');
  const key=d.projectId+'/'+d.id;if(ids.has(key)||!d.title||d.title.length>48)throw Error('Invalid document title or duplicate route');
  sources.add(d.source);ids.add(key);
  const b=reader(d.source);if(!b)throw Error('Missing document '+d.source);
  const markdown=d.contentOverride===undefined?normalizeText(b):d.contentOverride;
  if(typeof markdown!=='string'||Buffer.byteLength(markdown)>200000)throw Error('Invalid document text');
  const {contentOverride,...metadata}=d;
  return {...metadata,markdown};
 });
 const projects=new Map();
 for(const d of rows){
  if(!projects.has(d.projectId))projects.set(d.projectId,JSON.parse(reader(`content/development/projects/${d.projectId}.json`)));
  const project=projects.get(d.projectId);
  if(project.docs.some(x=>x.id===d.id))throw Error('Document route conflicts with project guide: '+d.id);
  if(d.parent===d.id||!project.docs.some(x=>x.id===d.parent)&&!ids.has(d.projectId+'/'+d.parent))throw Error('Missing document parent: '+d.id);
  const visited=new Set([d.id]);let parent=rows.find(x=>x.projectId===d.projectId&&x.id===d.parent);
  while(parent){if(visited.has(parent.id))throw Error('Document parent cycle');visited.add(parent.id);parent=rows.find(x=>x.projectId===d.projectId&&x.id===parent.parent);}
 }
 return Buffer.from('// Generated by scripts/journal/documents.mjs; edit the registry or its reviewed sources.\nexport const DOCUMENTS='+JSON.stringify(rows,null,2)+';\n');
}
export function buildDocuments(root=ROOT,{check=false}={}){
 const bytes=documentData(root),old=readOptional(root,OUTPUT);
 if(equalText(old,bytes))return;
 if(check)throw Error('Document pages are stale: run npm run journal:build');
 writeAtomic(root,OUTPUT,bytes);
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))buildDocuments(ROOT,{check:process.argv.includes('--check')});
