import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {createDevServer} from '../scripts/server.mjs';
import {sandbox} from './helpers.mjs';
async function running(t,original=false){const s=sandbox(t),server=createDevServer({...s,original});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r);});t.after(()=>new Promise(r=>server.close(r)));return {...s,server,port:server.address().port};}
function request(port,uri,options={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path:uri,...options},res=>{const b=[];res.on('data',x=>b.push(x));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(b).toString()}));});req.on('error',reject);req.end();});}
test('real HTTP candidate endpoint serves compiled source, game file remains untouched',async t=>{const s=await running(t),r=await request(s.port,'/games/mario-mix/classic-mix.js');assert.equal(r.status,200);assert.ok(r.body.includes('const __mmR05'));assert.equal(fs.readFileSync(path.join(s.root,'games/mario-mix/classic-mix.js'),'utf8'),s.runtime);});
test('reference server serves original script, build metadata explicitly says original',async t=>{const s=await running(t,true),r=await request(s.port,'/games/mario-mix/classic-mix.js'),m=await request(s.port,'/__r05/build.json');assert.equal(r.body,s.runtime);assert.equal(JSON.parse(m.body).mode,'original-reference');});
test('development HTML drops analytics only in memory and preserves script location',async t=>{const s=await running(t),r=await request(s.port,'/games/mario-mix/play.html?test=1');assert.equal(r.status,200);assert.ok(r.body.includes('src="classic-mix.js"'));assert.ok(!r.body.includes('site-analytics'));assert.equal(fs.readFileSync(path.join(s.root,'games/mario-mix/play.html'),'utf8'),s.html);});
test('HTTP server denies write requests, foreign Host, Origin and cross-site fetch',async t=>{const s=await running(t);for(const o of [{method:'POST'},{headers:{Host:'evil.example'}},{headers:{Origin:'https://example.org'}},{headers:{'Sec-Fetch-Site':'cross-site'}}]){const r=await request(s.port,'/games/mario-mix/play.html',o);assert.ok([403,405].includes(r.status));}});
test('HTTP private files, path traversal, encoding and symlink protection',async t=>{const s=await running(t);fs.symlinkSync(s.dir,path.join(s.root,'games/mario-mix/linked'),'dir');for(const p of ['/.git/config','/packages/mario-mix/baseline.json','/games/mario-mix/%2e%2e/%2e%2e/package.json','/games/mario-mix/linked/secret','/games/mario-mix/a%5cb','/games/mario-mix/a%00b','/%ZZ']){const r=await request(s.port,p);assert.ok([400,403,404].includes(r.status),p+':'+r.status);}});
test('HTTP HEAD and missing resources have explicit status, no directory listing',async t=>{const s=await running(t);const h=await request(s.port,'/games/mario-mix/classic-mix.js',{method:'HEAD'});assert.equal(h.status,200);assert.equal(h.body,'');assert.ok(Number(h.headers['content-length'])>0);assert.equal((await request(s.port,'/games/mario-mix/assets/')).status,404);assert.equal((await request(s.port,'/games/mario-mix/missing.png')).status,404);});
