#!/usr/bin/env node
import {loadExperiments} from '../platform/experiments.mjs';
import {withExperimentDocuments} from '../../assets/platform/contracts.mjs';
/** Deterministic, small navigation data + independently cacheable article bodies. */
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {readOptional,writeAtomic} from '../lib/safe-path.mjs';
import {documentData} from '../journal/documents.mjs';
import {validateCatalog,validateProject} from '../../assets/journal/model.mjs';
export const ROOT=fileURLToPath(new URL('../../',import.meta.url));
const CODE=['assets/site-router.js','assets/journal/runtime.mjs','assets/journal/render.mjs','assets/journal/documents.mjs','assets/journal/public-layout.mjs','assets/journal/experiment.mjs','assets/journal/update-audience.mjs','assets/release/public-content.mjs'];
const VERSION=/dev-r44(?:-[0-9a-f]{16})?/g;
const sha=b=>createHash('sha256').update(b).digest('hex');
const json=x=>Buffer.from(JSON.stringify(x,null,2)+'\n');
const js=(name,value)=>Buffer.from('// Generated by scripts/dev-center/build.mjs.\nexport const '+name+'='+JSON.stringify(value).replace(/</g,'\\u003c')+';\n');
export function planJournalData(root=ROOT,{reader=p=>readOptional(root,p),documentReader=reader}={}){
 const get=p=>{const b=reader(p);if(b===null||b===undefined)throw Error('Missing development input: '+p);return Buffer.from(b);};
 const catalog=validateCatalog(JSON.parse(get('content/development/catalog.json')));
 const {entries:experiments}=loadExperiments(root,{reader:get});
 const projects=catalog.projects.map(row=>{const p=validateProject(JSON.parse(get(row.file)));if(p.id!==row.id)throw Error('Project ID mismatch');return withExperimentDocuments(p,experiments);});
 const documentSource=documentData(root,{reader:documentReader}).toString('utf8');
 const marker='export const DOCUMENTS=';const offset=documentSource.indexOf(marker);
 if(offset<0||!documentSource.endsWith(';\n'))throw Error('Unsupported document generator output');
 const documents=JSON.parse(documentSource.slice(offset+marker.length,-2));
 const code=CODE.map(p=>[p,get(p).toString().replace(VERSION,'dev-r44')]);
 const revision='dev-r44-'+sha(json({catalog,projects,documents,experiments,code,css:get('assets/journal/organization.css').toString()})).slice(0,16);
 const files=new Map();const index=[];
 for(const d of documents){
  const file=`assets/journal/data/documents/${d.projectId}/${d.id}.json`;
  const {markdown,...metadata}=d;index.push({...metadata,contentHref:'/'+file+'?v='+revision});
  files.set(file,json({projectId:d.projectId,id:d.id,source:d.source,markdown}));
 }
 const navigationProjects=projects.map(p=>({...p,docs:p.docs.map(d=>{
  if(d.readingDocument)return d;
  const file=`assets/journal/data/guides/${p.id}/${d.id}.json`;
  files.set(file,json({projectId:p.id,guide:d}));
  return {...d,sections:[],deferredGuide:'/'+file+'?v='+revision};
 })}));
 files.set('assets/journal/data/catalog.mjs',js('CATALOG',{catalog,projects:navigationProjects}));
 files.set('assets/journal/data/documents-index.mjs',js('DOCUMENTS',index));
 files.set('assets/journal/data/experiments.mjs',js('EXPERIMENTS',experiments));
 files.set('assets/journal/data/revision.json',json({schemaVersion:1,revision}));
 const navigationBytes=files.get('assets/journal/data/catalog.mjs').length+files.get('assets/journal/data/documents-index.mjs').length+files.get('assets/journal/data/experiments.mjs').length;
 return {files,revision,code,navigationBytes,articleCount:documents.length+projects.reduce((n,p)=>n+p.docs.length,0)};
}
export function build(root=ROOT,{check=false}={}){
 const plan=planJournalData(root),out=new Map(plan.files);
 for(const [p,source]of plan.code)out.set(p,Buffer.from(source.replace(VERSION,plan.revision)));
 const cssPath='assets/journal/journal.css',baseCSS=readOptional(root,cssPath)?.toString();
 if(!baseCSS)throw Error('Missing shared journal stylesheet');
 const cleanCSS=baseCSS.replace(/\n?\/\* DEV-CENTER:BEGIN \*\/[\s\S]*?\/\* DEV-CENTER:END \*\/\s*$/,'').trimEnd();
 out.set(cssPath,Buffer.from(cleanCSS+'\n\n/* DEV-CENTER:BEGIN */\n'+readOptional(root,'assets/journal/organization.css').toString().trimEnd()+'\n/* DEV-CENTER:END */\n'));
 const changes=[...out].filter(([p,b])=>!readOptional(root,p)?.equals(b));
 if(check&&changes.length)throw Error('Development data is stale: npm run journal:build\n'+changes.map(([p])=>p).join('\n'));
 if(!check)for(const[p,b]of changes)writeAtomic(root,p,b);
 return {changed:changes.length,navigationBytes:plan.navigationBytes,articleCount:plan.articleCount};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 try{if(process.argv.slice(2).some(x=>x!=='--check'))throw Error('Unsupported option');console.log(build(ROOT,{check:process.argv.includes('--check')}));}catch(e){console.error(e.message);process.exitCode=1;}
}
