import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,mkdir,writeFile,rm}from'node:fs/promises';
import path from 'node:path';
import os from'node:os';
import {createRequire}from'node:module';
import{build,outputs,ROOT}from'../tools/build-collab.mjs';
const M=createRequire(import.meta.url)('../dev/model.js');
const source=JSON.parse(await readFile(new URL('../collab/project.json',import.meta.url),'utf8'));
const fresh=()=>M.clone(source);
test('committed project passes schema and has all three playable entries',()=>{assert.deepEqual(M.validate(source),[]);assert.equal(source.episodes.length,3);});
test('counts exactly partition tasks',()=>{assert.equal(Object.values(M.counts(source)).reduce((a,b)=>a+b,0),source.tasks.length);});
test('filter finds ID, owner and status independently',()=>{assert.equal(M.filterTasks(source,{query:'COL-001'}).length,1);const ready=M.filterTasks(source,{status:'ready'});assert.ok(ready.length>0);assert.ok(ready.every(t=>t.status==='ready'));});
test('invalid status and duplicate id are rejected',()=>{let p=fresh();p.tasks[0].status='magic';assert.match(M.validate(p).join(' '),/状态/);p=fresh();p.tasks[1].id=p.tasks[0].id;assert.match(M.validate(p).join(' '),/重复/);});
test('done requires evidence, including malformed non-string evidence',()=>{const p=fresh();p.tasks[0].evidence='';assert.ok(M.validate(p).length);p.tasks[0].evidence=42;assert.doesNotThrow(()=>M.validate(p));assert.ok(M.validate(p).length);});
test('missing dependencies and dependency cycles are rejected',()=>{let p=fresh();p.tasks[0].dependsOn=['MISSING-001'];assert.match(M.validate(p).join(' '),/不存在/);p=fresh();p.tasks[0].dependsOn=[p.tasks[1].id];p.tasks[1].dependsOn=[p.tasks[0].id];assert.match(M.validate(p).join(' '),/环/);});
test('done cannot bypass incomplete dependencies',()=>{const p=fresh();p.tasks[0].dependsOn=['SRC-001'];assert.match(M.validate(p).join(' '),/未完成/);});
test('dates and paths are validated, not merely matched by shape',()=>{const p=fresh();p.updatedAt='2026-02-30';assert.match(M.validate(p).join(' '),/日期/);assert.equal(M.cleanPath('../private'),false);assert.equal(M.cleanPath('https://evil.test/x'),false);assert.equal(M.cleanPath('docs/collab/HANDOFF.md'),true);});
test('Issue URL must be exact current repo and numeric issue',()=>{for(const url of ['javascript:alert(1)','https://evil.test/issues/1','https://github.com/Aha-xiaoQ/other/issues/2','https://github.com/'+source.repository+'/issues/1?evil=1']){const p=fresh();p.tasks[0].issueUrl=url;assert.ok(M.validate(p).length);}const p=fresh();p.tasks[0].issueUrl='https://github.com/'+p.repository+'/issues/1';assert.deepEqual(M.validate(p),[]);});
test('edit produces immutable copy and refuses structural patch fields',()=>{const p=M.editTask(source,'SRC-001',{owner:'test contributor'});assert.equal(source.tasks.find(t=>t.id==='SRC-001').owner,'');assert.equal(p.tasks.find(t=>t.id==='SRC-001').owner,'test contributor');assert.throws(()=>M.editTask(source,'SRC-001',{title:'rewrite'}));});
test('handoff includes baseline, next action, latest-repo and manual-push boundary',()=>{const s=M.resumeText(source);for(const text of [source.baseCommit,source.nextTask,'AGENTS.md','main','不要擅自推送'])assert.ok(s.includes(text));});
test('fingerprint detects local draft difference',()=>{assert.equal(M.fingerprint(source),M.fingerprint(fresh()));const p=M.editTask(source,'SRC-001',{notes:'changed'});assert.notEqual(M.fingerprint(source),M.fingerprint(p));});
test('JSON primitives and malformed collections return errors without crashing',()=>{for(const p of [null,[],false,1,'bad',{},Object.assign(fresh(),{tasks:[null]})]){assert.doesNotThrow(()=>M.validate(p));assert.ok(M.validate(p).length);}});
test('generated JS and Markdown are synchronized with canonical project',async()=>{assert.deepEqual(await build(true),[]);});
test('stale generated file fails check until rebuilt',async()=>{const temp=await mkdtemp(path.join(os.tmpdir(),'mm-build-'));try{await mkdir(path.join(temp,'collab'));await mkdir(path.join(temp,'dev'));await writeFile(path.join(temp,'collab/project.json'),JSON.stringify(source));await assert.rejects(build(true,temp),/过期/);await build(false,temp);assert.deepEqual(await build(true,temp),[]);}finally{await rm(temp,{recursive:true,force:true});}});
