import test from'node:test';import assert from'node:assert/strict';
import http from'node:http';import{mkdtemp,mkdir,writeFile,rm,symlink}from'node:fs/promises';import path from'node:path';import os from'node:os';
import{createDevServer}from'../tools/dev-server.mjs';
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'mm-server-'));await mkdir(path.join(root,'dev'));await mkdir(path.join(root,'.git'));await mkdir(path.join(root,'empty'));await writeFile(path.join(root,'dev/index.html'),'<!doctype html><h1>开发中心</h1>');await writeFile(path.join(root,'dev/data.json'),'{}');await writeFile(path.join(root,'.git/config'),'private');const server=createDevServer(root);await new Promise((res,rej)=>{server.once('error',rej);server.listen(0,'127.0.0.1',res);});t.after(async()=>{await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});});const port=server.address().port;const req=(p,method='GET',host)=>new Promise((res,rej)=>{const r=http.request({hostname:'127.0.0.1',port,path:p,method,headers:host?{host}:{}},s=>{const chunks=[];s.on('data',c=>chunks.push(c));s.on('end',()=>res({status:s.statusCode,headers:s.headers,body:Buffer.concat(chunks).toString('utf8')}));});r.on('error',rej);r.end();});return{root,req};}
test('static GET and HEAD use correct types and no-cache headers',async t=>{const{req}=await fixture(t);const get=await req('/dev/');assert.equal(get.status,200);assert.match(get.headers['content-type'],/text\/html/);assert.match(get.body,/开发中心/);assert.equal(get.headers['cache-control'],'no-store');const head=await req('/dev/index.html','HEAD');assert.equal(head.status,200);assert.equal(head.body,'');assert.match((await req('/dev/data.json')).headers['content-type'],/application\/json/);});
test('directory redirect and missing routes do not list files',async t=>{const{req}=await fixture(t);const redir=await req('/dev');assert.equal(redir.status,302);assert.equal(redir.headers.location,'/dev/');assert.equal((await req('/empty/')).status,404);assert.equal((await req('/missing')).status,404);});
test('private paths, encoded traversal and foreign Host rejected',async t=>{const{req}=await fixture(t);for(const p of ['/.git/config','/%2e%2e/private','/dev/../.git/config','/dev%5c..%5c.git/config'])assert.equal((await req(p)).status,403,p);assert.equal((await req('/dev/','GET','evil.test')).status,403);assert.equal((await req('/dev/%ZZ')).status,400);});
test('POST cannot write to project',async t=>{const{req}=await fixture(t);assert.equal((await req('/dev/data.json','POST')).status,405);assert.equal((await req('/dev/data.json')).body,'{}');});
test('symlinks cannot expose hidden files',async t=>{if(process.platform==='win32')return t.skip('POSIX-only symlink test.');const{req,root}=await fixture(t);await symlink(path.join(root,'.git/config'),path.join(root,'visible.txt'));assert.equal((await req('/visible.txt')).status,403);});
