import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {fileURLToPath} from 'node:url';
import {projectEmblem,renderProjectCards} from '../assets/journal/render.mjs';
const root=new URL('../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8');
for(const kind of ['game','web']){
 test(kind+' uses a 96×72 small decorative icon, no banner words/caption',()=>{
  const h=projectEmblem(kind);assert.ok(h.includes('j-project-emblem--compact'));assert.ok(h.includes('width="96" height="72"'));
  assert.ok(!/j-emblem-word|\bPLAY\b|\bBUILD\b|IDEAS INTO REALITY/.test(h));assert.ok(h.includes('alt=""'));assert.ok(h.includes('aria-hidden="true"'));
 });
}
test('game retains the simple tilted controller with D-pad and button',()=>{const s=read('assets/journal/icons/controller.svg');assert.ok(s.includes('rotate(12'));assert.ok(s.includes('rx="10"'));assert.ok(s.includes('<circle'));assert.ok(s.includes('M29 25v19'));});
test('website has browser chrome, address line, content blocks and pointer',()=>{const s=read('assets/journal/icons/web-studio.svg');for(const token of ['M10 20h72','M33 13.5h36','M17 44h18','m69 39 15 10'])assert.ok(s.includes(token));assert.notEqual(s,read('assets/journal/icons/controller.svg'));});
test('both assets share the same viewBox and do not contain active or external content',()=>{for(const name of ['controller','web-studio']){const s=read('assets/journal/icons/'+name+'.svg');assert.ok(s.includes('viewBox="0 0 96 72"'));assert.ok(!/<script|<foreignObject|<text|\bon\w+=|href=|url\(|@font/i.test(s));}});
test('unrelated category rendering keeps existing R08 artwork and behavior',()=>{for(const [c,w,f]of [['tool','TOOLS','workflow'],['experiment','LAB','experiment'],['other','CREATE','workflow'],['future','CREATE','workflow']]){
 const h=projectEmblem(c);assert.ok(h.includes('>'+w+'</span>'));assert.ok(h.includes('/assets/illustrations/'+f+'.svg?v=workshop-r08'));assert.ok(!h.includes('--compact'));}
});
test('compact CSS is scoped, fixed-size, with no animation or new theme',()=>{const all=read('assets/journal/journal.css'),s=all.slice(all.indexOf('/* R12 /'));assert.ok(s.includes('width:96px;height:72px'));assert.ok(s.includes('height:80px;min-height:80px'));assert.ok(!/:root|@font-face|@keyframes|view-transition/.test(s));assert.ok(s.includes('animation:none'));for(const sel of s.matchAll(/(?:^|[{}])\s*([^{}]+)\{/g)){const q=sel[1].replace(/\/\*[\s\S]*?\*\//g,'').trim();if(q&&!q.startsWith('@'))assert.ok(q.split(',').every(a=>a.trim().startsWith('.journal')),q);}});
test('catalog copy, status and destinations remain intact',()=>{const ps=[{id:'my-game',visibility:'public',category:'game',title:'任意游戏',summary:'完整介绍不改',stage:'测试中'},{id:'my-site',visibility:'public',category:'web',title:'任意网站',summary:'另外一条介绍',stage:'待验收'}];const h=renderProjectCards(ps);for(const t of ['任意游戏','完整介绍不改','任意网站','另外一条介绍','/notes/my-game/','/notes/my-site/'])assert.ok(h.includes(t));assert.equal((h.match(/j-compact-icon/g)||[]).length,2);});
test('search and category filters still use stable IDs without artwork branches',()=>{const ps=[{id:'alpha',visibility:'public',category:'game',title:'游戏甲',summary:'one',stage:'测试'},{id:'beta',visibility:'public',category:'web',title:'网站乙',summary:'two',stage:'测试'}];assert.ok(!renderProjectCards(ps,{category:'game'}).includes('网站乙'));assert.ok(renderProjectCards(ps,{q:'two'}).includes('网站乙'));assert.ok(!/p\.id\s*===\s*['"]/.test(read('assets/journal/render.mjs')));});
test('both direct-page CSS and dynamic renderer have current document cache revisions',()=>{assert.ok(read('assets/journal/runtime.mjs').includes('render.mjs?v=docs-r26'));assert.ok(read('scripts/journal/build.mjs').includes('journal/journal.css?v=docs-r26'));const html=read('notes/index.html');assert.ok(html.includes('site-router.js?v=docs-r26'));assert.ok(html.includes('journal.css?v=docs-r26'));});
test('no second transition owner or extra top navigation is introduced',()=>{const router=read('assets/site-router.js');assert.equal((router.match(/document\.startViewTransition\(commit\)/g)||[]).length,1);const html=read('notes/index.html');assert.equal((html.match(/data-nav-key=/g)||[]).length,6);assert.equal((html.match(/<header\b/g)||[]).length,1);});
test('handoff, version distinction and scope are documented',()=>{for(const f of ['START_HERE.md','HANDOFF.md','CHANGELOG.md','TEST_REPORT.md','ACCEPTANCE.md'])assert.ok(read('docs/design-r12/'+f).length>30);assert.ok(read('docs/design-r12/HANDOFF.md').includes('M03'));});
