import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import os from'node:os';import vm from'node:vm';import{fileURLToPath}from'node:url';
import{load,planCollections,build,wireHTML,hash,audit,safe}from'../scripts/workshop/build.mjs';
const ROOT=fileURLToPath(new URL('../',import.meta.url));
function apis(){const c=vm.createContext({URL});for(const p of ['ui/site-actions.js','workshop-media.js','workshop-cards.js'])vm.runInContext(fs.readFileSync(ROOT+'assets/'+p,'utf8'),c);return c;}
const C=apis(),M=C.SITE_MEDIA,W=C.SITE_WORKSHOP;
const manifest=JSON.parse(fs.readFileSync(ROOT+'content/presentation.json'));
const item={id:'new-thing',title:'很长的标题 / A readable long title',summary:'全部介绍应当保留，不使用 line-clamp 隐藏。',tags:['项目'],detailUrl:'projects/new-thing/',visibility:'public',primaryType:'project'};
test('six background presets have explicit types',()=>{assert.equal(Object.keys(M.presets).length,6);assert.ok(M.presets.poster.includes('image'));});
test('supplied presentation manifest validates',()=>assert.equal(M.validateManifest(manifest),manifest));
for(const preset of ['character-paper','character-night','poster','interface','pixel-window'])test('image preset '+preset,()=>assert.ok(M.render({kind:'image',preset,src:'assets/a.webp'}).includes('pw-media--'+preset)));
for(const src of ['javascript:alert(1)','data:image/png;base64,a','../a.png','a/../b.webp','a/%2e%2e/b.png','//evil.invalid/a.png','https://u:p@example.com/a.png','a\\b.png','a.png\" onerror=alert(1)','a.woff2'])test('reject unsafe or nonimage '+src,()=>assert.throws(()=>M.validateEntry({kind:'image',preset:'poster',src})));
test('unknown config field is an error',()=>assert.throws(()=>M.validateEntry({kind:'diagram',preset:'blueprint',css:'position:fixed'}),/未知字段/));
test('unknown preset is an error',()=>assert.throws(()=>M.validateEntry({kind:'image',preset:'invented',src:'a.png'})));
test('poster and character cropping rejected',()=>{for(const p of ['poster','interface','character-paper','character-night'])assert.throws(()=>M.validateEntry({kind:'image',preset:p,src:'a.png',fit:'cover'}));});
test('pixel window can opt into cropping',()=>assert.ok(M.render({kind:'image',preset:'pixel-window',src:'a.png',fit:'cover'}).includes('object-fit:cover')));
test('positions constrained to finite percentages',()=>{for(const p of ['101% 50%','0; color:red','50%','NaN% 0%'])assert.throws(()=>M.validateEntry({kind:'image',preset:'poster',src:'a.png',position:p}));});
test('sprite remains first-row-only',()=>assert.throws(()=>M.validateEntry({...manifest.entries['project-q-mimi'],sprite:{width:96,height:104,columns:8,rows:11,frames:9,durationMs:1560}})));
test('sprite uses relative sheet sizing and finite animation',()=>{const s=M.render(manifest.entries['project-q-mimi']);assert.ok(s.includes('--pw-columns:8'));assert.ok(s.includes('--pw-strip-end:-75%'));const css=fs.readFileSync(ROOT+'assets/workshop-media.css','utf8');assert.ok(css.includes('steps(var(--pw-frames)) 2'));assert.ok(css.includes('animation:none'));});
test('new IDs use data mapping, not project branches',()=>{const h=W.projectCard({...item,id:'third-character'},0,{manifest:{entries:{'third-character':{kind:'image',preset:'character-night',src:'characters/a.png'}}}});assert.ok(h.includes('pw-media--character-night'));assert.ok(!fs.readFileSync(ROOT+'assets/workshop-cards.js','utf8').includes('q-mimi'));});
test('card tone not chosen from list index',()=>assert.equal(W.projectCard(item,0).match(/class="pw-work-card[^"]*/)[0],W.projectCard(item,1).match(/class="pw-work-card[^"]*/)[0]));
test('markup escapes titles and descriptions',()=>{const h=W.projectCard({...item,title:'<script>bad()</script>',summary:'<img onerror=bad src=x>'});assert.ok(h.includes('&lt;script&gt;'));assert.ok(!h.includes('<script>'));});
test('content objects are not mutated',()=>{const before=JSON.stringify(item);W.projectCard(item);M.resolve(item);assert.equal(JSON.stringify(item),before);});
test('unsafe actions are rejected',()=>assert.throws(()=>W.projectCard({...item,detailUrl:'javascript:evil()'})));
test('images eager for first row, lazy afterwards',()=>{const e={kind:'image',preset:'poster',src:'a.png'};assert.ok(M.render(e,{index:1}).includes('loading="eager"'));assert.ok(M.render(e,{index:2}).includes('loading="lazy"'));});
test('uniform grid has no first child exception',()=>{const css=fs.readFileSync(ROOT+'assets/workshop-components.css','utf8');assert.ok(!/first-child|grid-column:1\/-1/.test(css));assert.ok(css.includes('repeat(2,minmax(0,1fr))'));assert.ok(css.includes('@media(max-width:680px)'));});
test('empty content renders truthful empty states',()=>{assert.ok(W.renderCollection('projects',{items:[],tools:[]}).includes('新作品正在准备中'));assert.ok(!W.renderCollection('games',{items:[],tools:[]}).includes('pw-game-card'));});
test('all game actions retained without nested links',()=>{const g={...item,primaryType:'game',localUrl:'games/a/play.html',detailUrl:'games/a/',cover:'a.png',downloadUrl:'downloads/a.zip',videoUrl:'https://example.com/v'};const h=W.gameCard(g);assert.ok(h.includes(' download'));assert.ok(h.includes('观看视频'));assert.ok(h.includes('游戏介绍'));assert.ok(h.includes('开始试玩'));assert.equal((h.match(/<a /g)||[]).length,4);});
test('wireHTML is idempotent',()=>{const t='<head></head><body><script src="/assets/site-shell.js"></script></body>';const h=wireHTML(t);assert.equal(wireHTML(h),h);assert.equal((h.match(/data-media-css/g)||[]).length,1);assert.ok(h.indexOf('workshop-cards.js')<h.indexOf('site-shell.js'));});
test('wireHTML rejects missing/duplicate core scripts',()=>{assert.throws(()=>wireHTML('<head></head>'));assert.throws(()=>wireHTML('<head></head><script src="/assets/site-shell.js"></script><script src="/assets/site-shell.js"></script>'));});
async function temp(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'r07-build-'));function put(p,t){fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,t);}
 for(const p of ['assets/ui/site-actions.js','assets/workshop-media.js','assets/workshop-cards.js','content/presentation.json'])put(p,fs.readFileSync(ROOT+p));
 put('content/site-data.js','globalThis.SITE_DATA='+JSON.stringify({items:[item],tools:[],evidence:[]})+';');
 for(const p of ['projects','games','tools'])put(p+'/index.html',`<head><title>${p}</title></head><body data-page="${p}"><div id="app" data-prerendered="true"><header>KEEP HEADER</header><main id="main">old</main><footer>KEEP FOOTER</footer></div><script src="/assets/site-shell.js"></script></body>`);
 try{return await fn(root,put);}finally{fs.rmSync(root,{recursive:true,force:true});}}
async function seed(root,put){const p=await planCollections(root);for(const [f,b]of p.pages)put(f,b);put('docs/design-r07/generated-pages.json',JSON.stringify({schemaVersion:1,version:'workshop-r08',files:Object.fromEntries([...p.pages].map(([f,b])=>[f,hash(b)]))},null,2)+'\n');}
test('shared static renderer preserves host and no-JS content',()=>temp(async(root,put)=>{const p=await planCollections(root);const h=p.pages.get('projects/index.html').toString();assert.ok(h.includes('KEEP HEADER'));assert.ok(h.includes('KEEP FOOTER'));assert.ok(h.includes(item.summary));assert.ok(h.includes('data-prerendered="true"'));}));
test('second build is byte-stable',()=>temp(async(root,put)=>{await seed(root,put);assert.equal((await build(root)).changed,0);assert.equal((await build(root,{check:true})).changed,0);}));
test('changed content requires rebuild',()=>temp(async(root,put)=>{await seed(root,put);put('content/site-data.js','globalThis.SITE_DATA='+JSON.stringify({items:[{...item,title:'New title'}],tools:[]})+';');await assert.rejects(()=>build(root,{check:true}),/未构建/);assert.ok((await build(root)).changed>0);assert.ok(fs.readFileSync(root+'/projects/index.html','utf8').includes('New title'));}));
test('manual generated edits are protected',()=>temp(async(root,put)=>{await seed(root,put);fs.appendFileSync(root+'/projects/index.html','CUSTOM');await assert.rejects(()=>build(root),/手工修改/);}));
test('missing collection template is an explicit error',()=>temp(async(root)=>{fs.rmSync(root+'/games/index.html');await assert.rejects(()=>planCollections(root),/缺少必要/);}));
test('asset audit never treats missing as verified',()=>temp(async(root,put)=>{put('content/site-data.js','globalThis.SITE_DATA='+JSON.stringify({items:[{...item,cover:'assets/missing.png'}],tools:[]})+';');const r=await audit(root);assert.equal(r.missing,1);}));
test('path traversal and symlink rejected in builder',()=>temp(async(root)=>{assert.throws(()=>safe(root,'../a'));const target=path.join(root,'link-target');fs.mkdirSync(target);fs.symlinkSync(target,path.join(root,'link'),process.platform==='win32'?'junction':'dir');assert.throws(()=>safe(root,'link/a'));}));
