import {loadPixelFont} from './chill-font.mjs';
import {createGamepadInput} from './editor-gamepad.mjs';
import {enemySprite,orderedTerrain} from './map-appearance.mjs';
import {createSound,themeFor} from './editor-audio.mjs';
import {background,drawTile,drawObject,drawPlayer,drawScenery,preloadArt,drawReference,drawHud} from './editor-art.mjs';
import {createStageCatalog} from './runtime/stage-catalog.mjs';
import {createPlatformStage} from './editor-mario-stage.mjs';
import {createPlatformMotor} from './editor-mario-motor.mjs';
/** Uses the existing platform driver, not a separate approximation of its physics. */
export async function play(pack,rooms=[],media={},options={}){
 await Promise.all([preloadArt(rooms),loadPixelFont()]);
 const hudLogo=new Image();hudLogo.src=media.brandCore||'/assets/q-logo-pixel-core.svg';await hudLogo.decode();
 const hudMark=document.createElement('canvas');hudMark.width=hudMark.height=16;const markContext=hudMark.getContext('2d');markContext.imageSmoothingEnabled=false;markContext.drawImage(hudLogo,0,0,16,16);markContext.globalCompositeOperation='source-in';markContext.fillStyle='#ffffff';markContext.fillRect(0,0,16,16);
 const markPixels=markContext.getImageData(0,0,16,16).data;let markTop=16,markBottom=0,markLeft=16,markRight=0;for(let y=0;y<16;y++)for(let x=0;x<16;x++)if(markPixels[(y*16+x)*4+3]){markLeft=Math.min(markLeft,x);markRight=Math.max(markRight,x+1);markTop=Math.min(markTop,y);markBottom=Math.max(markBottom,y+1);}const markCenter=(markTop+markBottom)/2;
 const sound=createSound(media);
 const dialog=document.createElement('dialog'),title=document.createElement('h2'),info=document.createElement('p'),canvas=document.createElement('canvas'),close=document.createElement('button'),restart=document.createElement('button'),continueButton=document.createElement('button'),bar=document.createElement('div');
 const brand=document.createElement('a'),logo=document.createElement('img');
 brand.href='https://aha-xiaoq.github.io/';brand.target='_blank';brand.rel='noopener';brand.setAttribute('aria-label','在下_小Q · 打开网站');
 brand.style.cssText='display:inline-flex;align-items:center;flex:none;color:inherit;text-decoration:none;line-height:0';
 logo.src=media.brandLogo||'/assets/q-logo-pixel-framed.svg';logo.alt='Q 标志';
 for(const img of [logo]){img.width=32;img.height=32;img.style.cssText='width:32px;height:32px;object-fit:contain;vertical-align:middle;border-radius:5px';}
 brand.append(logo);title.style.cssText='display:flex;align-items:center;gap:12px;line-height:1.3;font-size:20px';title.append(brand,document.createTextNode('在下_小Q 试玩地图'));info.textContent='方向键 / A、D 移动，按住空格跳高，Shift / J / X 加速，火焰形态按这些键发射火球，↑ 攀爬藤蔓，↓ / S 下蹲，↓ / E 进入管道。触屏：A 跳跃，B / X / Y 加速及火球，↑ 进管道，↓ 下蹲 / 进管道；可同时按住方向与动作键。';
 canvas.width=512;canvas.height=480;canvas.style.width='100%';canvas.style.maxWidth='768px';canvas.style.margin='auto';canvas.style.imageRendering='pixelated';canvas.style.height='auto';canvas.tabIndex=0;canvas.setAttribute('aria-label','基础平台运行时试跑');
 close.textContent='返回编辑';restart.textContent='重新开始';continueButton.textContent='从当前位置继续';continueButton.hidden=true;continueButton.title='保留当前地图位置继续测试';bar.className='row';bar.append(continueButton,restart,close);const mute=document.createElement('button');mute.textContent='声音：开';mute.onclick=()=>{mute.textContent=sound.toggle()?'声音：开':'声音：关';};bar.append(mute);
 const touch={},pending={},held=new Map(),controlButtons=[];
 const controls=document.createElement('div'),pad=document.createElement('div'),dpad=document.createElement('div'),actions=document.createElement('div');
 controls.className='play-controls';pad.className='play-gamepad';pad.setAttribute('aria-label','触屏手柄');dpad.className='play-dpad';actions.className='play-actions';
 const middle=document.createElement('div'),pauseButton=document.createElement('button');middle.className='play-pad-middle';mute.textContent='BGM';mute.title='声音开关';mute.setAttribute('aria-label','声音开关');mute.onclick=()=>{const on=sound.toggle();mute.setAttribute('aria-pressed',String(!on));mute.title=on?'声音：开':'声音：关';};pauseButton.textContent='START';pauseButton.title='暂停 / 继续';pauseButton.setAttribute('aria-label','暂停 / 继续');const padLogo=logo.cloneNode();padLogo.src=media.brandCore||'/assets/q-logo-pixel-core.svg';padLogo.alt='Q 标志';padLogo.className='play-pad-logo';padLogo.style.cssText='width:32px;height:32px;object-fit:contain;grid-column:1 / -1;justify-self:center;transform:translateY(-20px)';padLogo.style.transform='translate('+ (16-markLeft-markRight)+'px,-20px)';middle.append(padLogo,mute,pauseButton);pad.append(dpad,middle,actions);controls.append(bar,pad);
 for(const [key,label,description,parent]of [['interact','↑','进入管道',dpad],['left','←','向左移动',dpad],['down','↓','下蹲 / 进入管道',dpad],['right','→','向右移动',dpad],['run','X','加速 / 火球',actions],['runB','A','跳跃',actions],['jumpAlt','B','加速 / 火球',actions],['runAlt','Y','加速 / 火球',actions]]){
  const b=document.createElement('button');b.type='button';b.dataset.control=key;b.setAttribute('aria-label',description);b.setAttribute('aria-pressed','false');b.innerHTML='<strong>'+label+'</strong><small>'+description+'</small>';controlButtons.push(b);
  const update=()=>{touch[key]=[...held.values()].includes(key);b.classList.toggle('held',!!touch[key]);b.setAttribute('aria-pressed',String(!!touch[key]));};
  b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,key);update();if(['jump','interact','attack'].includes(key))pending[key]=true;if(key==='jumpAlt'&&faceLayout==='right')pending.jump=true;if(key==='runB'&&faceLayout==='bottom')pending.jump=true;if(key==='down')pending.interact=true;};
  b.onpointerup=b.onpointercancel=b.onlostpointercapture=e=>{held.delete(e.pointerId);update();};
  b.oncontextmenu=e=>e.preventDefault();parent.append(b);
 }
 const clearTouch=()=>{held.clear();for(const k of Object.keys(touch))touch[k]=false;for(const k of Object.keys(pending))pending[k]=false;for(const b of controlButtons){b.classList.remove('held');b.setAttribute('aria-pressed','false');}};
 let faceLayout='bottom';
 const faceLabels={bottom:{runAlt:['Y','加速 / 火球'],run:['X','加速 / 火球'],jumpAlt:['B','加速 / 火球'],runB:['A','跳跃']},right:{runAlt:['X','加速 / 火球'],run:['Y','加速 / 火球'],jumpAlt:['A','跳跃'],runB:['B','加速 / 火球']}};
 const updateFaceLabels=layout=>{for(const b of controlButtons){const pair=faceLabels[layout]?.[b.dataset.control];if(!pair)continue;b.querySelector('strong').textContent=pair[0];b.querySelector('small').textContent=pair[1];b.setAttribute('aria-label',pair[1]);}};
 const screen=document.createElement('section'),fullscreen=document.createElement('button'),screenStyle=document.createElement('style');
 screen.className='workshop-play-screen';fullscreen.textContent='全屏';fullscreen.type='button';fullscreen.setAttribute('aria-pressed','false');bar.prepend(fullscreen);
 screenStyle.textContent=`.workshop-play-screen:fullscreen{box-sizing:border-box;width:100vw;height:100dvh;padding:12px;background:#101015;color:#f7f4ea;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;gap:8px;overflow:hidden}.workshop-play-screen:fullscreen h2{font-size:18px;margin:0}.workshop-play-screen:fullscreen p{font-size:12px;margin:0;line-height:1.4}.workshop-play-screen:fullscreen canvas{display:block;width:100%!important;height:100%!important;max-width:none!important;max-height:none!important;min-height:0;object-fit:contain;border:0;margin:0!important}.workshop-play-screen:fullscreen .row{display:flex;justify-content:center;flex-wrap:wrap;gap:6px;margin:0}.workshop-play-screen:fullscreen button{font:inherit;min-height:36px;padding:6px 12px;color:#f7f4ea;background:#23232c;border:1px solid #666;cursor:pointer}@media(max-height:480px){.workshop-play-screen:fullscreen p{display:none}.workshop-play-screen:fullscreen{grid-template-rows:auto minmax(0,1fr) auto;padding:6px;gap:4px}}`;
 screenStyle.textContent+=`.workshop-play-screen .play-gamepad[hidden]{display:none!important}.workshop-play-screen .play-gamepad{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:12px;width:min(100%,440px);margin:10px auto 0;padding:14px 16px;background:linear-gradient(#dedee2,#b4b5bf);border:2px solid #8a8b98;border-radius:60px 60px 76px 76px;box-shadow:inset 0 3px 0 #f5f5f7,inset 0 -7px 0 #92939f,0 5px 0 #14141d;touch-action:none;user-select:none;-webkit-user-select:none}.workshop-play-screen .play-dpad,.workshop-play-screen .play-actions{display:grid;grid-template-columns:repeat(3,40px);grid-template-rows:repeat(3,40px);place-items:center;flex-shrink:0}.workshop-play-screen .play-gamepad button{box-sizing:border-box;margin:0;min-width:44px;min-height:44px;padding:0;border:1px solid #15151e;background:#30313b;color:#fff;box-shadow:0 3px 0 #161620;touch-action:none;transform:none;font:11px system-ui}.play-gamepad strong{font:bold 18px system-ui}.play-dpad small{display:none}.play-dpad [data-control=interact]{grid-column:2;grid-row:1}.play-dpad [data-control=left]{grid-column:1;grid-row:2}.play-dpad [data-control=down]{grid-column:2;grid-row:3}.play-dpad [data-control=right]{grid-column:3;grid-row:2}.play-dpad:after{content:'';grid-column:2;grid-row:2;width:40px;height:40px;background:#30313b}.play-actions [data-control=runAlt]{grid-column:2;grid-row:1}.play-actions [data-control=run]{grid-column:1;grid-row:2}.play-actions [data-control=jumpAlt]{grid-column:3;grid-row:2}.play-actions [data-control=runB]{grid-column:2;grid-row:3}.workshop-play-screen .play-actions button{width:48px;height:48px;border-radius:50%;background:#56518c;border:1px solid #35315b}.play-actions small{display:block;font:9px/1.2 system-ui}.play-pad-middle{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;align-self:center}.workshop-play-screen .play-pad-middle button{min-width:48px;min-height:44px;border:0;border-radius:20px;background:#545560;font-size:10px;box-shadow:inset 0 -3px #33343e}.workshop-play-screen .play-gamepad button.held,.workshop-play-screen .play-gamepad button[aria-pressed=true]{background:#faf0bf;color:#15151e;box-shadow:none}.workshop-play-screen .play-gamepad button:focus-visible{outline:3px solid #ffce54;outline-offset:3px}@media(max-width:520px){.workshop-play-screen .play-gamepad{padding:12px 8px;gap:4px}.workshop-play-screen .play-dpad,.workshop-play-screen .play-actions{grid-template-columns:repeat(3,34px);grid-template-rows:repeat(3,36px)}.play-pad-middle{flex-direction:row;gap:4px}.workshop-play-screen .play-pad-middle button{min-width:42px;min-height:44px}.workshop-play-screen .play-actions button{width:44px;height:44px}.play-controls .row button{font-size:12px;padding:6px 8px}}@media(max-height:480px){.workshop-play-screen:fullscreen .play-gamepad{padding-top:6px;padding-bottom:6px;margin-top:4px}.workshop-play-screen:fullscreen .play-controls .row button{min-height:28px;padding:3px 8px}}`;
 screenStyle.textContent+=`@media(orientation:landscape){.workshop-play-screen:fullscreen{position:relative;display:block;padding:0!important}.workshop-play-screen:fullscreen>canvas{position:absolute;inset:0;width:100%!important;height:100%!important;pointer-events:none}.workshop-play-screen:fullscreen>h2{position:absolute;top:max(8px,env(safe-area-inset-top));left:max(8px,env(safe-area-inset-left));z-index:2;font-size:14px!important;gap:6px!important}.workshop-play-screen:fullscreen>p{display:none}.workshop-play-screen:fullscreen .play-controls,.workshop-play-screen:fullscreen .play-gamepad:not([hidden]){display:contents}.workshop-play-screen:fullscreen .play-dpad{position:absolute;left:max(14px,env(safe-area-inset-left));top:55%;transform:translateY(-50%);z-index:2}.workshop-play-screen:fullscreen .play-actions{position:absolute;right:max(14px,env(safe-area-inset-right));top:55%;bottom:auto;transform:translateY(-50%);z-index:2}.workshop-play-screen:fullscreen .play-pad-middle{position:absolute;left:max(20px,env(safe-area-inset-left));top:calc(55% - 112px);bottom:auto;z-index:2;gap:4px 8px}.workshop-play-screen:fullscreen .play-controls .row{position:absolute;right:max(10px,env(safe-area-inset-right));top:8px;width:122px;display:grid;grid-template-columns:1fr;gap:4px;z-index:2}.workshop-play-screen:fullscreen .play-controls .row button{min-height:30px;padding:3px 6px;font-size:12px;background:#23232ce8}.workshop-play-screen:fullscreen .play-pad-logo{display:none}.workshop-play-screen:fullscreen .play-pad-middle button{min-height:40px}.workshop-play-screen:fullscreen .play-actions button{width:48px;height:48px}@media(max-width:640px){.workshop-play-screen:fullscreen .play-dpad,.workshop-play-screen:fullscreen .play-actions{grid-template-columns:repeat(3,32px);grid-template-rows:repeat(3,36px)}.workshop-play-screen:fullscreen .play-controls .row{width:98px}.workshop-play-screen:fullscreen .play-pad-middle{left:8px}.workshop-play-screen:fullscreen .play-dpad{left:8px}.workshop-play-screen:fullscreen .play-actions{right:8px}}}`;
 screenStyle.textContent+=`@media(orientation:landscape) and (min-height:501px){.workshop-play-screen:fullscreen>h2{top:20px;left:20px;font-size:18px!important}.workshop-play-screen:fullscreen>p{display:block;position:absolute;left:20px;top:70px;width:max(110px,calc((100vw - 100dvh * 16 / 15) / 2 - 40px));max-width:280px;z-index:2;line-height:1.8;font-size:13px}.workshop-play-screen:fullscreen .play-controls .row{top:20px;right:20px;width:140px;gap:10px}.workshop-play-screen:fullscreen .play-controls .row button{min-height:40px;font-size:14px}}`;
 let deathUiHidden=null;const restoreDeathUi=()=>{if(deathUiHidden!==null){screen.classList.toggle('play-ui-hidden',deathUiHidden);menuToggle.setAttribute('aria-expanded',String(!deathUiHidden));deathUiHidden=null;}};const menuToggle=document.createElement('button');menuToggle.type='button';menuToggle.textContent='在下_小Q 试玩地图';menuToggle.title='显示 / 隐藏操作面板';menuToggle.setAttribute('aria-label','显示 / 隐藏操作面板');menuToggle.setAttribute('aria-expanded','true');title.lastChild.replaceWith(menuToggle);menuToggle.onclick=()=>{const hidden=screen.classList.toggle('play-ui-hidden');menuToggle.setAttribute('aria-expanded',String(!hidden));};
 screenStyle.textContent+=`.workshop-play-screen>h2>button{font:inherit;color:inherit;background:none!important;border:0!important;padding:0!important;cursor:pointer}.workshop-play-screen.play-ui-hidden>p,.workshop-play-screen.play-ui-hidden .play-controls>.row{display:none!important}.workshop-play-screen:fullscreen>p{box-sizing:border-box;padding:12px;border-radius:8px;background:#191920ed}.workshop-play-screen:fullscreen .play-controls>.row{padding:8px;border-radius:8px;background:#191920ed}`;
 screen.append(title,info,canvas,controls);dialog.style.width='1000px';dialog.style.maxWidth='95vw';dialog.append(screenStyle,screen);document.body.append(dialog);
 const fullscreenChanged=()=>{const active=document.fullscreenElement===screen;fullscreen.textContent=active?'退出全屏':'全屏';fullscreen.setAttribute('aria-pressed',String(active));hidePad.hidden=!active;screen.classList.toggle('play-ui-hidden',active);menuToggle.setAttribute('aria-expanded',String(!active));clearTouch();pad.hidden=active;hidePad.textContent=active?'显示手柄':'隐藏手柄';hidePad.setAttribute('aria-expanded',String(!active));canvas.focus();};
 fullscreen.disabled=!document.fullscreenEnabled;
 if(fullscreen.disabled){fullscreen.textContent='浏览器不支持全屏';}
 fullscreen.onclick=async()=>{try{if(document.fullscreenElement===screen)await document.exitFullscreen();else await screen.requestFullscreen();}catch{fullscreen.textContent='全屏未开启，点击重试';} };
 document.addEventListener('fullscreenchange',fullscreenChanged);
 const hidePad=document.createElement('button');hidePad.type='button';hidePad.textContent='隐藏手柄';hidePad.hidden=true;hidePad.setAttribute('aria-expanded','true');bar.append(hidePad);
 hidePad.onclick=()=>{clearTouch();pad.hidden=!pad.hidden;hidePad.textContent=pad.hidden?'显示手柄':'隐藏手柄';hidePad.setAttribute('aria-expanded',String(!pad.hidden));canvas.focus();};
 let catalog=createStageCatalog(pack),plan=catalog.plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true});let advancing=false,advanceTimer;let stage,keys=new Set(),last=0,acc=0,raf,paused=false;
 const reset=()=>{advancing=false;clearTimeout(advanceTimer);sound.stop();stage?.dispose();stage=createPlatformStage({plan,motor:createPlatformMotor(),visualRooms:rooms,initialState:options.initialState,autoContinue:options.developerMode!==false,allowWarp:!!options.onWarp,emit:(type,data)=>{if(type==='sound')sound.effect(data.event);}});keys.clear();clearTouch();acc=0;};
 pauseButton.onclick=()=>{paused=!paused;keys.clear();clearTouch();pauseButton.setAttribute('aria-pressed',String(paused));pauseButton.title=paused?'继续':'暂停';if(paused){sound.stop();stage.pause();}else{last=performance.now();stage.resume();canvas.focus();}sound.effect('pause');};
 reset();canvas.workshopRead=()=>({...stage.view(),audio:sound.snapshot()});restart.onclick=()=>{restoreDeathUi();reset();sound.unlock();sound.background(themeFor(rooms.find(r=>r.roomId===stage.view().roomId)?.setting));continueButton.hidden=true;paused=false;last=performance.now();canvas.focus();};continueButton.onclick=()=>{if(options.developerMode!==false&&stage.continueFromCurrent()){continueButton.hidden=true;paused=false;last=performance.now();restoreDeathUi();sound.unlock();sound.background(themeFor(rooms.find(r=>r.roomId===stage.view().roomId)?.setting));canvas.focus();}};close.onclick=()=>dialog.close();
 const keydown=e=>{if(e.code==='Enter'&&stage.view().completed){e.preventDefault();e.stopPropagation();restart.click();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyA','KeyD','KeyS','KeyJ','KeyX','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();e.stopPropagation();keys.add(e.code);if(!e.repeat){if(e.code==='Space')pending.jump=true;if(['KeyJ','KeyX','ShiftLeft','ShiftRight'].includes(e.code))pending.attack=true;if(['KeyE','ArrowDown'].includes(e.code))pending.interact=true;}}},keyup=e=>keys.delete(e.code);
 const blur=()=>{keys.clear();clearTouch();paused=true;sound.stop();stage.pause();},focus=()=>{paused=false;last=performance.now();stage.resume();};
 window.addEventListener('keydown',keydown,true);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);window.addEventListener('focus',focus);
 const gamepadLayout=document.createElement('select');gamepadLayout.setAttribute('aria-label','外接手柄 A 键位置');for(const [value,label]of [['auto','手柄布局：自动'],['bottom','A 在下方（Xbox）'],['right','A 在右方（Nintendo）']])gamepadLayout.add(new Option(label,value));info.append(document.createElement('br'),gamepadLayout);
 const resolveFaceLayout=gp=>gamepadLayout.value==='right'||(gamepadLayout.value==='auto'&&/Nintendo|Switch|Joy-Con|Pro Controller/i.test(gp?.id||''))?'right':'bottom';
 gamepadLayout.onchange=()=>{clearTouch();faceLayout=resolveFaceLayout();updateFaceLabels(faceLayout);};updateFaceLabels(faceLayout);
 const readGamepad=createGamepadInput(undefined,()=>gamepadLayout.value);
 const gamepadStatus=document.createElement("span");gamepadStatus.style.cssText="display:block;font-size:12px";info.append(gamepadStatus);
 function frame(now){
  if(!dialog.open)return;
  const gp=readGamepad();const nextFaceLayout=resolveFaceLayout(gp);if(nextFaceLayout!==faceLayout){faceLayout=nextFaceLayout;updateFaceLabels(faceLayout);}gamepadStatus.textContent=gp.connected?'外接手柄：'+gp.id+' · 方向键/左摇杆移动，A 跳跃，B 加速/火球，X/Y 同 B，START 暂停'+(gp.standard?'':'（非标准布局，按键可能不同）'):'外接手柄：连接后按任意键激活';
  const overlay=screen.querySelector('.campaign-card');if(!overlay){if(gp.pausePressed){if(stage.view().completed)restart.click();else pauseButton.click();}if(gp.mutePressed)mute.click();}
  acc+=Math.min(100,last?now-last:0);last=now;
  const virtualJump=faceLayout==='right'?touch.jumpAlt:touch.runB,virtualRun=faceLayout==='right'?(touch.run||touch.runAlt||touch.runB):(touch.run||touch.runAlt||touch.jumpAlt);
  while(acc>=1000/60){if(!paused)stage.step({x:(keys.has('ArrowRight')||keys.has('KeyD')||touch.right||gp.x>0?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')||touch.left||gp.x<0?1:0),run:keys.has('ShiftLeft')||keys.has('ShiftRight')||keys.has('KeyJ')||keys.has('KeyX')||virtualRun||gp.run,jump:keys.has('Space')||virtualJump||pending.jump||gp.jump,up:keys.has('ArrowUp')||touch.interact||(gp.interact&&!gp.down),down:keys.has('ArrowDown')||keys.has('KeyS')||touch.down||gp.down,attack:keys.has('KeyJ')||keys.has('KeyX')||touch.attack||virtualRun||pending.attack||gp.run,interact:keys.has('KeyE')||keys.has('ArrowDown')||touch.interact||touch.down||pending.interact||gp.interact});for(const k of Object.keys(pending))pending[k]=false;acc-=1000/60;}
  const v=stage.view();continueButton.hidden=true;if(options.developerMode===false&&(v.p?.dying||v.completed&&v.lives<=0)&&document.fullscreenElement===screen){if(deathUiHidden===null)deathUiHidden=screen.classList.contains('play-ui-hidden');screen.classList.remove('play-ui-hidden');menuToggle.setAttribute('aria-expanded','true');}if(v.completed&&v.warpTarget&&options.onWarp&&!advancing){advancing=true;options.onWarp(v.warpTarget,{lives:v.lives,coins:v.coins,score:v.score,power:v.p.power},session);}if(v.completed&&!v.warpTarget&&v.lives>0&&options.onComplete&&!advancing){advancing=true;advanceTimer=setTimeout(()=>{if(!dialog.open)return;options.onComplete({lives:v.lives,coins:v.coins,score:v.score,power:v.p.power},session);},1800);}
  const c=canvas.getContext('2d'),scale=2,camX=v.cam,camY=Math.max(0,Math.min(Math.max(0,v.height-240),v.p.y-100));
  const room={...(rooms.find(r=>r.roomId===v.roomId)||{}),playGeometry:v.geometry,finish:v.finish,tick:v.tick,renderBounds:{x:camX,y:camY,w:256,h:240}};
  c.imageSmoothingEnabled=false;background(c,room,512,480);c.save();c.scale(scale,scale);c.translate(-Math.round(camX),-Math.round(camY));
  if(!paused&&!v.completed&&!v.p.dying&&!v.finish)sound.background(themeFor(room.setting,!!v.p.star,v.timeLeft));else if(v.completed||v.p.dying||v.finish)sound.stopMusic();
  drawScenery(c,room);
  const visible=o=>o.x+o.w>=camX&&o.x<=camX+256&&o.y+o.h>=camY&&o.y<=camY+240;
  for(const vine of v.vines||[])drawReference(c,{kind:'active-vine',x:vine.x,y:vine.y,w:vine.w,h:vine.h},room);
  for(const marker of room.markers||[])if(/^(lava|water)-/.test(marker.kind))drawReference(c,marker,room);
  for(const g of room.decorations||[])if(!g.hidden&&visible(g))drawTile(c,g,room);
  const behind=o=>!!o.emerge||Number.isFinite(o.clipTop);
  const actor=o=>drawObject(c,{...o,skin:o.shell?(/beetle/i.test(o.type)?'beetleshell':'shell'):o.type||room.enemySkins?.[o.id]||room.markers?.find(m=>m.id===o.id)?.kind,source:{...o.source,frame:o.frame}},v.tick,room);
  for(const o of [...v.enemies,...v.items])if(behind(o)&&visible(o))actor(o);
  for(const g of orderedTerrain(room,v.geometry))if(!g.hidden&&visible(g))drawTile(c,{...g,y:g.y-(g.bump?Math.sin(g.bump/12*Math.PI)*6:0),material:g.used?'used':g.material||room.map?.geometry.find(q=>q.id===(g.sourceId||g.id))?.material},room);
  for(const marker of room.markers||[])if(!/^(lava|water)-/.test(marker.kind)&&!v.hiddenMarkers?.includes(marker.id)&&marker.kind!=='decorative-trunk'&&!enemySprite(marker.kind)&&marker.kind!=='marker-Bowser')drawReference(c,marker,room);
  for(const o of [...v.objects,...v.enemies,...v.items])if(!['spawn','portal'].includes(o.kind)&&!behind(o)&&visible(o))actor(o);
  if(v.finish?.castle||v.finish?.phase!=='score'){c.save();if(v.transition){c.beginPath();if(v.transition.clipTop!=null)c.rect(camX,camY,256,Math.max(0,v.transition.clipTop-camY));else c.rect(camX,camY,Math.max(0,v.transition.clipRight-camX),240);c.clip();}drawPlayer(c,v.p,v.tick,room.playerSkin);c.restore();}c.restore();c.save();c.scale(2,2);c.drawImage(hudMark,Math.round(12-(markLeft+markRight)/2),3,16,16);c.fillStyle='#fff';c.textAlign='left';c.font='8px ChillBitmap';c.textBaseline='alphabetic';const brandMetrics=c.measureText('在下小Q · 非官方同人');c.fillText('在下小Q · 非官方同人',24+brandMetrics.actualBoundingBoxLeft,Math.round(3+markCenter+(brandMetrics.actualBoundingBoxAscent-brandMetrics.actualBoundingBoxDescent)/2));c.textBaseline='alphabetic';drawHud(c,v,pack.stages[0].title.match(/[1-8]-[1-4]/)?.[0]||'--');c.restore();if(v.completed){c.fillStyle='rgba(16,16,22,.88)';c.fillRect(80,174,352,126);c.fillStyle='#faf7eb';c.textAlign='center';c.font='32px ChillBitmap16';c.fillText(v.lives>0?'关卡完成':'游戏结束',256,218);c.font='16px ChillBitmap16';c.fillText((options.onComplete&&v.lives>0?(options.completionMessage||'即将进入下一关…'):'按 Enter 或点击「重新开始」再玩一次'),256,262);}raf=requestAnimationFrame(frame);
 }
 dialog.onclose=()=>{clearTimeout(advanceTimer);document.removeEventListener('fullscreenchange',fullscreenChanged);if(document.fullscreenElement===screen)document.exitFullscreen().catch(()=>{});cancelAnimationFrame(raf);sound.stop();stage.dispose();window.removeEventListener('keydown',keydown,true);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);window.removeEventListener('focus',focus);dialog.remove();};
 const session={screen,media,close:()=>dialog.close(),async load(nextPack,nextRooms,nextOptions){await preloadArt(nextRooms);if(!dialog.open)return;pack=nextPack;rooms=nextRooms;options=nextOptions;catalog=createStageCatalog(pack);plan=catalog.plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true});reset();paused=false;last=performance.now();canvas.focus();}};
 dialog.showModal();canvas.focus();raf=requestAnimationFrame(frame);return session;
}
