// Generated by showcase:build; edit content/about-view.json.
globalThis.SITE_ABOUT_SUPPORT = Object.freeze({"schemaVersion":1,"avatar":{"src":"/assets/identity/xiaoq-avatar-p63a.svg?v=dd5b8227f5b3e07a8da6","alt":"小Q像素头像：黄色皮卡丘头套、黑框眼镜与 Q 标识"},"guestbookHref":"/guestbook/","beforeHtml":"","afterHtml":""});
