import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {mainSection,headerMutation,MENU_QUERY} from '../../assets/ui/site-refinement.mjs';
import {selectProjects,renderProjectCards,render} from '../../assets/journal/render.mjs';
import {wireExperience} from '../../scripts/experience/wire.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const read=p=>fs.readFileSync(root+p,'utf8');
const project=JSON.parse(read('content/development/projects/mario-mix.json'));
const catalog=JSON.parse(read('content/development/catalog.json'));
const projects=catalog.projects.map(x=>JSON.parse(read(x.file)));
for(const [url,section] of [['/','home'],['/index.html','home'],['/projects/q-mimi/','projects'],['/games/mario-mix-3/index.html','games'],['/notes/mario-mix/docs/terra-source/','notes'],['/dev/','notes'],['/about/','about'],['/search/',null]])test('main navigation context '+url,()=>assert.equal(mainSection(url),section));
test('breakpoint is a shared fixed contract',()=>assert.equal(MENU_QUERY,'(max-width: 720px)'));
test('typing in content is not treated as a header mutation',()=>assert.equal(headerMutation([{target:{closest:()=>null},addedNodes:[{nodeType:3}]}]),false));
test('header insertions request initialization',()=>assert.equal(headerMutation([{target:{closest:()=>null},addedNodes:[{nodeType:1,matches:()=>true}]}]),true));
test('language buttons added inside header are handled',()=>assert.equal(headerMutation([{target:{closest:()=>({})},addedNodes:[]}]),true));
test('visible projects share one matching/count algorithm',()=>{const r=selectProjects(projects);assert.equal(r.count,projects.filter(x=>x.visibility==='public').length);});
test('search trims input and uses case-insensitive matching',()=>assert.deepEqual(selectProjects(projects,{q:'  '+project.title+'  '}).items.map(x=>x.id),[project.id]));
test('draft projects never leak into matching counts',()=>assert.equal(selectProjects([...projects,{...project,id:'private',visibility:'draft'}]).count,selectProjects(projects).count));
test('archived projects are explicit, not mixed into default',()=>assert.equal(selectProjects([{...project,visibility:'archived'}]).count,0));
test('category counts are filtered, not global totals',()=>assert.equal(selectProjects(projects,{category:'game'}).count,projects.filter(x=>x.visibility==='public'&&x.category==='game').length));
test('empty result preserves actionable recovery',()=>{assert.equal(selectProjects(projects,{q:'no-matching-xyz'}).count,0);assert.match(renderProjectCards(projects,{q:'no-matching-xyz'}),/data-reset-projects/);});
test('pagination clamps out-of-range URLs',()=>{const many=Array.from({length:17},(_,i)=>({...project,id:'p-'+i}));const r=selectProjects(many,{page:999});assert.equal(r.current,3);assert.equal(r.items.length,5);});
test('clear project labels and independent live count exist in static output',()=>{const h=render({view:'index'},{catalog,projects,states:{},notes:[]});assert.match(h,/j-search-label/);assert.match(h,/data-project-result-status/);assert.match(h,/data-clear-project-filters hidden/);assert.doesNotMatch(h,/data-project-results[^>]*aria-live/);});
test('individual guide breadcrumb includes navigable guides parent',()=>{const h=render({view:'docs',projectId:'mario-mix',doc:'terra-source'},{catalog,projects,states:{}});const crumb=h.match(/class="j-breadcrumb"[\s\S]*?<\/div>/)[0];assert.match(crumb,/href="\/notes\/mario-mix\/docs\/"/);assert.match(crumb,/aria-current="page">第三期开发源码/);});
test('HTML wiring is idempotent and has just one existing experience loader',()=>{const h=read('notes/index.html'),w=wireExperience(h);assert.equal(wireExperience(w),w);assert.equal((w.match(/data-experience-module/g)||[]).length,1);assert.match(w,/runtime\.mjs\?v=site-r23/);});
test('refinement CSS is centrally imported once',()=>assert.equal((read('assets/experience/site-experience.css').match(/site-refinement\.css\?v=site-r23/g)||[]).length,1));
test('atlas overrides more-specific legacy prose width',()=>assert.match(read('assets/ui/site-refinement.css'),/#app \.journal \.j-reading:has\(\.q-atlas\)\{max-width:none\}/));
test('new controls provide reduced motion and forced-color fallback',()=>{const s=read('assets/ui/site-refinement.css');assert.match(s,/prefers-reduced-motion/);assert.match(s,/forced-colors/);assert.match(s,/min-height:44px/);});
test('module has no telemetry, persistence, route hijack or innerHTML menu generation',()=>{const s=read('assets/ui/site-refinement.mjs');assert.doesNotMatch(s,/fetch\(|localStorage|sessionStorage|pushState|innerHTML|document\.body\.style\.overflow/);});
test('composition cancels delayed full-site search',()=>assert.match(read('assets/experience/runtime.mjs'),/compositionstart[^\n]*clearTimeout\(queryTimer\)/));
test('project search waits for committed IME input',()=>{const s=read('assets/journal/runtime.mjs');assert.match(s,/if\(e\.isComposing\)return/);assert.match(s,/compositionend',onSearch/);});
test('public game release remains M07 and templates stay W02',()=>{assert.equal(project.currentRelease.version,'0.4.3');assert.match(project.chapterPlan.starterHref,/W02/);});
