import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {videoURL,rows,readmeBlock,replaceReadme,projectVideos,plan} from '../../scripts/videos/sync.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const c={URL};for(const p of ['assets/ui/site-actions.js','content/site-data.js'])vm.runInNewContext(read(p),c);
const blank=[...rows(c.SITE_DATA)].map(t=>({...t,url:null}));
const url='https://www.bilibili.com/video/BV1g9bx6PEwL/';
test('two exact, distinct video targets retain explicit slots',()=>{assert.equal(rows(c.SITE_DATA).length,2);assert.deepEqual(blank.map(x=>x.key),['episode4','workshop']);});
test('absent URL is pending, never a fabricated URL',()=>{for(const v of [undefined,null,''])assert.equal(videoURL(v),null);});
test('canonical URL is accepted without marking playback verification',()=>assert.equal(videoURL(url),url));
for(const value of ['javascript:alert(1)','https://evil.example/video/BV1g9bx6PEwL/','https://www.bilibili.com@evil.example/video/BV1g9bx6PEwL/','https://www.bilibili.com/video/BV1g9bx6PEwL/?x=1','https://www.bilibili.com/video/undefined/',{},123])test('video schema rejects '+String(value),()=>assert.throws(()=>videoURL(value)));
test('pending panel has readable text but is not an empty player or a fake link',()=>{const h=c.SITE_ACTIONS.videoPanel({id:'x',title:'测试',videoSlot:true});assert.match(h,/视频待发布/);assert.match(h,/data-video-state="pending"/);assert.doesNotMatch(h,/<(?:a|iframe)\b|href=/);});
test('published panel points to the exact video in a safe new tab',()=>{const h=c.SITE_ACTIONS.videoPanel({id:'x',title:'测试',videoSlot:true,videoUrl:url});assert.match(h,/data-video-state="available"/);assert.ok(h.includes('href="'+url+'"'));assert.match(h,/rel="noopener noreferrer"/);assert.doesNotMatch(h,/视频待发布|<iframe/);});
test('video panel escapes titles',()=>assert.doesNotMatch(c.SITE_ACTIONS.videoPanel({id:'x',title:'<img onerror=x>',videoSlot:true}),/<img onerror/));
test('unregistered tools retain their original artwork',()=>assert.equal(c.SITE_ACTIONS.videoPanel({title:'other'}),''));
test('README pending states need no BV placeholder',()=>{const b=readmeBlock(blank);assert.equal((b.match(/视频待发布/g)||[]).length,2);assert.doesNotMatch(b,/BV1|iframe/);});
test('README manages only its delimited block, preserving unrelated text',()=>{const t='# Intro\n\n## Run locally\ncustom content\n';const a=replaceReadme(t,readmeBlock(blank));assert.ok(a.startsWith('# Intro\n\n'));assert.ok(a.endsWith('## Run locally\ncustom content\n'));assert.equal(replaceReadme(a,readmeBlock(blank)),a);});
test('malformed or duplicate README boundaries fail closed',()=>{for(const t of ['<!-- XIAOQ:VIDEOS:START -->','<!-- XIAOQ:VIDEOS:END --><!-- XIAOQ:VIDEOS:START -->',readmeBlock(blank)+readmeBlock(blank)])assert.throws(()=>replaceReadme(t,readmeBlock(blank)));});
test('project video state is derived and does not change source acceptance or historical updates',()=>{const p=JSON.parse(read('content/development/projects/mario-mix.json')),before=structuredClone(p);const n=projectVideos(p,blank.map(t=>({...t,url:t.key==='episode4'?url:null})));assert.deepEqual(p,before);assert.deepEqual(n.currentRelease,p.currentRelease);assert.deepEqual(n.updates,p.updates);assert.equal(n.links.filter(l=>l.href===url).length,1);assert.ok(n.highlights.some(x=>x.includes('地图工坊 视频待发布')));assert.deepEqual(projectVideos(n,blank.map(t=>({...t,url:t.key==='episode4'?url:null}))),n);});
test('README and development documents match the source registry',()=>{for(const[p,b]of plan(root))assert.equal(read(p),b.toString(),p);});
test('both generated targets contain a real pending video box without IDs',()=>{for(const[p,id]of [['games/mario-mix-4/index.html','game-mario-mix-4'],['tools/index.html','mario-map-workshop']]){const h=read(p);assert.ok(h.includes(`data-video-slot="${id}"`));}});
test('fourth episode typography uses covered Latin IV and an explicit missing-glyph face',()=>{const item=c.SITE_DATA.items.find(x=>x.id==='game-mario-mix-4');assert.match(item.title,/ IV /);assert.doesNotMatch(item.title,/Ⅳ/);const css=read('assets/site-brand-tokens.css');assert.match(css,/unicode-range:\s*U\+5C3C/);assert.match(css,/subset-114\.woff2/);});
test('fourth episode authoritative status is released but reference fidelity stays pending',()=>{const d=JSON.parse(read('packages/mario-mix-worlds/content/catalog.json'));const l=d.levels.find(x=>x.id==='1-4');assert.equal(l.status,'released');assert.equal(l.playHref,'/games/mario-mix-4/play.html');assert.equal(l.template.originalReview,'pending');});

 test('homepage shared resources use the same current content hashes as direct entry pages',async()=>{const{versionEntry}=await import('../../scripts/videos/cache.mjs');assert.equal(versionEntry(read('index.html'),root),read('index.html'));});
 test('missing-glyph supplement is inherited by body despite later theme styles',()=>{const s=read('assets/site-brand-tokens.css');assert.match(s,/font-family: "LXGW WenKai Supplement"/);assert.match(s,/html body\{font-family:var\(--font-body\)/);});
