#!/usr/bin/env node
/** Generate game detail bodies, a visitor guide and a genuine 404 document.
 * All markup comes from the same pure module used by the browser shell.
 */
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {readOptional,writeAtomic,safe} from '../lib/safe-path.mjs';
import {equalText,matchesTextHash} from '../lib/text-records.mjs';
import {nativePage} from '../journal/build.mjs';
import {wireHTML} from '../workshop/build.mjs';
export const ROOT=fileURLToPath(new URL('../../',import.meta.url));
export const RECORD='docs/launch-r19/generated-files.json';
const sha=b=>createHash('sha256').update(b).digest('hex');
export async function planLaunch(root,{reader=p=>readOptional(root,p)}={}){
  const get=async p=>{safe(root,p);const b=await reader(p);if(!b)throw Error('缺少构建文件：'+p);return b.toString('utf8');};
  const context=vm.createContext({URL});
  for(const p of ['content/site-data.js','assets/ui/site-actions.js','assets/launch/journey.js'])new vm.Script(await get(p),{filename:p}).runInContext(context,{timeout:1000});
  const data=context.SITE_DATA,journey=context.SITE_JOURNEY,files=new Map(),missingDetails=[],supports={};
  const template=await get('notes/index.html');
  for(const [file,body,title,intro,page] of [
    ['play-guide/index.html',journey.helpPage(),'试玩帮助','体验作品、查看源码，遇到问题也有去处。','visitorHelp'],
    ['404.html',journey.notFound(),'页面未找到','这个地址没有对应的公开页面。','notFound']]) {
    let html=nativePage(template,body,{title,intro,eyebrow:page==='notFound'?'NOT FOUND':'GET STARTED'},file);
    html=html.replace('data-page="notes"',`data-page="${page}"`).replace(/\sdata-journal-page="[^"]*"/,'').replace(' data-journal-slot','').replace(/(data-nav-key="notes")\s+aria-current="page"/g,'$1');
    if(page==='notFound')html=html.replace('</head>','<meta name="robots" content="noindex, follow">\n</head>');
    files.set(file,Buffer.from(html));
  }
  for(const item of data.items||[]){
    if(item.primaryType!=='game'||item.visibility!=='public'||item.lifecycleStatus==='archived')continue;
    if(!/^[a-z0-9][a-z0-9-]*$/.test(item.slug||''))throw Error('游戏 slug 无效');
    const file=`games/${item.slug}/index.html`,source=await reader(file);
    if(!source){missingDetails.push(file);continue;} // Report, never invent an unpublished work.
    let html=source.toString('utf8');
    if((html.match(/<main\b/gi)||[]).length!==1||!/<\/main>/i.test(html))throw Error('游戏介绍页 main 不唯一：'+file);
    const proof=(data.evidence||[]).find(e=>(item.evidenceIds||[]).includes(e.id));
    const main=html.match(/<main\b[\s\S]*?<\/main>/i)[0];
    let support;
    if(main.includes('data-game-journey')){
      const m=main.match(/<section class="section" data-game-support>\s*<div class="shell article">([\s\S]*?)<\/div>\s*<\/section>\s*<\/main>$/);
      if(/\bdata-game-support\b/.test(main)&&(!m||(main.match(/\bdata-game-support\b/g)||[]).length!==1))throw Error('作品说明边界不明确，请人工合并：'+file);
      support=m?m[1]:'';
    }else{
      // Migrate only the recognised original introduction. Preserve all following
      // rights/support content byte-for-byte rather than replacing a custom article.
      const m=main.match(/^<main\b[^>]*><section class="section"><div class="shell article"><img\b[^>]*><h2>开始游玩<\/h2><p>[\s\S]*?<\/p><div class="actions">[\s\S]*?<\/div>(?:<p>下载后解压[^<]*<\/p>)?([\s\S]*)<\/div><\/section><\/main>$/);
      if(!m)throw Error('游戏介绍区不是已识别模板，请人工合并：'+file);
      support=m[1];
    }
    supports[item.slug]=support;
    const next='<main id="main" tabindex="-1">'+journey.gameStart(item,proof)+(support?'<section class="section" data-game-support><div class="shell article">'+support+'</div></section>':'')+'</main>';
    html=html.replace(/<main\b[\s\S]*?<\/main>/i,next);
    const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    html=html.replace(/<title>[\s\S]*?<\/title>/i,'<title>'+e(item.title)+' · 在下_小Q</title>');
    html=html.replace(/(<section class="page-head">[\s\S]*?<h1>)[\s\S]*?(<\/h1>)/,(_,a,b)=>a+e(item.title)+b);
    html=html.replace(/(<meta\b[^>]*(?:property="og:title"|name="twitter:title")[^>]*content=")[^"]*(")/g,(_,a,b)=>a+e(item.title)+b);
    html=html.replace(/data-prerendered="[^"]*"/,'data-prerendered="true"');
    files.set(file,Buffer.from(wireHTML(html)));
  }
  files.set('content/game-support.js',Buffer.from('// Generated by launch:build; edit the game introduction source instead.\nglobalThis.SITE_GAME_SUPPORT = Object.freeze(' + JSON.stringify(supports).replace(/</g,'\\u003c') + ');\n'));
  return {files,missingDetails};
}
export async function build(root=ROOT,{check=false}={}){
  const plan=await planLaunch(root),prior=JSON.parse(readOptional(root,RECORD)||'{"files":{}}');const changes=[];
  for(const [p,b]of plan.files){const before=readOptional(root,p);if(before&&prior.files[p]&&!matchesTextHash(before,prior.files[p]))throw Error('生成文件含手工修改：'+p);if(equalText(before,b))continue;if(before&&!prior.files[p])throw Error('首次迁移须通过R19安装器核对：'+p);changes.push({p,b,before});}
  for(const p of Object.keys(prior.files))if(!plan.files.has(p))throw Error('已有介绍页不再登记，需手动归档：'+p);
  const record=Buffer.from(JSON.stringify({schemaVersion:1,files:Object.fromEntries([...plan.files].map(([p,b])=>[p,sha(b)]))},null,2)+'\n');
  if(!equalText(readOptional(root,RECORD),record))changes.push({p:RECORD,b:record,before:readOptional(root,RECORD)});
  if(check&&changes.length)throw Error('试玩引导未更新，运行 npm run launch:build');
  if(!check){for(const c of changes){const actual=readOptional(root,c.p);if((actual?sha(actual):null)!==(c.before?sha(c.before):null))throw Error('构建期间文件已修改：'+c.p);}for(const c of changes)writeAtomic(root,c.p,c.b);}
  return {changed:changes.length,files:plan.files.size,missingDetails:plan.missingDetails};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))build(ROOT,{check:process.argv.includes('--check')}).then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(e.message);process.exitCode=1;});
