/** Original geometric test-font generator. No production/system font is read,
 * embedded or redistributed. Generated bytes live only in the test document. */
import {deflateSync} from 'node:zlib';
const aligned=n=>(n+3)&~3;
function checksum(bytes){const b=Buffer.alloc(aligned(bytes.length));bytes.copy(b);let n=0;for(let i=0;i<b.length;i+=4)n=(n+b.readUInt32BE(i))>>>0;return n;}
function names(family){
 const strings=[[1,family],[2,'Regular'],[4,family+' Regular'],[6,family.replace(/[^a-zA-Z0-9]/g,'')]];
 const data=strings.map(([,s])=>{const b=Buffer.from(s,'utf16le');b.swap16();return b;});
 const head=Buffer.alloc(6+12*strings.length);head.writeUInt16BE(strings.length,2);head.writeUInt16BE(head.length,4);let offset=0;
 strings.forEach(([id],i)=>{const p=6+i*12;head.writeUInt16BE(3,p);head.writeUInt16BE(1,p+2);head.writeUInt16BE(0x409,p+4);head.writeUInt16BE(id,p+6);head.writeUInt16BE(data[i].length,p+8);head.writeUInt16BE(offset,p+10);offset+=data[i].length;});return Buffer.concat([head,...data]);
}
export function geometricFont(codepoints,{family='QFontFixture'}={}){
 const points=[...new Set(codepoints)].sort((a,b)=>a-b);if(!points.length||points.some(n=>!Number.isInteger(n)||n<32||n>0x10ffff)||points.length>2000)throw Error('Invalid geometric font fixture points');
 const count=points.length+1,t=new Map(),head=Buffer.alloc(54);head.writeUInt32BE(0x10000);head.writeUInt32BE(0x10000,4);head.writeUInt32BE(0x5f0f3cf5,12);head.writeUInt16BE(1000,18);head.writeInt16BE(600,40);head.writeInt16BE(740,42);head.writeUInt16BE(8,46);head.writeInt16BE(2,48);head.writeInt16BE(1,50);t.set('head',head);
 const hhea=Buffer.alloc(36);hhea.writeUInt32BE(0x10000);hhea.writeInt16BE(800,4);hhea.writeInt16BE(-200,6);hhea.writeUInt16BE(700,10);hhea.writeInt16BE(600,16);hhea.writeInt16BE(1,18);hhea.writeUInt16BE(count,34);t.set('hhea',hhea);
 const maxp=Buffer.alloc(32);maxp.writeUInt32BE(0x10000);maxp.writeUInt16BE(count,4);maxp.writeUInt16BE(4,6);maxp.writeUInt16BE(1,8);maxp.writeUInt16BE(2,14);t.set('maxp',maxp);
 const metrics=Buffer.alloc(count*4);for(let i=0;i<count;i++)metrics.writeUInt16BE(700,i*4);t.set('hmtx',metrics);
 const glyph=Buffer.alloc(36);glyph.writeInt16BE(1);glyph.writeInt16BE(60,2);glyph.writeInt16BE(600,6);glyph.writeInt16BE(740,8);glyph.writeUInt16BE(3,10);glyph.fill(1,14,18);[60,540,0,-540].forEach((n,i)=>glyph.writeInt16BE(n,18+i*2));[0,0,740,0].forEach((n,i)=>glyph.writeInt16BE(n,26+i*2));
 const glyphs=[Buffer.alloc(0),...points.map(n=>n===32?Buffer.alloc(0):glyph)],loca=Buffer.alloc((count+1)*4);let offset=0;glyphs.forEach((b,i)=>{loca.writeUInt32BE(offset,i*4);offset+=b.length;});loca.writeUInt32BE(offset,count*4);t.set('glyf',Buffer.concat(glyphs));t.set('loca',loca);
 const cmap=Buffer.alloc(12+16+12*points.length);cmap.writeUInt16BE(1,2);cmap.writeUInt16BE(3,4);cmap.writeUInt16BE(10,6);cmap.writeUInt32BE(12,8);cmap.writeUInt16BE(12,12);cmap.writeUInt32BE(cmap.length-12,16);cmap.writeUInt32BE(points.length,24);points.forEach((n,i)=>{const p=28+12*i;cmap.writeUInt32BE(n,p);cmap.writeUInt32BE(n,p+4);cmap.writeUInt32BE(i+1,p+8);});t.set('cmap',cmap);
 const os2=Buffer.alloc(78);os2.writeInt16BE(700,2);os2.writeUInt16BE(400,4);os2.writeUInt16BE(5,6);os2.write('QFIX',58);os2.writeUInt16BE(64,62);os2.writeUInt16BE(Math.min(points[0],65535),64);os2.writeUInt16BE(Math.min(points.at(-1),65535),66);os2.writeInt16BE(800,68);os2.writeInt16BE(-200,70);os2.writeUInt16BE(800,74);os2.writeUInt16BE(200,76);t.set('OS/2',os2);
 t.set('name',names(family));const post=Buffer.alloc(32);post.writeUInt32BE(0x30000);t.set('post',post);
 const rows=[...t].sort(([a],[b])=>a<b?-1:1).map(([tag,data])=>{const packed=deflateSync(data);return {tag,data,packed:packed.length<data.length?packed:data};});
 const directory=Buffer.alloc(rows.length*20),parts=[];offset=44+directory.length;
 rows.forEach((row,i)=>{const p=i*20;directory.write(row.tag,p,4,'ascii');directory.writeUInt32BE(offset,p+4);directory.writeUInt32BE(row.packed.length,p+8);directory.writeUInt32BE(row.data.length,p+12);directory.writeUInt32BE(checksum(row.data),p+16);const packed=Buffer.alloc(aligned(row.packed.length));row.packed.copy(packed);parts.push(packed);offset+=packed.length;});
 const woff=Buffer.alloc(44);woff.write('wOFF');woff.writeUInt32BE(0x10000,4);woff.writeUInt32BE(offset,8);woff.writeUInt16BE(rows.length,12);woff.writeUInt32BE(12+rows.length*16+rows.reduce((n,r)=>n+aligned(r.data.length),0),16);woff.writeUInt16BE(1,20);
 return Buffer.concat([woff,directory,...parts]);
}
