import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath}from'node:url';
import {planLaunch,build,RECORD}from'../../scripts/launch/build.mjs';
import {review,audit,localReference,REQUIRED}from'../../scripts/launch/check.mjs';
import {shareURL}from'../../assets/launch/runtime.mjs';
import {wireExperience}from'../../scripts/experience/wire.mjs';
const ROOT=fileURLToPath(new URL('../../',import.meta.url));const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const item={id:'visitor-sample',slug:'visitor-sample',title:'验证用作品',primaryType:'game',visibility:'public',localUrl:'games/visitor-sample/play.html',cover:'assets/sample.webp',videoUrl:'https://example.org/demo',downloadUrl:'downloads/sample.zip',evidenceIds:[]};
function context(){const c=vm.createContext({URL});for(const p of ['assets/ui/site-actions.js','assets/launch/journey.js'])vm.runInContext(read(p),c);return c;}
function temporary(t){const r=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'launch-unit-'));t.after(()=>fs.rmSync(r,{recursive:true,force:true}));return r;}
function put(r,p,b){const f=path.join(r,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b);}
function input(r){const m=new Map([['content/site-data.js',Buffer.from('globalThis.SITE_DATA='+JSON.stringify({items:[item],evidence:[]})+';')],['notes/index.html',Buffer.from(read('notes/index.html'))],['assets/ui/site-actions.js',Buffer.from(read('assets/ui/site-actions.js'))],['assets/launch/journey.js',Buffer.from(read('assets/launch/journey.js'))]]);for(const[p,b]of m)put(r,p,b);return m;}
const original=(support='<h2>作品说明</h2><p>维持原作者说明。</p>')=>'<!doctype html><html><head><title>样例</title></head><body><div id="app" data-prerendered="true"><h1>样例</h1><main id="main" tabindex="-1"><section class="section"><div class="shell article"><img src="/assets/sample.webp"><h2>开始游玩</h2><p>简介</p><div class="actions"><a href="/games/visitor-sample/play.html">试玩</a></div><p>下载后解压，用浏览器打开 index.html。</p>'+support+'</div></section></main></div><script src="/assets/site-shell.js"></script><script src="/assets/site-router.js"></script></body></html>';
test('one primary play action precedes the secondary video and download',()=>{const h=context().SITE_JOURNEY.gameStart(item);assert.ok(h.indexOf('开始试玩')<h.indexOf('观看演示'));assert.match(h,/<a[^>]+href="\/games\/visitor-sample\/play.html"/);assert.match(h,/download/);assert.match(h,/data-action="primary"|class="button"/);assert.equal((h.match(/id="q-play-heading"/g)||[]).length,1);});
test('title and proof strings are escaped, not executed',()=>{const h=context().SITE_JOURNEY.gameStart({...item,title:'<img src=x onerror=alert(1)>'},{accessNote:'<script>x</script>'});assert.match(h,/&lt;img/);assert.doesNotMatch(h,/<script>x/);});
test('unsafe action and media schemes do not become links',()=>{const J=context().SITE_JOURNEY;for(const s of ['javascript:alert(1)','data:text/html,x','//evil.test/x','/a/../x','/a/%2e%2e/x','https://a:b@evil.test','https://evil.test/\n'])assert.equal(J.linkURL(s),'');assert.doesNotMatch(J.gameStart({...item,localUrl:'javascript:alert(1)',cover:'data:x'}),/href="javascript:|src="data:/);});
test('missing cover uses an honest usable fallback',()=>{const h=context().SITE_JOURNEY.gameStart({...item,cover:null});assert.doesNotMatch(h,/<img/);assert.match(h,/预览图暂时无法显示/);assert.match(h,/开始试玩/);});
test('help has two entry purposes, readable device limitations and no data reset instruction',()=>{const h=context().SITE_JOURNEY.helpPage();assert.match(h,/先体验作品/);assert.match(h,/看看如何制作/);assert.match(h,/没有触屏按钮时/);assert.match(h,/不要.*删除存档/);assert.doesNotMatch(h,/按你的要求|我已为你|本轮/);});
test('404 uses a native search form and nonredirect recovery links',()=>{const h=context().SITE_JOURNEY.notFound();assert.match(h,/<form[^>]+action="\/search\/"[^>]+method="get"/);assert.match(h,/name="q"/);assert.doesNotMatch(h,/location\.replace|http-equiv="refresh"/);});
test('copy preserves the public work path and excludes tracking/query/hash',()=>{assert.equal(shareURL('https://host.test/games/demo/?q=private&utm_source=x#x'),'https://host.test/games/demo/');assert.throws(()=>shareURL('javascript:alert(1)'));assert.throws(()=>shareURL('https://user:pass@host.test'));});
test('resource wiring is idempotent and precedes body shell execution',()=>{const h=wireExperience(read('notes/index.html'));assert.equal(wireExperience(h),h);for(const marker of ['data-journey-core','data-journey-module','data-journey-support','data-journey-css'])assert.equal((h.match(new RegExp(marker,'g'))||[]).length,1);assert.ok(h.indexOf('data-journey-core')<h.indexOf('</head>'));});
test('guide is an existing-router route, not a seventh navigation item',()=>{const r=read('assets/site-router.js'),s=read('assets/site-shell.js');assert.match(r,/visitorHelp/);assert.match(s,/renderVisitorHelp/);assert.doesNotMatch(s,/data-nav-key="visitorHelp"/);assert.equal((r.match(/document\.startViewTransition\(commit\)/g)||[]).length,1);});
test('no preview media or font bytes are embedded into new JS or CSS',()=>{for(const p of ['assets/launch/journey.js','assets/launch/journey.css','assets/launch/runtime.mjs'])assert.doesNotMatch(read(p),/data:.*base64|@font-face/);});
test('launch plan contains recovery pages but does not invent missing game pages',async t=>{const r=temporary(t);input(r);const p=await planLaunch(r);assert.ok(p.files.has('404.html'));assert.ok(p.files.has('play-guide/index.html'));assert.ok(p.files.has('content/game-support.js'));assert.deepEqual(p.missingDetails,['games/visitor-sample/index.html']);assert.equal(p.files.has('games/visitor-sample/index.html'),false);});
test('game introduction migration retains custom support and copyright byte content',async t=>{const r=temporary(t);input(r);const support='<h2>自定义说明</h2><p data-custom="yes">原有权利人、授权限制和特殊说明。</p>';put(r,'games/visitor-sample/index.html',original(support));const p=await planLaunch(r),h=p.files.get('games/visitor-sample/index.html').toString();assert.ok(h.includes(support));const c=context();vm.runInContext(p.files.get('content/game-support.js').toString(),c);const dynamic=c.SITE_JOURNEY.gameMain(item);assert.ok(dynamic.includes(support));assert.equal(h.match(/<main\b[\s\S]*?<\/main>/)[0],dynamic);});
test('new 404 has noindex and all absolute resources remain safe at arbitrary request depth',async t=>{const r=temporary(t);input(r);const h=(await planLaunch(r)).files.get('404.html').toString();assert.match(h,/noindex, follow/);assert.match(h,/data-page="notFound"/);assert.doesNotMatch(h,/(?:href|src)="\.\.\//);});
test('unknown custom game intro is a merge conflict not blind overwrite',async t=>{const r=temporary(t);input(r);put(r,'games/visitor-sample/index.html','<main><p>自定义</p></main>');await assert.rejects(()=>planLaunch(r),/人工合并/);});
test('registered build is stable and does not change original play bytes',async t=>{const r=temporary(t);input(r);put(r,'games/visitor-sample/index.html',original());put(r,'games/visitor-sample/play.html','DO NOT CHANGE');const p=await planLaunch(r);for(const[f,b]of p.files)put(r,f,b);const {createHash}=await import('node:crypto');put(r,RECORD,JSON.stringify({files:Object.fromEntries([...p.files].map(([p,b])=>[p,createHash('sha256').update(b).digest('hex')]))}));await build(r);assert.equal((await build(r,{check:true})).changed,0);assert.equal(fs.readFileSync(path.join(r,'games/visitor-sample/play.html'),'utf8'),'DO NOT CHANGE');});
test('hand-edited generated helper is refused by builder',async t=>{const r=temporary(t);input(r);await build(r);fs.appendFileSync(path.join(r,'play-guide/index.html'),'<!-- human edit -->');await assert.rejects(()=>build(r),/手工修改/);});
test('local references resolve directory URLs and anchors',()=>{assert.deepEqual(localReference('games/x/index.html','../../notes/#doc'),{path:'notes/index.html',fragment:'doc'});assert.equal(localReference('index.html','https://example.org/'),null);assert.equal(localReference('index.html','mailto:x@y'),null);assert.ok(localReference('index.html','/%00').error);});
function auditFixture(t){const r=temporary(t);put(r,'index.html','<main id="main"><h1>测试</h1><a href="/help/#top">帮助</a></main>');put(r,'help/index.html','<main id="top"><h1>帮助</h1></main>');for(const rec of ['docs/development/generated-pages.json','docs/design-r07/generated-pages.json','docs/experience-r18/generated-files.json',RECORD])put(r,rec,JSON.stringify({files:{'help/index.html':'ledger'}}));return r;}
test('local audit reports a missing target instead of all-clear',t=>{const r=auditFixture(t);fs.appendFileSync(path.join(r,'index.html'),'<a href="/missing/">缺失</a>');assert.ok(audit(r).errors.some(e=>e.problem==='missing-local-reference'));});
test('local audit notices broken anchor and duplicate heading',t=>{const r=auditFixture(t);put(r,'help/index.html','<main><h1>一</h1><h1>二</h1></main>');const a=audit(r);assert.ok(a.errors.some(e=>e.problem==='missing-anchor'));assert.ok(a.errors.some(e=>e.problem==='non-unique-h1'));});
test('audit fingerprint changes when a checked target changes',t=>{const r=auditFixture(t),a=audit(r);assert.equal(a.errors.length,0);fs.appendFileSync(path.join(r,'help/index.html'),'<!-- different -->');assert.notEqual(audit(r).fingerprint,a.fingerprint);assert.equal(a.networkChecked,false);});
test('release evidence is refused by default; does not generate approval',()=>{const a={fingerprint:'x',errors:[]};assert.equal(review(a,null).ready,false);assert.equal(REQUIRED.length,7);});
test('complete synthetic evidence is valid only for exact tested fingerprint',()=>{const a={fingerprint:'test-fixture',errors:[]},e={schemaVersion:1,fingerprint:'test-fixture',checks:Object.fromEntries(REQUIRED.map(id=>[id,{status:'passed',by:'TEST FIXTURE',date:'2026-09-18',evidence:'synthetic test, not real approval'}]))};assert.equal(review(a,e).ready,true);assert.equal(review({...a,fingerprint:'changed'},e).ready,false);assert.equal(review({...a,errors:[{problem:'missing-page',page:'x'}]},e).ready,false);});
test('invalid dates and unnamed approval do not pass',()=>{const a={fingerprint:'x',errors:[]},e={schemaVersion:1,fingerprint:'x',checks:Object.fromEntries(REQUIRED.map(id=>[id,{status:'passed',by:'',date:'2026-99-99',evidence:'test'}]))};assert.equal(review(a,e).ready,false);});

test('visitor help is discoverable in the built search index',()=>{const idx=JSON.parse(read('content/search-index.json'));assert.equal(idx.entries.filter(e=>e.id==='guide:visitor-help').length,1);assert.ok(idx.entries.find(e=>e.id==='guide:visitor-help').tags.includes('声音'));});
