import {test} from 'node:test';import assert from 'node:assert/strict';
import {loadReference} from '../scripts/reference.mjs';import {ROOT} from '../scripts/build.mjs';import {compileWorld} from '../src/compiler.mjs';import {fromTemplate,problems} from '../atlas/editor-model.mjs';import {connectionProblems} from '../atlas/editor-objects.mjs';import {markerParts,terrainParts} from '../atlas/map-appearance.mjs';import {createPlatformStage} from '../atlas/editor-mario-stage.mjs';import {createPlatformMotor} from '../atlas/editor-mario-motor.mjs';
const reference=loadReference(ROOT);
test('all 32 maps retain every area and section inspection view, with bounded complete base terrain',()=>{for(const m of reference.maps){const w=compileWorld(reference,m.name),parts=m.areas.reduce((n,a)=>n+(a.sections||[]).reduce((n,s)=>n+['before','stretch','after'].filter(k=>s[k]).length,0),0);assert.equal(w.rooms.length,m.areas.length+parts);for(const r of w.rooms)for(const q of r.map.geometry){assert.ok(q.x>=0&&q.x+q.w<=r.map.width);assert.ok(q.y>=0&&q.y+q.h<=r.map.height);}}});
test('8-4 base contains the after section and all five rooms; original loops remain recorded',()=>{const before=JSON.stringify(reference),w=compileWorld(reference,'8-4'),base=w.rooms.find(r=>r.roomId==='area-0');assert.equal(base.map.width,1440);assert.ok(base.semantics.some(s=>s.source.transport===2));assert.equal(w.coverage.areas,5);assert.equal(base.assembly.length,1);assert.equal(JSON.stringify(reference),before);const d=fromTemplate(w);assert.deepEqual(connectionProblems(d),[]);assert.ok(d.rooms[0].map.objects.some(o=>o.kind==='portal'&&o.targetRoom==='area-1'));});
test('4-4 and 7-4 default views include their successful path through every section and castle finish',()=>{for(const [id,count] of [['4-4',3],['7-4',7]]){const r=compileWorld(reference,id).rooms[0];assert.equal(r.assembly.length,count);assert.ok(r.markers.some(m=>m.kind==='castle-finish'));assert.ok(r.map.width>1000);}});
test('castle bridge uses one 16px sprite strip, NPC is Toad except final Peach, firebar rotates',()=>{for(const id of ['1-4','2-4','3-4','4-4','5-4','6-4','7-4','8-4']){const w=compileWorld(reference,id);for(const r of w.rooms.filter(r=>r.markers.some(m=>m.kind==='castle-finish'))){const g=r.map.geometry.find(q=>r.semantics.find(s=>s.id===q.id)?.kind==='CastleBridge'||r.semantics.find(s=>s.id===q.id)?.type==='CastleBridge');assert.equal(terrainParts(r,g)[0].h,16);assert.ok(markerParts(r,r.markers.find(m=>m.kind==='castle-finish'))[0].name.includes(id==='8-4'?'Peach':'Toad'));}}const m={kind:'rotating-firebar',x:80,y:176,source:{fireballs:6,speed:1}},a=markerParts({tick:0},m),b=markerParts({tick:28},m);assert.equal(a.length,6);assert.notEqual(a[5].x,b[5].x);});
test('axe retracts bridge before Bowser falls',()=>{
 const r=compileWorld(reference,'1-4').rooms[0],axe=r.markers.find(m=>m.kind==='bridge-axe-finish'),bridge=r.map.geometry.find(g=>r.semantics.find(s=>s.id===g.id)?.type==='CastleBridge');const character={capabilities:['jump'],motion:{width:10,height:14,maxHealth:1}};r.map.objects=[{id:'start',kind:'spawn',x:axe.x,y:axe.y-14,w:10,h:14},{id:'boss',kind:'walker',x:bridge.x+80,y:bridge.y-32,w:32,h:32}];r.enemySkins={boss:'enemy-bowser'};const s=createPlatformStage({plan:{character,stage:{entryRoom:r.roomId,entrySpawn:'start'},rooms:{[r.roomId]:r.map}},visualRooms:[r],motor:createPlatformMotor(),emit(){}});for(let i=0;i<10;i++)s.step();assert.equal(s.view().finish.phase,'bridge');assert.ok(s.view().geometry.find(g=>g.id===bridge.id).w<208);for(let i=0;i<80;i++)s.step();assert.equal(s.view().finish.phase,'boss-fall');assert.ok(!s.view().geometry.some(g=>g.id===bridge.id));assert.ok(s.view().enemies[0].y>bridge.y);
});

test('visible rotating fireballs use the same positions for damage',()=>{
 const room={roomId:'main',map:{width:512,height:240,geometry:[{id:'floor',x:0,y:208,w:512,h:32,collision:'solid'}],objects:[{id:'start',kind:'spawn',x:84,y:180,w:10,h:14}]},markers:[{id:'bar',kind:'rotating-firebar',x:80,y:176,source:{fireballs:6,speed:1}}]},character={capabilities:['jump'],motion:{width:10,height:14,maxHealth:1}},stage=createPlatformStage({plan:{character,stage:{entryRoom:'main',entrySpawn:'start'},rooms:{main:room.map}},visualRooms:[room],motor:createPlatformMotor(),emit(){}});stage.step();assert.equal(stage.view().lives,2);assert.equal(stage.view().p.dying,true);
});
