import fs from 'node:fs';import {test} from 'node:test';import assert from 'node:assert/strict';import {fromTemplate} from '../atlas/editor-model.mjs';import {projectPack} from '../atlas/editor-runtime.mjs';import {createStageCatalog} from '../atlas/runtime/stage-catalog.mjs';import {createPlatformMotor} from '../atlas/editor-mario-motor.mjs';import {createPlatformStage} from '../atlas/editor-mario-stage.mjs';import {billShots} from '../atlas/editor-bill.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));
function fixture(setup=()=>{}){const d=fromTemplate(read('../generated/levels/1-2/template.json'));for(const r of d.rooms)r.playHero='bill';setup(d);const pack=projectPack(d,'area-1',read('../atlas/runtime/character.json')),plan=createStageCatalog(pack).plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true});return createPlatformStage({plan,motor:createPlatformMotor(),visualRooms:d.rooms,emit(){}});}
test('Bill 1-2 holds fire, eight-way aim, and uses tall/crouching body',()=>{const s=fixture();for(let i=0;i<60;i++)s.step({run:true});assert.equal(s.view().p.hero,'bill');assert.equal(s.view().p.h,30);assert.ok(s.view().items.some(x=>x.kind==='bill-shot'));s.step({down:true});assert.equal(s.view().p.h,16);for(let i=0;i<15;i++)s.step({up:true,run:true});assert.ok(s.view().items.some(x=>x.kind==='bill-shot'&&x.vy<0));});
for(const weapon of ['N','M','S','F','L'])test('existing Bill weapon family '+weapon,()=>{const shots=billShots({x:0,y:0,w:10,h:30,aimX:1,aimY:-1,weapon});assert.equal(shots.length,weapon==='S'?5:weapon==='L'?4:1);assert.ok(shots.every(s=>Number.isFinite(s.vx)&&Number.isFinite(s.vy)));});
test('Bill exits 1-2 side pipe without replacing the map',()=>{let target;const s=fixture(d=>{const r=d.rooms.find(r=>r.roomId==='area-1'),p=r.map.objects.find(o=>o.kind==='portal'&&o.h>o.w);assert.ok(p);target=p.targetRoom;Object.assign(r.map.objects.find(o=>o.kind==='spawn'),{x:p.x+2,y:p.y+p.h-14,w:10,h:14});});for(let i=0;i<180;i++){s.step({x:1});if(s.view().roomId===target&&!s.view().transition)break;}assert.equal(s.view().roomId,target);assert.equal(s.view().p.hero,'bill');assert.equal(s.view().p.h,30);assert.equal(s.view().lives,3);});
import {blank,parseProject} from '../atlas/editor-model.mjs';
import {selectHero,heroFor,carryPlayer} from '../atlas/editor-heroes.mjs';
import {buildCampaign} from '../atlas/campaign-build.mjs';
import {advanceBillShot} from '../atlas/editor-bill.mjs';
const character=read('../atlas/runtime/character.json');
function custom(doc,initialState=null){const pack=projectPack(doc,doc.rooms[0].roomId,character),events=[];const s=createPlatformStage({plan:createStageCatalog(pack).plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true}),motor:createPlatformMotor(),visualRooms:doc.rooms,initialState,autoContinue:true,emit:(type,data)=>events.push({type,...data})});return {s,events};}
function arena(){const d=selectHero(blank('Bill test',512,240),'bill'),r=d.rooms[0];Object.assign(r.map.objects[0],{x:32,y:194,w:10,h:14});r.map.geometry=[{id:'floor',x:0,y:208,w:512,h:32,collision:'solid',material:'ground'}];return d;}
test('all 32 reference maps retain geometry, rooms and enemies when selecting Bill and roundtripping',()=>{for(let w=1;w<=8;w++)for(let n=1;n<=4;n++){const d=fromTemplate(read(`../generated/levels/${w}-${n}/template.json`)),before=JSON.stringify(d.rooms.map(r=>r.map));selectHero(d,'bill');const restored=parseProject(JSON.stringify(d));assert.equal(heroFor(restored),'bill');assert.equal(JSON.stringify(restored.rooms.map(r=>r.map)),before);assert.ok(restored.rooms.every(r=>r.playHero==='bill'));selectHero(restored,'mario');assert.ok(restored.rooms.every(r=>r.playHero==='mario'));}});
test('campaign applies Bill to all maps and carries weapon without Mario power growth',async()=>{const levels=await buildCampaign(async p=>read('../atlas/'+p),()=>{},{hero:'bill'});assert.equal(levels.length,32);assert.ok(levels.every(l=>l.rooms.every(r=>r.playHero==='bill')));const {s}=custom(arena(),{hero:'bill',weapon:'S',power:2,lives:9,coins:20,score:3000});assert.equal(s.view().p.weapon,'S');assert.equal(s.view().p.power,0);assert.equal(s.view().p.h,30);assert.equal(carryPlayer(s.view()).hero,'bill');assert.equal(carryPlayer(s.view()).weapon,'S');});
for(const weapon of ['M','S','F','L'])test('shot opens configured '+weapon+' reward; actual jump collects supply',()=>{const d=arena(),r=d.rooms[0];r.map.geometry.push({id:'reward',x:80,y:176,w:16,h:16,collision:'solid',material:'block',reward:'bill-'+weapon});const {s,events}=custom(d);for(let i=0;i<55;i++)s.step({run:true});assert.ok(s.view().items.some(x=>x.kind==='bill-supply'&&x.weapon===weapon));for(let i=0;i<100&&s.view().p.weapon==='N';i++)s.step({x:1,jump:i<35,run:true});assert.equal(s.view().p.weapon,weapon);assert.equal(s.view().score,1000);assert.ok(events.some(e=>e.event==='powerup'));});
test('Bill down+jump drops through one-way platform and lands on solid ground',()=>{const d=arena(),r=d.rooms[0];r.map.geometry.push({id:'platform',x:16,y:144,w:100,h:8,collision:'oneway',material:'platform'});r.map.objects[0].y=130;const {s}=custom(d);for(let i=0;i<5;i++)s.step({});s.step({down:true,jump:true});for(let i=0;i<50;i++)s.step({});assert.equal(s.view().p.y+s.view().p.h,208);assert.equal(s.view().p.h,30);});
test('Bill death/continue resets weapon without moving body up on each revival',()=>{const {s}=custom(arena(),{hero:'bill',weapon:'L'});for(let i=0;i<5;i++)s.step({});const start=s.view().p.y;const d=arena();d.rooms[0].map.objects.push({id:'danger',kind:'hazard',x:30,y:180,w:16,h:28});const t=custom(d).s;for(let i=0;i<3;i++)t.step({});assert.equal(t.view().p.dying,true);assert.equal(t.continueFromCurrent(),true);assert.ok(Math.abs(t.view().p.y-start)<1);assert.equal(t.view().p.weapon,'N');});
test('spread contact size follows existing growing projectile art',()=>{const shot=billShots({x:0,y:0,w:10,h:30,aimX:1,aimY:0,weapon:'S'})[0];for(let i=0;i<32;i++)advanceBillShot(shot);assert.equal(shot.w,8);assert.equal(shot.h,8);});

test('Bill traverses every reference horizontal exit and preserves equipped weapon',()=>{for(let w=1;w<=8;w++)for(let n=1;n<=4;n++){const t=read(`../generated/levels/${w}-${n}/template.json`);for(const rr of t.rooms.filter(r=>!r.origin||r.origin.part==='base'))for(const pipe of (rr.semantics||[]).filter(s=>(s.kind||s.type)==='PipeHorizontal')){const d=selectHero(fromTemplate(t),'bill'),r=d.rooms.find(r=>r.roomId===rr.roomId),g=r.map.geometry.find(g=>g.id===pipe.id),portal=r.map.objects.find(o=>o.kind==='portal'&&Math.abs(o.x-g.x)<32);Object.assign(r.map.objects.find(o=>o.kind==='spawn'),{x:g.x-10,y:g.y+g.h-14,w:10,h:14});const pack=projectPack(d,r.roomId,character),s=createPlatformStage({plan:createStageCatalog(pack).plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true}),motor:createPlatformMotor(),visualRooms:d.rooms,initialState:{hero:'bill',weapon:'S'},emit(){}});let entered=false;for(let i=0;i<200;i++){s.step({x:1});entered||=s.view().transition?.phase==='enter';if(entered&&s.view().roomId===portal.targetRoom&&!s.view().transition)break;}assert.ok(entered,`${w}-${n} ${r.roomId} entered`);assert.equal(s.view().roomId,portal.targetRoom);assert.equal(s.view().transition,null);assert.equal(s.view().p.weapon,'S');assert.equal(s.view().lives,3);}}});

test('Bill castle finish clears firing/aim and reaches reunion with intact walking state',()=>{const d=selectHero(fromTemplate(read('../generated/levels/8-4/template.json')),'bill'),r=d.rooms.find(r=>r.markers.some(m=>m.kind==='castle-finish')&&!r.roomId.includes('section')),axe=r.markers.find(m=>m.kind==='bridge-axe-finish');Object.assign(r.map.objects.find(o=>o.kind==='spawn'),{x:axe.x,y:axe.y,w:10,h:14});const pack=projectPack(d,r.roomId,character),s=createPlatformStage({plan:createStageCatalog(pack).plan(pack.stages[0].id,pack.characters[0].id,{allowDraft:true}),motor:createPlatformMotor(),visualRooms:d.rooms,emit(){}});assert.equal(s.view().enemies.find(e=>/bowser/i.test(e.type)).hp,20);let reunited=false;for(let i=0;i<1200;i++){s.step({down:true,run:true});const v=s.view();if(v.finish?.age>1){assert.equal(v.p.aimY,0);assert.equal(v.p.firing,false);assert.equal(v.items.filter(x=>x.kind==='bill-shot').length,0);}if(v.finish?.phase==='reunion'){reunited=true;break;}}assert.ok(reunited);});
