import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {ROOT,plan,build,hash} from '../scripts/build.mjs';import {loadReference} from '../scripts/reference.mjs';import {compileWorld,extensionFiles} from '../src/compiler.mjs';import {toTiled} from '../src/tiled.mjs';import {createAdaptation,adaptations} from '../scripts/preview.mjs';import {createAtlasServer} from '../scripts/atlas-server.mjs';
const ref=loadReference(ROOT),copy=x=>JSON.parse(JSON.stringify(x));
for(let w=2;w<=8;w++)for(let l=1;l<=4;l++)test(`${w}-${l}: real source records, bounded geometry, immutable deterministic template`,()=>{
 const id=`${w}-${l}`,src=JSON.stringify(ref),a=compileWorld(ref,id),b=compileWorld(ref,id);assert.deepEqual(a,b);assert.equal(JSON.stringify(ref),src);assert.ok(a.coverage.placementRecords>=25,id);assert.ok(a.coverage.geometry>=15,id);assert.equal(a.coverage.geometryReview,'reference-transcribed-pending-original-review');
 for(const r of a.rooms){const ids=new Set();for(const g of [...r.map.geometry,...r.map.objects]){assert.ok(!ids.has(g.id),g.id);ids.add(g.id);assert.ok([g.x,g.y,g.w,g.h].every(Number.isFinite));assert.ok(g.x>=0&&g.y>=0&&g.x+g.w<=r.map.width&&g.y+g.h<=240);}assert.ok(r.sourceRecordCount>0);}
});
test('32 templates / 63 source areas / 33 section parts, not repeated generic maps',()=>{const {worlds}=plan();assert.equal(worlds.length,32);assert.equal(worlds.reduce((n,w)=>n+w.coverage.areas,0),63);assert.equal(worlds.reduce((n,w)=>n+(w.coverage.sectionViews||0),0),33);const hashes=worlds.slice(4).map(w=>hash(JSON.stringify(w.rooms.map(r=>({g:r.map.geometry,m:r.markers})))));assert.equal(new Set(hashes).size,28);});
test('2-1 begins with the 736-unit floor and has sky + underground areas',()=>{const w=compileWorld(ref,'2-1');assert.equal(w.rooms.length,3);assert.ok(w.maps[0].geometry.some(g=>g.x===0&&g.y===208&&g.w===1472));assert.ok(w.rooms.some(r=>r.setting==='Sky'));assert.ok(w.topology.links.some(l=>l.kind==='vine'));});
test('water rooms do not silently use platform-v1 swimming',()=>{let n=0;for(const w of plan().worlds.slice(4)){for(const r of w.rooms.filter(r=>r.underwater)){n++;assert.ok(!r.previewSupported);assert.ok(!w.inspectionStages.some(s=>s.rooms[r.roomId]));assert.ok(!extensionFiles(w).has(`content/extensions/maps/${r.map.id}/map.json`));assert.ok(w.coverage.pending.includes('underwater-physics'));}}assert.equal(n,5);});
test('4-4 keeps all section parts and conditional pass/fail destinations',()=>{const w=compileWorld(ref,'4-4');assert.equal(w.rooms.length,8);assert.equal(w.topology.areas[0].sections.length,3);assert.ok(w.topology.links.some(l=>l.kind==='SectionDecider'&&l.target.fail===0));assert.ok(w.rooms.some(r=>r.origin.part==='stretch'));});
test('7-4 keeps 18 parts of seven sections, not a flattened fixed map',()=>{const w=compileWorld(ref,'7-4');assert.equal(w.coverage.sectionViews,18);assert.equal(w.topology.areas[0].sections.length,7);assert.ok(w.topology.links.some(l=>l.kind==='SectionDecider'&&l.target.fail===3));});
test('8-4 retains five areas, recursive pipes and infinity height records',()=>{const w=compileWorld(ref,'8-4');assert.equal(w.coverage.areas,5);assert.equal(w.coverage.sectionViews,8);assert.ok(JSON.stringify(w.topology).includes('Infinity'));assert.ok(w.topology.links.some(l=>l.kind==='location'&&l.target===1));assert.ok(w.rooms.find(r=>r.roomId==='area-3').underwater);});
test('bridges have original end posts, not a solid rectangle over the water',()=>{const w=compileWorld(ref,'2-3');assert.ok(w.maps[0].geometry.some(g=>g.x===240&&g.y===160&&g.w===256&&g.h===8));assert.ok(w.maps[0].geometry.some(g=>g.x===496&&g.y===160&&g.h===80));});
test('scale initial platform positions are explicit and remain unimplemented mechanics',()=>{const w=compileWorld(ref,'4-3');assert.ok(w.coverage.pending.includes('coupled-scale'));assert.ok(w.maps[0].geometry.some(g=>g.x===(396-12)*2&&g.y===208-(86-24)*2&&g.w===48));});
test('negative Fill vertical spacing is preserved for 7-2 coins',()=>{const w=compileWorld(ref,'7-2'),m=w.maps[1];assert.ok(m.objects.some(o=>o.kind==='coin'&&o.x===2562&&o.y===144));assert.ok(m.objects.some(o=>o.kind==='coin'&&o.x===2562&&o.y===192));});
test('source anomalies are retained for review, not silently corrected',()=>{const a=compileWorld(ref,'6-2');assert.ok(a.maps.some(m=>m.geometry.some(g=>g.x===2440)));const b=compileWorld(ref,'7-2');assert.ok(b.topology.issues.some(i=>i.field==='yum'));const c=compileWorld(ref,'8-2');assert.ok(c.coverage.pending.includes('source-ceiling-width-review'));});
test('unknown macros and object types fail, malformed Fill is bounded',()=>{for(const q of [{macro:'Unknown'},{thing:'Unknown'},{macro:'Fill',thing:'Stone',xnum:999999}]){const x=copy(ref);x.maps.find(m=>m.name==='2-1').areas[0].creation.push(q);assert.throws(()=>compileWorld(x,'2-1'));}});
test('all 96 Tiled object exports have unique layer and object IDs',()=>{let n=0;for(const w of plan().worlds)for(const r of w.rooms){const t=toTiled(r),ids=t.layers.flatMap(l=>l.objects.map(o=>o.id));assert.equal(t.type,'map');assert.equal(new Set(ids).size,ids.length);assert.ok(t.nextobjectid>Math.max(...ids));n++;}assert.equal(n,96);});
test('32 single-map and eight world archives are generated and inspectable',()=>{const {out}=plan();for(let w=1;w<=8;w++){assert.ok(out.get(`generated/downloads/MarioMix_World_${w}_W02.zip`).length>1000);for(let s=1;s<=4;s++)assert.ok(out.get(`generated/downloads/MarioMix_Map_${w}-${s}_W02.zip`).length>2000);}});
test('new draft can select an 8-4 section without modifying reference data',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'w02-draft-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const d of ['reference','content'])fs.cpSync(path.join(ROOT,d),path.join(root,d),{recursive:true});fs.copyFileSync(path.join(ROOT,'NOTICE.md'),path.join(root,'NOTICE.md'));const before=fs.readFileSync(path.join(root,'reference/worlds/world-8.json'));const a=createAdaptation(root,{base:'8-4',room:'area-1-section-0-before',id:'castle-study',title:'城堡方案',apply:true});assert.equal(a.value.room,'area-1-section-0-before');assert.equal(adaptations(root).length,1);assert.ok(before.equals(fs.readFileSync(path.join(root,'reference/worlds/world-8.json'))));assert.throws(()=>createAdaptation(root,{base:'8-4',room:'area-3',id:'water-study',title:'水下'}),/水下/);});
test('atlas serves actual HTTP JSON / SVG, refuses traversal and nonpublic sources',async t=>{const s=createAtlasServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>s.close());const base='http://127.0.0.1:'+s.address().port;
 const idx=await (await fetch(base+'/generated/atlas-index.json')).json();assert.equal(idx.levels.length,32);assert.equal((await fetch(base+'/generated/levels/8-4/area-3.svg')).status,200);assert.equal((await fetch(base+'/reference/worlds/world-8.json')).status,400);assert.equal((await fetch(base+'/atlas/%2e%2e%2f%2e%2e%2fetc/passwd')).status,400);assert.equal((await fetch(base+'/atlas/index.html',{method:'POST'})).status,405);
});
