"""M07 complete candidate DOM checks. Offline set_content, not a native HTTP/device certification."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,hashlib
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'.local/player-browser'
def main():
 OUT.mkdir(parents=True,exist_ok=True);checks=[];errors=[]
 def check(name,value):
  checks.append({'name':name,'pass':bool(value)})
  if not value:raise AssertionError(name)
 with sync_playwright() as p:
  b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
  page=b.new_page(viewport={'width':1440,'height':960},device_scale_factor=1.5)
  page.on('pageerror',lambda e:errors.append(e.stack));page.route('http://**/*',lambda r:r.abort());page.route('https://**/*',lambda r:r.abort())
  html=(ROOT/'dist/MarioMix_Terraria_M07.html').read_text().replace('<html lang="zh-CN">','<html lang="zh-CN" data-test="1">')
  page.set_content(html,wait_until='domcontentloaded',timeout=25000);page.wait_for_function('()=>!!window.__terraPlayerUiTest');page.wait_for_timeout(350)
  mode=lambda:page.evaluate('window.__test.state().mode')
  sync=lambda:page.evaluate('window.__terraPlayerUiTest.refresh()')
  check('Starts on a visible character selection, not forced tutorial',page.locator('#heroPicker').is_visible() and not page.locator('dialog[open]').count())
  check('Six inherited characters remain present',page.locator('#heroPicker button[data-hero]').count()==6)
  check('Background controls inert during menu',page.locator('.app>header').evaluate('(e)=>e.inert'))
  for hero,chapter in [('mario','1-1'),('bill','1-1'),('megaman','1-1'),('ryu','1-2'),('tank','1-2'),('sandboxTrio','1-3')]:
   page.locator(f'#heroPicker button[data-hero="{hero}"]').click();sync();check('Actual menu chapter '+hero,chapter in page.locator('#mainAction').inner_text())
  page.screenshot(path=str(OUT/'M07-Menu-Desktop.png'),full_page=False)
  page.locator('#m07MenuOptions').click();check('Settings work before starting',page.locator('#m07Options').evaluate('(e)=>e.open'))
  page.locator('#m05Pref-text').click();check('Large text preference applied',page.locator('body').get_attribute('data-terra-text')=='large')
  page.locator('#m05Pref-text').click();page.locator('#m07OptionsClose').click();sync();check('Closing start-screen settings does not start game',page.locator('#heroPicker').is_visible())
  page.locator('#m07MenuHelp').click();check('Help starts at named title',page.evaluate('document.activeElement.id')=='m06HelpTitle')
  check('Actor-specific help has six groups',page.locator('.m06-help-card').count()==6)
  page.keyboard.press('Escape');sync()
  page.locator('#mainAction').click();page.wait_for_timeout(150);sync();page.evaluate('window.__trioTest.step(1,{})');sync()
  check('Starting uses real Terraria runtime',page.evaluate('window.__trioTest.state().mode')=='playing')
  check('Desktop HUD uses display pixels, not 256px source',page.evaluate('window.__terraHudSurfaceTest.snapshot().width')>700)
  check('Original desktop tool hit area remains visible',page.locator('#t15HudHits button[data-t15-tool="1"]').is_visible())
  page.locator('#t15HudHits button[data-t15-tool="1"]').click();sync();check('Real desktop hit region selects platform',page.evaluate('window.__trioTest.state().tool')==1)
  page.locator('#t15HudHits button[data-t15-tool="0"]').click();sync()
  page.screenshot(path=str(OUT/'M07-Game-Desktop.png'),full_page=True)
  before=page.evaluate('window.__trioTest.state().p')
  page.locator('#m07OptionsButton').click();sync();check('Opening options pauses current challenge',page.evaluate('window.__trioTest.state().mode')=='paused')
  page.locator('#m05Pref-contrast').click();page.screenshot(path=str(OUT/'M07-Settings-Desktop.png'),full_page=False)
  page.locator('#m05Pref-contrast').click();page.locator('#m07OptionsClose').click();sync()
  check('Options resume only own pause',page.evaluate('window.__trioTest.state().mode')=='playing')
  check('UI clicks did not move player',before==page.evaluate('window.__trioTest.state().p'))
  page.locator('#t21BindingButton').click();sync();check('Interaction row is no longer missing',page.locator('#t21BindRows button[data-binding="interact"]').count()==2)
  page.locator('#t21BindRows button[data-binding="jump"][data-source="keys"]').click();page.keyboard.press('u');sync()
  check('Keyboard binding changes through real model',page.evaluate('window.__terraSettingsTest.config().actions.jump.keys[0]')=='KeyU')
  page.locator('#t21BindReset').click();check('Reset bindings requires confirmation',page.locator('#m07Confirm').evaluate('(e)=>e.open'))
  check('Destructive action initially focuses Cancel',page.evaluate('document.activeElement.id')=='m07ConfirmCancel')
  page.locator('#m07ConfirmCancel').click();check('Cancel preserves custom mapping',page.evaluate('window.__terraSettingsTest.config().actions.jump.keys[0]')=='KeyU')
  page.screenshot(path=str(OUT/'M07-Bindings-Desktop.png'),full_page=False)
  page.locator('#t21BindClose').click();sync();page.locator('#m06HelpButton').click()
  check('Help reflects current U mapping', 'U' in page.locator('.m06-help-card').nth(1).inner_text())
  page.keyboard.press('Tab');check('Tab reaches visible item inside help',page.evaluate('!!document.activeElement.closest("#m06Help")'))
  page.screenshot(path=str(OUT/'M07-Help-Desktop.png'),full_page=False);page.keyboard.press('Escape');sync()
  page.locator('#restartButton').click();sync();check('Restart is a confirmation, not immediate reset',page.locator('#m07Confirm').evaluate('(e)=>e.open'))
  page.keyboard.press('Escape');sync();check('Cancel restart returns playing',page.evaluate('window.__trioTest.state().mode')=='playing')
  check('Cancel restart preserves position',before==page.evaluate('window.__trioTest.state().p'))
  page.locator('#pauseButton').click();sync();check('Pause exposes clear main action',page.locator('#mainAction').inner_text()=='继续游戏')
  page.locator('#m07MenuOptions').click();page.locator('#m07OptionsClose').click();sync();check('Manually paused game stays paused after settings',page.evaluate('window.__trioTest.state().mode')=='paused')
  page.locator('#mainAction').click();sync()
  page.evaluate('window.__terraPlayerUiTest.pickup({name:"星怒",effect:"召唤星星攻击敌人。长文字保持正常字形换行，不压扁。",age:30})');sync()
  check('Pickup uses outside-world, selectable text',page.locator('#m07Pickup').is_visible())
  page.locator('#m07Recent summary').click()
  check('Pickup is also available in history','星怒' in page.locator('#m07Recent').inner_text())
  for w,h in [(320,844),(390,844),(768,1024),(844,390),(1440,960)]:
   page.set_viewport_size({'width':w,'height':h});page.evaluate('window.__trioTest.step(0,{})');sync();page.wait_for_timeout(80)
   check('No horizontal page overflow '+str(w),page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
   ratio=page.locator('#game').evaluate('e=>e.getBoundingClientRect().width/e.getBoundingClientRect().height')
   check('World aspect unchanged '+str(w),abs(ratio-16/15)<.02)
   if w<=390:
    check('Narrow screen uses reflowed readable HUD '+str(w),page.locator('#m07CompactHud').is_visible())
    check('Compact HUD min14px values '+str(w),float(page.locator('.m07-hud-stats span').first.evaluate('e=>getComputedStyle(e).fontSize').removesuffix('px'))>=14)
    page.locator('.m07-compact-slots button[data-tool="1"]').click();sync();check('Compact tool hit selects original model '+str(w),page.evaluate('window.__trioTest.state().tool')==1)
    page.locator('.m07-compact-slots button[data-tool="0"]').click();sync()
    page.screenshot(path=str(OUT/f'M07-Game-{w}.png'),full_page=True)
   page.locator('#t21BindingButton').click();sync();rect=page.locator('#t21Bindings').bounding_box();check('Bindings fit viewport '+str(w),rect['x']>=0 and rect['x']+rect['width']<=w+1 and rect['y']>=0)
   page.locator('#t21BindClose').click();sync()
  # Pad input supplied only for button-edge logic, not evidence of a physical device.
  page.locator('#m07OptionsButton').click();page.evaluate('''()=>{window.__m07Pad={connected:true,axes:[0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.__m07Pad]});window.__terraPlayerUiTest.pollPad();window.__m07Pad.buttons[13].pressed=true;window.__terraPlayerUiTest.pollPad();}''')
  check('Synthetic pad can navigate open options',page.evaluate('!!document.activeElement.closest("#m07Options")'))
  page.evaluate('window.__m07Pad.buttons[13].pressed=false;window.__terraPlayerUiTest.pollPad();window.__m07Pad.buttons[1].pressed=true;window.__terraPlayerUiTest.pollPad()');sync();check('Synthetic pad cancel closes options',not page.locator('#m07Options').evaluate('(e)=>e.open'))
  page.evaluate('Object.defineProperty(navigator,"getGamepads",{configurable:true,value:()=>[]})')
  page.locator('#charactersButton').click();page.locator('#m07ConfirmAccept').click();sync()
  page.locator('#heroPicker button[data-hero="megaman"]').click();sync();page.locator('#m07MenuHelp').click()
  check('Megaman guide teaches charge and release','蓄力' in page.locator('.m06-help-card').nth(2).inner_text())
  check('Non-Terraria help excludes underground Terra prompts','眼球' not in page.locator('#m06Help').inner_text())
  page.locator('#m06HelpClose').click();sync();page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(OUT/'M07-Menu-Mobile.png'),full_page=False)
  page.locator('#heroPicker button[data-hero="sandboxTrio"]').click();sync();page.locator('#mainAction').click();sync()
  page.locator('#m07OptionsButton').click();page.evaluate("window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))");sync();check('Cached page suspension closes modal but does not resume',not page.locator('#m07Options').evaluate('(e)=>e.open') and page.evaluate('window.__trioTest.state().mode')=='paused')
  page.locator('#m07MenuOptions').click();check('Cached page retains UI listeners',page.locator('#m07Options').evaluate('(e)=>e.open'));page.locator('#m07OptionsClose').click();sync()
  page.close();check('No uncaught runtime or teardown errors',len(errors)==0);b.close()
 report={'result':'pass','count':len(checks),'checks':checks,'pageErrors':errors,'mode':'offline complete candidate, native DOM; explicit injected gamepad and persisted page events; no physical device or natural full playthrough','candidateSha256':hashlib.sha256((ROOT/'dist/MarioMix_Terraria_M07.html').read_bytes()).hexdigest()};(OUT/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
