#!/usr/bin/env node
/** Deterministic small ZIP writer (deflate, CRC32, UTF-8); no external dependency. */
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{deflateRawSync}from'node:zlib';
import{ROOT,hash}from'./build.mjs';import{safe,readOptional,writeAtomic}from'./lib/safe-path.mjs';
const table=Uint32Array.from({length:256},(_,n)=>{for(let j=0;j<8;j++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(b){let c=0xffffffff;for(const x of b)c=table[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
export function zip(entries){const locals=[],central=[];let offset=0;const names=new Set();for(const [name,data]of entries){if(names.has(name)||name.startsWith('/')||name.includes('\\')||name.split('/').some(x=>x==='..'))throw Error('Unsafe ZIP entry');names.add(name);const n=Buffer.from(name),c=deflateRawSync(data,{level:9}),crc=crc32(data),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(8,8);h.writeUInt16LE(0x5d30,12);h.writeUInt32LE(crc,14);h.writeUInt32LE(c.length,18);h.writeUInt32LE(data.length,22);h.writeUInt16LE(n.length,26);locals.push(h,n,c);const d=Buffer.alloc(46);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt16LE(0x800,8);d.writeUInt16LE(8,10);d.writeUInt16LE(0x5d30,14);d.writeUInt32LE(crc,16);d.writeUInt32LE(c.length,20);d.writeUInt32LE(data.length,24);d.writeUInt16LE(n.length,28);d.writeUInt32LE(offset,42);central.push(d,n);offset+=30+n.length+c.length;}
 if(entries.length>65535)throw Error('ZIP64 is not supported');const size=central.reduce((n,b)=>n+b.length,0),e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(entries.length,8);e.writeUInt16LE(entries.length,10);e.writeUInt32LE(size,12);e.writeUInt32LE(offset,16);return Buffer.concat([...locals,...central,e]);}
export function sourceEntries(root=ROOT){const out=[];function walk(dir=''){for(const ent of fs.readdirSync(dir?safe(root,dir):path.dirname(safe(root,'package.json')),{withFileTypes:true})){const rel=dir?dir+'/'+ent.name:ent.name;if(['dist','.local','.git','node_modules','SOURCE_SHA256SUMS.txt'].includes(ent.name))continue;const p=safe(root,rel);if(ent.isSymbolicLink())throw Error('Source links prohibited');if(ent.isDirectory()){walk(rel);}else if(ent.isFile()){if(/\.(ttf|otf|woff2?|eot)$/i.test(rel)||ent.name.startsWith('.env'))throw Error('Prohibited source archive entry: '+rel);out.push([rel,readOptional(root,rel)]);}}}walk();return out.sort((a,b)=>a[0].localeCompare(b[0],'en'));}
export function pack(root=ROOT){const entries=sourceEntries(root),sums=entries.map(([p,b])=>hash(b)+'  '+p).join('\n')+'\n';entries.push(['SOURCE_SHA256SUMS.txt',Buffer.from(sums)]);const release=JSON.parse(readOptional(root,'release.json'));if(!/^M[0-9]{2}$/.test(release.edition))throw Error('Invalid edition');const bytes=zip(entries.map(([p,b])=>['MarioMix_Terraria_'+release.edition+'/'+p,b]));const archive=release.sourceArchive;if(!/^MarioMix_Terraria_M[0-9]{2}(?:_R[0-9]+)?_Source\.zip$/.test(archive))throw Error('Invalid source archive name');writeAtomic(root,'.local/'+archive,bytes);return {path:'.local/'+archive,files:entries.length,bytes:bytes.length,sha256:hash(bytes)};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{console.log(JSON.stringify(pack(),null,2));}catch(e){console.error(e.message);process.exitCode=1;}}
