export function createGuestbookClient({baseUrl,fetchImpl=fetch,storage=localStorage,random=crypto}) {
 const base=new URL(baseUrl);if(base.protocol!=='https:'||base.origin!=='https://xiaoq-guestbook.hfutqdm.chatgpt.site')throw Error('CONFIG_INVALID');
 const key='xiaoq-guestbook-sites-owner-v1';
 function readIdentity(){let token;try{token=storage.getItem(key);if(!/^[a-f0-9]{64}$/.test(token||'')){const bytes=random.getRandomValues(new Uint8Array(32));token=[...bytes].map(v=>v.toString(16).padStart(2,'0')).join('');storage.setItem(key,token);token=storage.getItem(key);}if(!/^[a-f0-9]{64}$/.test(token||''))throw Error();}catch{throw Error('STORAGE_UNAVAILABLE');}return token;}
 async function identity(){return globalThis.navigator?.locks?globalThis.navigator.locks.request(key,readIdentity):readIdentity();}
 async function request(action,method='GET',data=null,own=false,before=null){const url=new URL(`/api/guestbook/${action}`,base);if(before)url.searchParams.set('before',before);const response=await fetchImpl(url,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(own?{'X-Guestbook-Owner':await identity()}: {})},...(data?{body:JSON.stringify(data)}:{}),credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(15000),redirect:'error'});let result;try{result=await response.json();}catch{throw Error('SERVICE_UNAVAILABLE');}if(!response.ok)throw Error(result.message||`REQUEST_FAILED_${response.status}`);return result;}
 async function page(action,before){const result=await request(action,'GET',null,action==='mine',before);if(!Array.isArray(result.rows)||result.rows.length>100)throw Error('INVALID_RESPONSE');for(const row of result.rows){if(!/^[1-9]\d*$/.test(row.id)||typeof row.body!=='string'||[...row.body].length>500||typeof row.nickname!=='string'||!/^#[a-f\d]{6}$/i.test(row.color)||!['square','round','heart','ticket'].includes(row.shape)||!Number.isInteger(row.x)||!Number.isInteger(row.y)||Math.abs(row.x)>1000000||Math.abs(row.y)>1000000||!Number.isFinite(Date.parse(row.created_at))||row.layout_version!==1||!Number.isInteger(row.width)||!Number.isInteger(row.height)||row.width<260||row.width>900||row.height<200||row.height>900)throw Error('INVALID_RESPONSE');}return result;}
 return {list:before=>page('list',before),wall:before=>page('wall',before),mine:before=>page('mine',before),submit:note=>{note.requestId??=random.randomUUID();return request('submit','POST',{...note,x:Math.round(note.x),y:Math.round(note.y)},true);},edit:(id,revision,note)=>request('edit','POST',{...note,id:String(id),revision},true),move:(id,x,y)=>request('move','POST',{id:String(id),x:Math.round(x),y:Math.round(y)},true),remove:id=>request('delete','POST',{id:String(id)},true)};
}
