import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {checkArchitecture,buildModuleDocs,ROOT} from '../scripts/architecture.mjs';
import {validateTasks,loadTasks,taskPlan} from '../scripts/collaboration.mjs';
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
function fixture(t){const r=fs.mkdtempSync(path.join(os.tmpdir(),'terra-arch-'));t.after(()=>fs.rmSync(r,{recursive:true,force:true}));for(const p of ['architecture','src','tests','build.config.json','docs','scripts'])fs.cpSync(path.join(ROOT,p),path.join(r,p),{recursive:true});return r;}
function patch(root,p,fn){const f=path.join(root,p),v=JSON.parse(fs.readFileSync(f));fn(v);fs.writeFileSync(f,JSON.stringify(v));}
test('Every registered runtime module has a real hook, layer, tests and entry contract',()=>{const r=checkArchitecture();assert.equal(r.modules,32);assert.equal(r.bridgeFiles,6);assert.equal(r.compatibilityFragments,33);assert.equal(r.trackedWrapperAssignments,41);});
test('New source module cannot bypass registration',t=>{const r=fixture(t);fs.writeFileSync(path.join(r,'src/input/unregistered.mjs'),'export function x(){}');assert.throws(()=>checkArchitecture(r),/Unregistered/);});
test('Missing test ownership is rejected',t=>{const r=fixture(t);patch(r,'architecture/modules.json',d=>d.modules[0].tests=[]);assert.throws(()=>checkArchitecture(r),/no tests/);});
test('Gameplay modules cannot acquire a browser-global dependency',t=>{const r=fixture(t);fs.appendFileSync(path.join(r,'src/simulation/eye-boss.mjs'),'\nwindow.bad=1;');assert.throws(()=>checkArchitecture(r),/Forbidden host/);});
test('Unknown or cyclic declared module dependencies are rejected',t=>{const r=fixture(t);patch(r,'architecture/modules.json',d=>d.modules[0].dependsOn=['missing']);assert.throws(()=>checkArchitecture(r),/Unknown dependency/);patch(r,'architecture/modules.json',d=>d.modules[0].dependsOn=[d.modules[0].id]);assert.throws(()=>checkArchitecture(r),/cycle/);});
test('Inner layers cannot depend on UI',t=>{const r=fixture(t);patch(r,'architecture/modules.json',d=>d.modules[0].dependsOn=['bindings-view']);assert.throws(()=>checkArchitecture(r),/depends on UI/);});
test('Golden fixtures and wrapper budgets cannot silently grow',t=>{const r=fixture(t);fs.appendFileSync(path.join(r,'src/bridges/bindings.bridge.js'),'\nfixedUpdate=function(){};');assert.throws(()=>checkArchitecture(r),/wrapper budget/);fs.writeFileSync(path.join(r,'src/bridges/bindings.bridge.js'),fs.readFileSync(path.join(ROOT,'src/bridges/bindings.bridge.js')));fs.appendFileSync(path.join(r,'tests/golden/clock.txt'),'\n');assert.throws(()=>checkArchitecture(r),/Golden reference/);});
test('False runtime wiring declarations cannot pass the gate',t=>{const r=fixture(t);patch(r,'architecture/modules.json',d=>d.modules[0].entryHook='clock');assert.throws(()=>checkArchitecture(r),/not wired/);});
test('Generated module documentation is deterministic and protects hand edits',t=>{const r=fixture(t);assert.equal(buildModuleDocs(r,{check:true}).changed,false);assert.equal(buildModuleDocs(r).changed,false);fs.appendFileSync(path.join(r,'docs/generated/MODULES.md'),'manual');assert.throws(()=>buildModuleDocs(r),/edited/);});
test('Tasks have file scope, acceptance, owner state, and no fake external links',()=>{const d=loadTasks();assert.equal(d.tasks.length,20);for(const t of d.tasks){assert.equal(t.issue,null);assert.equal(t.pullRequest,null);}assert.match(taskPlan(d,'M02-LABELS'),/不会认领/);assert.throws(()=>taskPlan(d,'FAKE'));});
test('Task claims without evidence, duplicate IDs and dependency cycles fail',()=>{const d=read('docs/TASKS.json');d.tasks[0].evidence=null;assert.throws(()=>validateTasks(d),/evidence/);const e=read('docs/TASKS.json');e.tasks[0].dependsOn=[e.tasks[0].id];assert.throws(()=>validateTasks(e),/cycle/);e.tasks[1].id=e.tasks[0].id;assert.throws(()=>validateTasks(e),/Duplicate/);});
test('Missing task scope or non-GitHub fabricated reference is rejected',()=>{const d=read('docs/TASKS.json');d.tasks[0].scope=['src/missing.mjs'];assert.throws(()=>validateTasks(d),/scope missing/);const e=read('docs/TASKS.json');e.tasks[0].issue='https://example.invalid/1';assert.throws(()=>validateTasks(e),/Issue\/PR/);});
