import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';
import{build,inspect,ROOT,hash}from'../scripts/build.mjs';import{safe,writeAtomic}from'../scripts/lib/safe-path.mjs';import{createServer}from'../scripts/serve.mjs';
function temp(t){const d=fs.mkdtempSync(path.join(os.tmpdir(),'terra-test-'));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));return d;}
const copy=(t)=>{const d=temp(t);for(const n of ['src','assets','content','tests/golden','build.config.json','release.json','baseline.json','upstream'])fs.cpSync(path.join(ROOT,n),path.join(d,n),{recursive:true});return d;};
test('Reference byte hash matches the actual uploaded ZIP HTML',()=>{const r=inspect(ROOT).report;assert.equal(r.referenceSha256,'e134fdee21a6dce43585cda93c582ca2c0bf45f325f14cde81e33b80b758f19c');assert.equal(r.referenceMatchesUpload,true);});
test('Resource byte checks cover all stored media',()=>{const r=inspect(ROOT).report;assert.equal(r.embeddedMedia,195);assert.equal(r.audioEntries,46);assert.equal(r.independentModules,32);});
test('Web module bundle and single HTML have no unresolved tokens',()=>{const r=inspect(ROOT);for(const [p,b]of r.output)if(/\.(html|mjs|js)$/.test(p))assert(!/@@TERRA_|__TERRA_ASSET_media/.test(b.toString()),p);assert(r.output.get('dist/play.html').toString().includes('type="module"'));});
test('Rebuilds are byte-stable and source files remain unchanged',t=>{const d=copy(t),before=hash(fs.readFileSync(path.join(d,'src/compat/30-terra-foundation.js.part')));build(d,{verifyBaseline:true});assert.equal(build(d).changed,0);assert.equal(build(d,{check:true}).changed,0);assert.equal(hash(fs.readFileSync(path.join(d,'src/compat/30-terra-foundation.js.part'))),before);});
test('Modified generated output is not overwritten',t=>{const d=copy(t);build(d);fs.appendFileSync(path.join(d,'dist/play.html'),'<!-- manual -->');assert.throws(()=>build(d),/edited/);});
test('Tampered embedded media is rejected',t=>{const d=copy(t),r=JSON.parse(fs.readFileSync(path.join(d,'content/resources.json')));fs.appendFileSync(path.join(d,Object.values(r.embedded)[0].path),'bad');assert.throws(()=>inspect(d),/integrity/);});
test('Duplicate module registration rejected',t=>{const d=copy(t),f=path.join(d,'build.config.json'),c=JSON.parse(fs.readFileSync(f));c.modules.push(c.modules[0]);fs.writeFileSync(f,JSON.stringify(c));assert.throws(()=>inspect(d),/Duplicate/);});
test('Golden changes cannot silently become the official baseline',t=>{const d=copy(t);fs.appendFileSync(path.join(d,'tests/golden/bindings-controller.txt'),'\n');assert.throws(()=>build(d,{verifyBaseline:true}),/round-trip/);});
test('Windows path hazards and traversal rejected',t=>{const d=temp(t);for(const p of ['../x','/etc/passwd','C:/Windows/a','a\\x','aux.txt','a/b.','.git/config','a:stream'])assert.throws(()=>safe(d,p));});
test('Dangling directory links are rejected without existsSync authorization',t=>{const d=temp(t),target=path.join(d,'nonexistent');fs.symlinkSync(target,path.join(d,'link'),process.platform==='win32'?'junction':'dir');assert.throws(()=>safe(d,'link/file.txt'),/链接/);});
test('Existing directory links are rejected',t=>{const d=temp(t);fs.mkdirSync(path.join(d,'actual'));fs.symlinkSync(path.join(d,'actual'),path.join(d,'link'),process.platform==='win32'?'junction':'dir');assert.throws(()=>safe(d,'link/file.txt'));});
test('Non-directory ancestors fail closed',t=>{const d=temp(t);fs.writeFileSync(path.join(d,'file'),'x');assert.throws(()=>writeAtomic(d,'file/nested.txt','bad'));});
test('HTTP GET/HEAD/module MIME and write rejection',async t=>{const d=temp(t);fs.mkdirSync(path.join(d,'dist'));fs.writeFileSync(path.join(d,'dist/play.html'),'candidate');fs.writeFileSync(path.join(d,'dist/reference.html'),'original');fs.writeFileSync(path.join(d,'dist/runtime.mjs'),'export const x=1;');const server=createServer(d);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const url='http://127.0.0.1:'+server.address().port;assert.equal(await(await fetch(url)).text(),'candidate');assert.match((await fetch(url+'/runtime.mjs')).headers.get('content-type'),/javascript/);assert.equal((await fetch(url,{method:'POST'})).status,405);assert.equal((await fetch(url,{headers:{Origin:'https://foreign.invalid'}})).status,403);assert.equal((await fetch(url+'/missing')).status,404);assert.equal(await(await fetch(url,{method:'HEAD'})).text(),'');});

test('Obsolete owned output is removed but an unrelated file is kept',t=>{const d=copy(t);build(d);const f=path.join(d,'dist/build-manifest.json'),m=JSON.parse(fs.readFileSync(f));const old=Buffer.from('old generated');fs.writeFileSync(path.join(d,'dist/obsolete.html'),old);fs.writeFileSync(path.join(d,'dist/personal.txt'),'keep');m.files['dist/obsolete.html']=hash(old);fs.writeFileSync(f,JSON.stringify(m));assert.throws(()=>build(d,{check:true}),/stale/);const r=build(d);assert.equal(r.removed,1);assert.equal(fs.existsSync(path.join(d,'dist/obsolete.html')),false);assert.equal(fs.readFileSync(path.join(d,'dist/personal.txt'),'utf8'),'keep');assert.equal(build(d,{check:true}).changed,0);});
test('Manually changed obsolete output blocks the entire build',t=>{const d=copy(t);build(d);const f=path.join(d,'dist/build-manifest.json'),m=JSON.parse(fs.readFileSync(f));m.files['dist/obsolete.html']=hash(Buffer.from('old generated'));fs.writeFileSync(path.join(d,'dist/obsolete.html'),'manual');fs.writeFileSync(f,JSON.stringify(m));const before=fs.readFileSync(path.join(d,'dist/play.html'));assert.throws(()=>build(d),/Obsolete generated output was edited/);assert.deepEqual(fs.readFileSync(path.join(d,'dist/play.html')),before);});
test('A malicious old manifest cannot authorize deletion outside dist',t=>{const d=copy(t);build(d);const f=path.join(d,'dist/build-manifest.json'),m=JSON.parse(fs.readFileSync(f));m.files['src/compat/30-terra-foundation.js.part']='0'.repeat(64);fs.writeFileSync(f,JSON.stringify(m));assert.throws(()=>build(d),/Invalid previous output/);});
