import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createDisplayPreferences} from '../src/ui/display-preferences.mjs';
import {paintAdventureHud,paintPickupNotice} from '../src/ui/adventure-render.mjs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const frozen=o=>{if(o&&typeof o==='object'){Object.values(o).forEach(frozen);Object.freeze(o);}return o;};
function drawing(){const log=[];const g=new Proxy({measureText:s=>({width:s.length*5})},{get:(t,k)=>k in t?t[k]:(...args)=>log.push([k,...args]),set:(t,k,v)=>{t[k]=v;return true;}});return{g,log};}
function state(){return {layout:{unit:.5,uiW:512,uiH:480,wide:false,slots:Array.from({length:6},(_,i)=>({x:12+i*36,y:24,w:32,h:32}))},model:{score:32,coins:2,time:287,tool:0,keys:['starfury','wood','axe','pickaxe','torch','fire'],counts:[null,64,null,null,60,null],hp:120,maxHp:200,mana:90,maxMana:200,gear:[{key:'head'}],defense:20},actor:{x:200,y:130},boss:null};}
test('Presentation defaults survive denied local storage',()=>{const p=createDisplayPreferences({storage:{getItem(){throw Error('denied')},setItem(){throw Error('denied')}}});assert.deepEqual(p.snapshot(),{text:'normal',contrast:'normal',motion:'system',persisted:false});assert.equal(p.set('text','large').text,'large');assert.equal(p.snapshot().persisted,false);});
test('Display settings have a separate key and roundtrip',()=>{const m=new Map(),storage={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)};const p=createDisplayPreferences({storage});p.set('contrast','high');assert.equal(m.size,1);assert(m.has('marioMix.presentation.v1'));assert.equal(createDisplayPreferences({storage}).snapshot().contrast,'high');});
test('Unknown, malformed, oversized, and nonboolean-style preferences fall back safely',()=>{for(const raw of ['null','[]','{}','oops','x'.repeat(3000),'{"version":2,"values":{"text":"large"}}'])assert.equal(createDisplayPreferences({storage:{getItem:()=>raw}}).snapshot().text,'normal');const p=createDisplayPreferences();assert.throws(()=>p.set('__proto__','x'));assert.throws(()=>p.set('text','huge'));});
test('Display preference snapshots cannot mutate internal state',()=>{const p=createDisplayPreferences();const s=p.snapshot();s.text='large';assert.equal(p.snapshot().text,'normal');});
test('HUD painter accepts frozen M04 model and leaves all gameplay values unchanged',()=>{const s=frozen(state()),before=JSON.stringify(s),{g,log}=drawing();paintAdventureHud({context:g,...s,icon:()=>{},text:()=>{}});assert.equal(JSON.stringify(s),before);assert.equal(log[0][0],'save');assert.equal(log.at(-1)[0],'restore');});
test('HUD slot geometry equals all six existing input regions',()=>{const s=state(),{g,log}=drawing();paintAdventureHud({context:g,...s,icon:()=>{},text:()=>{}});for(const q of s.layout.slots)assert(log.some(e=>e[0]==='fillRect'&&e.slice(1).join(',')===[q.x,q.y,q.w,q.h].join(',')));});
test('HUD retains score, coins, clock, health, mana, defense, and resource counts',()=>{const s=state(),labels=[],{g}=drawing();paintAdventureHud({context:g,...s,icon:()=>{},text:(t,...args)=>labels.push(String(t))});for(const expected of ['1-3','000032','×02','287','120/200','90/200','DEF 20','64','60'])assert(labels.includes(expected),expected);});
test('HUD ratios are clamped and invalid maximum cannot create negative bars',()=>{const s=state();s.model.hp=-10;s.model.maxHp=0;s.model.mana=1e6;const{g,log}=drawing();paintAdventureHud({context:g,...s,icon:()=>{},text:()=>{}});assert(log.filter(e=>e[0]==='fillRect').every(e=>e.slice(1).every(Number.isFinite)&&e[3]>=0&&e[4]>=0));});
test('Boss name and phase survive read-only painting',()=>{const s=state();s.boss=frozen({phase:2,hp:380,maxHp:500});const labels=[],{g,log}=drawing();paintAdventureHud({context:g,...s,icon:()=>{},text:t=>labels.push(String(t))});assert(labels.includes('380/500'));assert(log.some(e=>e[0]==='fillText'&&e[1]==='克苏鲁之眼  II'));});
test('Pickup paint wraps description and does not change queue age',()=>{const notice=frozen({age:28,name:'星怒',effect:'召唤星星攻击敌人，按住攻击键可连续挥动。'}),{g,log}=drawing();paintPickupNotice({context:g,notice,width:256,height:240,canvasWidth:512,canvasHeight:480,wide:false});assert.equal(notice.age,28);assert(log.filter(e=>e[0]==='fillText').length>=2);});
test('Reduced motion makes pickup paint stable without touching expiry or game time',()=>{const n=frozen({age:1,name:'药水',effect:'恢复生命'}),{g}=drawing();paintPickupNotice({context:g,notice:n,width:512,height:288,canvasWidth:1024,canvasHeight:576,wide:true,reducedMotion:true});assert.equal(g.globalAlpha,1);assert.equal(n.age,1);});
test('Display CSS is candidate-scoped and retains hitbox transparency',()=>{const css=read('src/ui/adventure.css');assert(!/^[\s]*(?:body|html|:root)\s*\{/m.test(css));assert(css.includes('prefers-reduced-motion'));assert(css.includes('[data-hud-layout=compact] #t15HudHits'));assert(css.includes('.m07-compact-slots'));assert(!/^#t15HudHits\s*\{display:none/m.test(css));assert(!css.includes('@font-face'));});
test('UI key gate is before legacy key processing, with no extra gameplay wrapper',()=>{const b=read('src/bridges/bindings.bridge.js');assert(b.includes('if(t17Early.presentation?.(e))return true;if(!isTrio())'));const v=read('src/ui/adventure-shell.mjs');assert(v.includes("e.code === 'Tab'"));assert(!/\b(?:fixedUpdate|draw|step|togglePause)\s*=/.test(v));});
test('Quick hints read current bindings rather than fixed Space/J/P text',()=>{const v=read('src/ui/adventure-shell.mjs');assert(v.includes('getBindings()?.actions'));assert(v.includes("'close', refreshHints"));assert(!v.includes('KEYBOARD ONLY'));});
test('No new font, external art, analytics, or font dependency in UI modules',()=>{for(const f of ['src/ui/adventure-shell.mjs','src/ui/adventure-render.mjs','src/ui/display-preferences.mjs'])assert(!/https?:|fetch\s*\(|@font-face/.test(read(f)),f);});
