import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildQuickGuide,formatPlayerReport} from '../src/ui/quick-guide.mjs';
import {createDisplayPreferences} from '../src/ui/display-preferences.mjs';
import {createActionDefinitions} from '../src/content/actions.mjs';
import {keyLabel} from '../src/ui/key-label.mjs';
const read = p => fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const args=()=>({bindings:{actions:createActionDefinitions()},keyLabel,padLabel:i=>'PAD '+i});
test('Help describes six concrete actions from current bindings',()=>{const rows=buildQuickGuide(args());assert.equal(rows.length,6);assert(rows.every(r=>r.title&&r.text&&r.keys));assert.equal(rows.find(r=>r.id==='jump').keys,'空格 / K');});
test('Custom keyboard mapping immediately changes help',()=>{const a=args();a.bindings.actions.jump.keys=['KeyU'];a.bindings.actions.interact.keys=['KeyI'];const rows=buildQuickGuide(a);assert.equal(rows[1].keys,'U');assert.equal(rows[3].keys,'I');});
test('Gamepad prompts are read from the binding model, not fixed buttons',()=>{const a=args();a.device='gamepad';a.bindings.actions.attack.pad=[9];assert(buildQuickGuide(a)[2].keys.endsWith('PAD 9'));});
test('Missing or unbound inputs have an explicit label',()=>{assert(buildQuickGuide({...args(),bindings:null}).every(r=>r.keys.includes('未绑定')));const a=args();a.bindings.actions.jump.keys=[];assert.equal(buildQuickGuide(a)[1].keys,'未绑定');});
test('Help is read-only and result items cannot mutate configuration',()=>{const a=args(),before=JSON.stringify(a.bindings);const rows=buildQuickGuide(a);assert(Object.isFrozen(rows[0]));assert.equal(JSON.stringify(a.bindings),before);});
test('Feedback export excludes arbitrary caller fields and control data',()=>{const text=formatPlayerReport({version:'0.4.2',device:'keyboard',password:'SECRET',bindings:{private:'PRIVATE'},path:'C:/private'});assert(text.includes('0.4.2'));assert(!/SECRET|PRIVATE|C:\//.test(text));});
test('Feedback summary limits lengths and strips injected lines',()=>{const text=formatPlayerReport({version:'0.4.2\nInjected: yes',mode:'x'.repeat(1000)});assert.equal(text.split('\n').filter(x=>x.startsWith('Injected')).length,0);assert(text.length<450);});
test('Valid saved preferences report persisted status on reload',()=>{const stored=JSON.stringify({version:1,values:{text:'large',contrast:'high',motion:'reduced'}});const s=createDisplayPreferences({storage:{getItem:()=>stored}}).snapshot();assert.equal(s.persisted,true);assert.equal(s.text,'large');});
test('Invalid partial saved preferences are not reported as fully persisted',()=>{const s=createDisplayPreferences({storage:{getItem:()=>'{"version":1,"values":{"text":"large"}}'}}).snapshot();assert.equal(s.persisted,false);});
test('Help uses an accessible dialog name, not a forced first-visit modal',()=>{const s=read('src/ui/adventure-help.mjs');assert(s.includes("aria-labelledby"));assert(s.includes("life.listen(learn,'click',open)"));assert(!/setTimeout|setInterval|requestAnimationFrame/.test(s));assert(s.includes('hintKey='));});
test('Handbook returns control without changing its pre-existing pause',()=>{const s=read('src/ui/adventure-help.mjs');assert(s.includes("ownsPause=getMode()==='playing'"));assert(s.includes("!doc.hidden&&getMode()==='paused'"));assert(s.includes('serial!==generation'));});
test('Help and display preserve BFCache resources and detach only on terminal exit',()=>{const s=read('src/bridges/adventure-shell.bridge.js');assert(s.includes('if(!e.persisted)'));assert(!s.includes('{once:true}'));assert(s.includes('terraAdventureHelp.suspend()'));});
test('Prototype host also preserves cache-entry listeners',()=>{assert(read('src/bridges/stages.bridge.js').includes("if(e.persisted){clearInput()"));});
test('Settings dialog has an actual accessible title',()=>{const s=read('src/bridges/bindings.bridge.js');assert(s.includes("setAttribute('aria-labelledby','t21BindingsTitle')"));assert(s.includes('id="t21BindingsTitle"'));});
test('New handbook is scoped and has no new animation or external art',()=>{const s=read('src/ui/adventure-help.mjs');assert(!/fetch\s*\(|https?:|@font-face|fixedUpdate\s*=|draw\s*=/.test(s));const css=read('src/ui/adventure.css');assert(css.includes('body[data-terra-ui="m07"]'));assert(!/@keyframes|@font-face/.test(css));});
