import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createActionDefinitions} from '../src/content/actions.mjs';
import {assignMountBinding} from '../src/input/mount-binding.mjs';
import {createBindingsModel} from '../src/input/bindings-model.mjs';
import {createKeyboardRouter} from '../src/input/keyboard-router.mjs';
import {createBindingCapture} from '../src/input/binding-capture.mjs';
import {createLifetime} from '../src/runtime/lifetime.mjs';
import {createSettingsSession} from '../src/ui/settings-session.mjs';
const definitions=createActionDefinitions();
const model=()=>createBindingsModel({definitions,assignMount:assignMountBinding});
const gold=n=>fs.readFileSync(new URL('golden/'+n+'.txt',import.meta.url),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
function oldLoader(){
 const c={T21_ACTIONS:definitions,t21DefaultBinds:()=>model().defaults(),t21Binds:model().defaults(),t25NeedsSave:false,t17Input:{deadzone:.22},clamp:(v,l,h)=>Math.max(l,Math.min(h,v))};
 vm.createContext(c);vm.runInContext(gold('bindings-load'),c);return c;
}
function valid(){const p=model().config(.22);p.actions.interact.pad=[];return p;}
test('M02 config instances and snapshots have no shared mutable bindings',()=>{const a=model(),b=model();a.bind('jump','keys','KeyT');const x=a.snapshot();x.attack.pad[0]=31;assert.deepEqual(b.snapshot(),model().defaults());assert.equal(a.snapshot().attack.pad[0],1);});
test('M01 default export/import failure reproduced and M02 defaults round trip',()=>{const m=model(),data=m.config(.22),old=oldLoader();assert.throws(()=>old.t21LoadBinds(data),/多个动作/);assert.deepEqual(m.load(data),{needsSave:false,deadzone:.22});assert.deepEqual(m.config(.22),data);});
test('Only contextual pad6 interact/recall pair is newly allowed, not keyboard sharing',()=>{const m=model(),d=valid();d.actions.jump.keys=['KeyJ'];assert.throws(()=>m.load(d),/多个动作/);assert.equal(m.bind('jump','pad',6).ok,false);assert.equal(m.bind('recall','pad',6).ok,true);});
test('Known version-1 configs match original loader across custom keys and deadzones',()=>{for(let i=0;i<80;i++){const d=valid();d.actions.jump.keys=['KeyCustom'+i];d.deadzone=(i-10)/100;const a=model(),b=oldLoader();a.load(d);b.t21LoadBinds(d);assert.deepEqual(a.snapshot(),plain(b.t21Binds));assert.equal(a.config(Math.max(.12,Math.min(.4,d.deadzone))).deadzone,b.t17Input.deadzone);}});
test('Older controlLayout migration preserves custom non-return bindings',()=>{const d=valid();d.controlLayout=5;d.actions.jump.keys=['KeyT'];d.actions.recall.pad=[8];const a=model(),b=oldLoader();const result=a.load(d);b.t21LoadBinds(d);assert.deepEqual(a.snapshot(),plain(b.t21Binds));assert.equal(result.needsSave,true);assert.deepEqual(a.snapshot().jump.keys,['KeyT']);assert.deepEqual(a.snapshot().recall.pad,[6]);});
test('Invalid config load is transactional and never changes deadzone externally',()=>{for(const mutate of [d=>d.version=2,d=>d.actions.jump=null,d=>d.actions.jump.pad=[32],d=>d.actions.jump.keys=[],d=>d.actions.jump.keys=[{}],d=>d.actions.jump.keys=['KeyJ']]){const m=model(),before=m.config(.22),d=valid();mutate(d);assert.throws(()=>m.load(d));assert.deepEqual(m.config(.22),before);}});
test('Unknown action keys cannot poison definitions or object prototype',()=>{const m=model(),d=valid();Object.assign(d.actions,JSON.parse('{"__proto__":{"keys":["KeyT"],"pad":[]},"constructor":{}}'));m.load(d);assert.equal(Object.hasOwn(m.snapshot(),'__proto__'),false);assert.equal({}.keys,undefined);});
test('Duplicate values and binding lengths follow baseline normalization',()=>{const d=valid();d.actions.torch={keys:['KeyT','KeyT','KeyU','KeyI','KeyO','KeyN','KeyM','KeyY'],pad:[20,20,21,22,23,24]};const a=model(),b=oldLoader();a.load(d);b.t21LoadBinds(d);assert.deepEqual(a.snapshot(),plain(b.t21Binds));});
test('Reserved physical keys and invalid action/source are not bound',()=>{const m=model(),before=m.snapshot();for(const k of ['Tab','AltLeft','ControlRight','MetaRight','123','<x>'])assert.equal(m.bind('jump','keys',k).ok,false);for(const v of [-1,32,1.5,NaN,'1'])assert.equal(m.bind('jump','pad',v).ok,false);assert.equal(m.bind('__proto__','keys','KeyT').ok,false);assert.equal(m.bind('jump','other',0).ok,false);assert.deepEqual(m.snapshot(),before);});
test('Conflict response reports owner, state unchanged on failure',()=>{const m=model(),before=m.snapshot();assert.deepEqual(m.bind('jump','keys','KeyJ'),{ok:false,reason:'conflict',owner:'attack'});assert.deepEqual(m.snapshot(),before);});
test('All 32 mount reassignments match original transactional algorithm',()=>{const old=vm.runInNewContext(gold('mount-binding')+';t24AssignMount',{structuredClone});for(let i=0;i<32;i++){const a=model().defaults(),b=structuredClone(a);assert.equal(assignMountBinding(a,i),old(b,i));assert.deepEqual(a,plain(b));}});
test('Mount full-table failure leaves supplied table unchanged',()=>{const b={mount:{pad:[0],keys:[]},all:{pad:[0],keys:[]}};for(let i=1;i<32;i++)b['occupied'+i]={pad:[i],keys:[]};const before=structuredClone(b);assert.equal(assignMountBinding(b,0),false);assert.deepEqual(b,before);});
test('Reset restores shipped defaults without sharing their arrays',()=>{const m=model();m.bind('jump','keys','KeyT');m.reset();assert.deepEqual(m.snapshot(),m.defaults());});
function keyboard(){let binds=model().defaults();const canonical=new Set([...Object.values(definitions).flatMap(d=>d.keys),'Digit1','KeyR','KeyC','Enter']);return {r:createKeyboardRouter({definitions,getBindings:()=>binds,canonicalKeys:canonical}),set:v=>binds=v,bindings:()=>binds,canonical};}
test('Keyboard map preserves captured key-up after rebinding while held',()=>{const k=keyboard();k.r.route({type:'keydown',code:'KeyK'},'playing');const d=k.bindings();d.jump.keys=['KeyT'];k.set(d);assert.equal(k.r.route({type:'keyup',code:'KeyK'},'paused').event.code,'Space');assert.deepEqual(k.r.snapshot(),[]);});
test('Keyboard pause, menu bypass and unassigned canonical suppression',()=>{const k=keyboard();assert.equal(k.r.route({type:'keydown',code:'KeyP'},'paused').kind,'resume');assert.equal(k.r.route({type:'keydown',code:'KeyK'},'select').kind,'pass');k.bindings().jump.keys=['KeyT'];assert.equal(k.r.route({type:'keydown',code:'KeyK'},'playing').kind,'consume');assert.equal(k.r.route({type:'keydown',code:'Digit1'},'playing').kind,'pass');});
test('Keyboard routing agrees with original across 1200 mixed events',()=>{const k=keyboard(),c={mode:'playing',t21Binds:k.bindings(),T21_ACTIONS:definitions,t21KeyHeld:new Map(),t17Keys:k.canonical,togglePause(){c.resume++;},t17ResetActions(){},resume:0,t21EarlyBase:e=>({kind:'forward',event:e})};vm.createContext(c);vm.runInContext(gold('keyboard-router'),c);const modes=['playing','paused','flag','select'],codes=['KeyK','KeyX','KeyT','Digit1','KeyP','KeyC','Enter','Space','KeyA','Escape'];for(let i=0;i<1200;i++){c.mode=modes[i%4];const e={type:i%3?'keydown':'keyup',code:codes[i%codes.length],repeat:i%5===0,key:'',ctrlKey:false,metaKey:false,altKey:false};const a=k.r.route(e,c.mode),before=c.resume,b=c.originalRoute(e);if(a.kind==='resume'){assert.equal(c.resume,before+1);assert.equal(b,true);}else if(a.kind==='consume')assert.equal(b,true);else assert.deepEqual(plain(a.kind==='mapped'?a.event:e),plain(b.event));assert.deepEqual(plain(k.r.snapshot()),plain([...c.t21KeyHeld]));}});
test('Clearing keyboard ownership releases held mapping records',()=>{const k=keyboard();k.r.route({type:'keydown',code:'KeyK'},'playing');k.r.clear();assert.deepEqual(k.r.snapshot(),[]);});
function capture(ok=true){const calls=[],blocked=new Set();return {calls,blocked,c:createBindingCapture({assign:(...a)=>{calls.push(a);return ok;},mask:i=>blocked.add(i),unmask:i=>blocked.delete(i)})};}
test('Held pad during capture does not bind until an actual release and edge',()=>{const{c,calls}=capture();c.begin('jump','pad',[true]);c.poll([true]);assert.equal(calls.length,0);c.poll([false]);assert.equal(c.poll([true]).ok,true);assert.equal(calls.length,1);});
test('Newly bound pad stays masked until released, with no repeated assignment',()=>{const{c,calls,blocked}=capture();c.begin('jump','pad',[]);c.poll([true]);assert(blocked.has(0));c.poll([true]);assert.equal(calls.length,1);c.poll([false]);assert(!blocked.size);});
test('Release barrier prevents assigning a second control while first is held',()=>{const{c,calls}=capture();c.begin('jump','pad');c.poll([true]);c.begin('attack','pad',[true,false]);c.poll([true,true]);assert.equal(calls.length,1);c.poll([false,false]);c.poll([false,true]);assert.equal(calls.length,2);});
test('Capture ignores repeat/modifiers and Escape cancels either input source',()=>{const{c,calls}=capture();c.begin('jump','keys');for(const e of [{repeat:true},{ctrlKey:true},{altKey:true},{metaKey:true}])c.key({type:'keydown',code:'KeyT',...e});assert(!calls.length);assert.equal(c.key({type:'keydown',code:'Escape'}).kind,'cancel');assert.equal(c.pending(),null);c.begin('jump','pad');c.key({type:'keydown',code:'Escape'});assert.equal(c.pending(),null);});
test('Failed pad binding clears capture without adding a mask',()=>{const{c,blocked}=capture(false);c.begin('jump','pad');assert.equal(c.poll([true]).ok,false);assert(!blocked.size);assert.equal(c.pending(),null);});
test('Capture context cleanup clears pending state and samples',()=>{const{c}=capture();c.begin('jump','pad');c.poll([true]);c.clear();assert.deepEqual(c.snapshot(),{active:null,previous:[],releasing:[]});});
function timerHarness(){const timers=new Map();let next=0;return {timers,make:()=>createLifetime({scheduleInterval:fn=>{timers.set(++next,fn);return next;},cancelInterval:id=>timers.delete(id)})};}
test('Lifetime disposal runs LIFO once, does not leak timers',()=>{const h=timerHarness(),s=h.make(),log=[];s.defer(()=>log.push(1));s.defer(()=>log.push(2));s.interval(()=>{},16);assert.equal(h.timers.size,1);s.dispose();s.dispose();assert.deepEqual(log,[2,1]);assert.equal(h.timers.size,0);assert.throws(()=>s.interval(()=>{},16));});
test('Lifetime clears all remaining resources when a disposer throws',()=>{const h=timerHarness(),s=h.make();s.interval(()=>{},16);s.defer(()=>{throw Error('x');});assert.throws(()=>s.dispose(),AggregateError);assert.equal(h.timers.size,0);});
test('Lifetime invalidates already queued timer callbacks',()=>{const h=timerHarness(),s=h.make();let count=0;s.interval(()=>count++,16);const fn=[...h.timers.values()][0];s.dispose();fn();assert.equal(count,0);});
test('Lifetime owns and removes an event listener',()=>{const h=timerHarness(),s=h.make(),t=new EventTarget();let count=0;s.listen(t,'ping',()=>count++);t.dispatchEvent(new Event('ping'));s.dispose();t.dispatchEvent(new Event('ping'));assert.equal(count,1);});
function session(mode='playing',fail=false){const h=timerHarness(),d={mode,shown:false,toggles:0,resets:0,focus:0,polls:0};const s=createSettingsSession({makeLifetime:h.make,getMode:()=>d.mode,togglePause:()=>{d.toggles++;d.mode=d.mode==='playing'?'paused':'playing';},resetInput:()=>d.resets++,render(){},show(){if(fail)throw Error('show failed');d.shown=true;},hide:()=>d.shown=false,focus:()=>d.focus++,poll:()=>d.polls++});return{s,d,h};}
test('Settings open/close 100 times acquires one timer and releases all',()=>{const{s,d,h}=session();for(let i=0;i<100;i++){assert(s.open());assert.equal(h.timers.size,1);assert.equal(s.open(),false);assert.equal(d.mode,'paused');assert(s.close());assert.equal(h.timers.size,0);assert.equal(d.mode,'playing');assert.equal(s.close(),false);}assert.equal(d.toggles,200);});
test('Settings opened from a paused game must not resume it',()=>{const{s,d}=session('paused');s.open();s.close();assert.equal(d.mode,'paused');assert.equal(d.toggles,0);});
test('Settings page exit clears resources without background resume or focus',()=>{const{s,d,h}=session();s.open();s.close({resume:false,restoreFocus:false});assert.equal(d.mode,'paused');assert.equal(d.focus,0);assert.equal(h.timers.size,0);});
test('Settings does not resume a scene whose mode changed while open',()=>{const{s,d}=session();s.open();d.mode='select';s.close();assert.equal(d.mode,'select');assert.equal(d.toggles,1);});
test('Settings show failure restores pause ownership and no active session remains',()=>{const{s,d,h}=session('playing',true);assert.throws(()=>s.open(),/show failed/);assert.equal(d.mode,'playing');assert.equal(h.timers.size,0);assert.equal(s.isOpen(),false);});
