#!/usr/bin/env node
/** Compile editable messages to a browser dictionary, without mutating the legacy dictionary. */
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {readOptional,writeAtomic} from '../lib/safe-path.mjs';
import {validateConfig} from './model.mjs';
export const ROOT=fileURLToPath(new URL('../../',import.meta.url));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const json=value=>Buffer.from(JSON.stringify(value,null,2)+'\n');
export function validateMessages(data) {
  if(data?.schemaVersion!==1||data.language!=='en'||!Array.isArray(data.messages)||data.messages.length>10000)throw Error('Invalid English catalog');
  const ids=new Set(),messages=Object.create(null);
  for(const row of data.messages){
    if(!/^[a-z][a-z0-9.-]*$/.test(row.id)||ids.has(row.id)||typeof row.source!=='string'||!row.source.trim()||typeof row.text!=='string'||!row.text.trim()||row.source.length>24000||row.text.length>30000||['__proto__','constructor','prototype'].includes(row.source))throw Error('Invalid locale message: '+row.id);
    const parameters=value=>[...new Set([...value.matchAll(/\{([a-zA-Z][a-zA-Z0-9_]*)\}/g)].map(m=>m[1]))].sort();
    if(JSON.stringify(parameters(row.source))!==JSON.stringify(parameters(row.text)))throw Error('Translation parameter mismatch: '+row.id);
    if(Object.hasOwn(messages,row.source)&&messages[row.source]!==row.text)throw Error('Conflicting translations: '+row.source);
    ids.add(row.id);messages[row.source]=row.text;
  }
  return messages;
}
export function planContent(root=ROOT,{reader=p=>readOptional(root,p)}={}){
  const get=p=>{const b=reader(p);if(!b)throw Error('Missing platform input: '+p);return b;};
  const config=validateConfig(JSON.parse(get('config/site-platform.json')));
  const source=JSON.parse(get('content/locales/en.json')),messages=validateMessages(source);
  const browser={schemaVersion:1,edition:config.edition,site:config.site};
  const keyed=JSON.stringify(Object.fromEntries(source.messages.map(row=>[row.id,{zh:row.source,en:row.text}]))).replace(/</g,'\\u003c');
  const sourceJSON=JSON.stringify({en:messages}).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  const files=new Map([
    ['assets/i18n/messages.js',Buffer.from('/* Generated by npm run platform:content. Edit content/locales/en.json. */\nglobalThis.SITE_LOCALE_MESSAGES = Object.freeze('+sourceJSON+');\nglobalThis.SITE_LOCALE_KEYS = Object.freeze('+keyed+');\n')],
    ['assets/platform/config.js',Buffer.from('/* Generated platform identity; no credentials or operational state. */\nglobalThis.SITE_PLATFORM = Object.freeze('+JSON.stringify(browser)+');\n')]
  ]);
  files.set('docs/platform/generated-files.json',json({schemaVersion:1,owner:'localization',sources:{'content/locales/en.json':sha(get('content/locales/en.json')),'config/site-platform.json':sha(get('config/site-platform.json'))},files:Object.fromEntries([...files].map(([p,b])=>[p,sha(b)]))}));
  return {files,messages:source.messages.length};
}
export function build(root=ROOT,{check=false}={}){
 const plan=planContent(root),changes=[...plan.files].filter(([p,b])=>!readOptional(root,p)?.equals(b));
 if(check&&changes.length)throw Error('Platform content is stale: npm run platform:content\n'+changes.map(([p])=>p).join('\n'));
 if(!check)for(const[p,b]of changes)writeAtomic(root,p,b);
 return {changed:changes.length,messages:plan.messages};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))try{if(process.argv.slice(2).some(x=>x!=='--check'))throw Error('Unsupported option');console.log(build(ROOT,{check:process.argv.includes('--check')}));}catch(error){console.error(error.message);process.exitCode=1;}
