import{roomTestPack}from'../src/room-test.mjs';
import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import os from'node:os';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
import{compileAll,compileReference,makeExtensions,tiledMap}from'../src/reference.mjs';import{validateCampaign}from'../src/campaign.mjs';import{mapSVG}from'../src/map-view.mjs';import{createStageCatalog}from'../vendor/m06/stage-catalog.mjs';import{createPlatformMotor}from'../vendor/m06/platform-motor.mjs';import{createPlatformStage}from'../vendor/m06/platform-stage.mjs';import{createStageSession}from'../vendor/m06/stage-session.mjs';import{createLifetime}from'../vendor/m06/lifetime.mjs';import{ROOT,build}from'../scripts/build.mjs';import{fork}from'../scripts/fork.mjs';import{integrationPlan,applyIntegration,undo}from'../scripts/integrate.mjs';import{createServer}from'../scripts/serve.mjs';import{pack}from'../scripts/pack.mjs';
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p))),refs=read('data/reference/world-1.json'),compiled=compileAll(refs),extensions=makeExtensions(compiled);const clone=x=>structuredClone(x);const room=(id,which='main')=>compiled.find(c=>c.id===id).rooms.find(r=>r.room===which);
function temp(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'level-kit-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p;}
function kit(t){const p=temp(t);fs.cpSync(ROOT,p,{recursive:true,filter:q=>!q.split(path.sep).includes('.local')});return p;}
function target(t){const p=temp(t),put=(f,b)=>{fs.mkdirSync(path.dirname(path.join(p,f)),{recursive:true});fs.writeFileSync(path.join(p,f),b);};put('package.json','{"version":"0.4.2"}');const dirs={'stage-catalog.mjs':'src/content','platform-stage.mjs':'src/simulation','platform-motor.mjs':'src/simulation','stage-session.mjs':'src/runtime','lifetime.mjs':'src/runtime'};for(const[n,d]of Object.entries(dirs))put(d+'/'+n,fs.readFileSync(path.join(ROOT,'vendor/m06',n)));for(const type of ['maps','characters','stages','audio'])fs.mkdirSync(path.join(p,'content/extensions',type),{recursive:true});return p;}
function session(pack=extensions){const catalog=createStageCatalog(pack),motor=createPlatformMotor();return createStageSession({catalog,drivers:{'platform-v1':p=>createPlatformStage({...p,motor})},makeLifetime:()=>createLifetime({scheduleInterval:setInterval,cancelInterval:clearInterval})});}
test('four source templates and eight rooms, not thirty-two reconstructed maps',()=>{assert.equal(compiled.length,4);assert.equal(compiled.reduce((n,c)=>n+c.rooms.length,0),8);assert.equal(extensions.stages.length,4);});
test('every source operation emits geometry, object or explicit marker',()=>{for(const c of compiled)for(const r of c.rooms)for(const o of r.coverage)assert.ok(o.geometry+o.objects+o.annotations>0,o.kind);});
test('all four templates validate through actual M06 stage contract',()=>assert.doesNotThrow(()=>createStageCatalog(extensions)));
test('source 1-1 first pipe keeps x224 and height16 at scale2',()=>{const q=room('1-1').geometry.find(g=>g.type==='Pipe');assert.deepEqual([q.x,q.y,q.w,q.h],[448,176,32,32]);});
test('source 1-1 ground gaps are not filled for convenience',()=>{const f=room('1-1').geometry.filter(g=>g.type==='Floor');assert.equal(f[0].w,1104);assert.equal(f[1].x,1136);assert.equal(f[2].x,1424);});
test('source 1-2 includes entrance/main/bonus/exit not just surface',()=>assert.deepEqual(compiled[1].rooms.map(x=>x.room),['main','entrance','bonus','exit']));
test('source 1-2 underground ceiling and pipe route',()=>{const q=room('1-2').geometry.find(g=>g.x===96&&g.y===32);assert.equal(q.w,1328);assert.equal(room('1-2').objects.filter(o=>o.kind==='portal').length,2);});
test('source 1-3 tree and moving bounds',()=>{const q=room('1-3').geometry.find(g=>g.type==='Tree');assert.deepEqual([q.x,q.y,q.w],[288,192,64]);assert.ok(room('1-3').geometry.some(g=>g.motion?.min===1320&&g.motion?.max===1440));});
test('source 1-4 start stairs and bridge positional expansion',()=>{assert.deepEqual(room('1-4').geometry.slice(0,3).map(q=>[q.x,q.y,q.w]),[[0,112,48],[48,128,16],[64,144,16]]);assert.ok(room('1-4').geometry.some(q=>q.type==='Bridge'&&q.x===2048&&q.w===208));});
test('castle firebars/boss remain typed unimplemented markers',()=>{const r=room('1-4');assert.equal(r.annotations.filter(o=>o.kind==='Firebar').length,7);assert.equal(r.annotations.find(o=>o.kind==='Bowser').state,'待接入');assert.equal(r.objects.some(o=>o.kind==='walker'),false);});
test('platform generator initial elevations preserve source two-unit offset',()=>{const q=room('1-2').geometry.filter(q=>q.x===2192);assert.deepEqual(q.map(x=>x.y),[208,112]);assert.ok(q.every(x=>!x.motion));});
test('hidden blocks are non-solid markers until bump behavior is implemented',()=>{const r=room('1-4');assert.equal(r.annotations.filter(o=>o.kind==='HiddenBlock').length,6);for(const o of r.annotations.filter(o=>o.kind==='HiddenBlock'))assert.equal(r.geometry.some(g=>g.id===o.id),false);});
test('all spawn boxes are free of solid collision',()=>{const motor=createPlatformMotor();for(const c of compiled)for(const r of c.rooms)for(const s of r.objects.filter(o=>o.kind==='spawn'))assert.equal(r.geometry.some(g=>g.collision==='solid'&&motor.overlap(s,g)),false,r.id+'/'+s.id);});
test('room graph has valid return destinations',()=>{for(const c of compiled)for(const r of c.rooms)for(const o of r.objects.filter(o=>o.kind==='portal'))assert.ok(c.rooms.find(x=>x.room===o.targetRoom)?.objects.some(s=>s.id===o.targetSpawn&&s.kind==='spawn'));});
test('unknown map operations fail explicitly',()=>{const m=clone(refs.maps[0]);m.rooms[0].ops.push({kind:'Unknown',x:1,y:1});assert.throws(()=>compileReference(m),/Unknown/);});
test('pathological fills and out-of-bounds geometry fail',()=>{const m=clone(refs.maps[0]);m.rooms[0].ops=[{kind:'Fill',thing:'Brick',nx:9999}];assert.throws(()=>compileReference(m));m.rooms[0].ops=[{kind:'Stone',x:-1}];assert.throws(()=>compileReference(m));});
test('compilation deterministic and source is not mutated',()=>{const before=JSON.stringify(refs);assert.equal(JSON.stringify(compileAll(refs)),JSON.stringify(compiled));assert.equal(JSON.stringify(refs),before);});
test('Tiled object export includes collision/gameplay/reference layers',()=>{const t=tiledMap(room('1-4'));assert.deepEqual(t.layers.map(l=>l.name),['collision','gameplay','reference-markers']);assert.equal(t.tilesets.length,0);assert.equal(new Set(t.layers.flatMap(l=>l.objects.map(o=>o.id))).size,t.layers.reduce((n,l)=>n+l.objects.length,0));});
test('SVG escapes labels and exposes structural scope',()=>{const s=mapSVG({...room('1-1'),title:'<img onerror=x>'});assert.match(s,/&lt;img/);assert.ok(!s.includes('<img'));assert.match(s,/不是完成版/);});
test('campaign 32 IDs, first 3 playable and Ori pending',()=>{const c=validateCampaign(read('data/campaign.json'));assert.equal(c.chapters.filter(c=>c.production==='playable').length,3);assert.equal(c.chapters[3].characters[0],'奥日');assert.equal(c.chapters[3].playHref,null);assert.equal(c.chapters.filter(c=>c.template.status==='pending').length,28);});
test('future stage cannot pretend to offer download or play',()=>{const c=read('data/campaign.json');c.chapters[4].template.downloadHref='/fake.zip';assert.throws(()=>validateCampaign(c));});
test('template compilation does not certify original geometry',()=>{const c=read('data/campaign.json');c.chapters[0].template.originalReview='verified';assert.throws(()=>validateCampaign(c));});
test('playable M06 sample moves in each imported entry',()=>{for(const id of ['1-1','1-2','1-3','1-4']){const s=session();const start=s.start('atlas-'+id,'atlas-scout',{allowDraft:true});for(let i=0;i<12;i++)s.step({x:1});assert.ok(s.view().scene.p.x>start.scene.p.x,id);s.stop();}});
test('paused/restarted stage has consistent scope and position',()=>{const s=session();s.start('atlas-1-1','atlas-runner',{allowDraft:true});s.step({x:1});s.pause();const v=s.view().scene;s.step({x:1});assert.deepEqual(s.view().scene,v);s.resume();s.restart();assert.equal(s.view().scene.p.x,32);s.stop();assert.equal(s.active(),false);});
test('new character config uses the same map without editing source geometry',()=>{const p=clone(extensions);p.characters[0].id='guest-runner';p.stages[0].characters.push('guest-runner');p.stages=p.stages.slice(0,1);p.characters=p.characters.filter(c=>c.id!=='atlas-runner');p.stages[0].characters=p.stages[0].characters.filter(x=>x!=='atlas-runner');const c=createStageCatalog(p);assert.ok(c.plan('atlas-1-1','guest-runner',{allowDraft:true}));});
test('build is repeatable and detects hand edited output',t=>{const p=kit(t);assert.equal(build(p,{check:true}).changed,0);fs.appendFileSync(path.join(p,'previews/1-1-main.svg'),'x');assert.throws(()=>build(p),/手改/);});
test('fork only writes new data and refuses name collision',t=>{const p=kit(t);const b=fs.readFileSync(path.join(p,'src/reference.mjs'));fork(p,{id:'guest-level',from:'1-1',apply:true});assert.deepEqual(fs.readFileSync(path.join(p,'src/reference.mjs')),b);assert.throws(()=>fork(p,{id:'guest-level',from:'1-1',apply:true}));assert.equal(JSON.parse(fs.readFileSync(path.join(p,'content/forks/guest-level.json'))).stages[0].id,'guest-level');});
test('integration dry-run makes no writes',t=>{const p=target(t);const plan=integrationPlan(p);assert.equal(plan.changes.length,15);assert.equal(fs.readdirSync(path.join(p,'content/extensions/maps')).length,0);});
test('integration applies data only, repeat safe, undo restores',t=>{const p=target(t);const plan=integrationPlan(p),src=fs.readFileSync(path.join(p,'src/content/stage-catalog.mjs'));const r=applyIntegration(plan);assert.equal(integrationPlan(p).changes.length,0);assert.deepEqual(fs.readFileSync(path.join(p,'src/content/stage-catalog.mjs')),src);assert.equal(undo(p,r,{apply:true}),15);assert.equal(fs.readdirSync(path.join(p,'content/extensions/maps')).length,0);});
test('integration conflict blocks all writes',t=>{const p=target(t);const d=path.join(p,'content/extensions/stages/atlas-1-1');fs.mkdirSync(d);fs.writeFileSync(path.join(d,'stage.json'),JSON.stringify({...extensions.stages[0],title:'someone else'}));assert.throws(()=>integrationPlan(p),/同名/);assert.equal(fs.readdirSync(path.join(p,'content/extensions/maps')).length,0);});
test('integration catches edits between check and apply',t=>{const p=target(t),plan=integrationPlan(p);fs.appendFileSync(path.join(p,'src/content/stage-catalog.mjs'),'\n');assert.throws(()=>applyIntegration(plan),/检查后/);});
test('integration rejects dangling symlink without existsSync',t=>{const p=target(t),f=path.join(p,'content/extensions/maps/dangling');fs.symlinkSync(path.join(p,'absent'),f,process.platform==='win32'?'junction':'dir');assert.throws(()=>integrationPlan(p));});
test('undo protects post-import edits',t=>{const p=target(t),r=applyIntegration(integrationPlan(p));fs.appendFileSync(path.join(p,'content/extensions/stages/atlas-1-1/stage.json'),' ');assert.throws(()=>undo(p,r,{apply:true}),/后续/);});
test('real HTTP serves HTML and JS MIME, rejects writes and traversal',async t=>{const s=createServer(ROOT);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>s.close());const base='http://127.0.0.1:'+s.address().port;assert.equal((await fetch(base)).status,200);assert.match((await fetch(base+'/ui/workbench.mjs')).headers.get('content-type'),/javascript/);assert.equal((await fetch(base,{method:'POST'})).status,405);assert.equal((await fetch(base+'/ui/%2e%2e%2fpackage.json')).status,400);assert.equal((await fetch(base+'/no-file')).status,404);});
test('source and individual template archives are deterministic',t=>{const p=kit(t);const a=pack(p),b=pack(p);assert.deepEqual(a,b);assert.equal(a.length,5);assert.ok(a.every(x=>x.bytes>1000));});

test('each explicit room test retains only its reachable graph without editing base',()=>{const before=JSON.stringify(extensions);for(const c of compiled)for(const r of c.rooms){const p=roomTestPack(extensions,'atlas-'+c.id,r.room);assert.doesNotThrow(()=>createStageCatalog(p));}assert.equal(JSON.stringify(extensions),before);});

test('review status requires real reviewer and evidence fields',()=>{const c=read('data/campaign.json');c.chapters[0].template.originalReview='reviewed';assert.throws(()=>validateCampaign(c),/缺少/);c.chapters[0].template.reviewedBy='fixture-reviewer';c.chapters[0].template.reviewEvidence=['fixture-only geometry review'];assert.doesNotThrow(()=>validateCampaign(c));});

test('malformed edited fork fails verify before generating outputs',t=>{const p=kit(t);fork(p,{id:'bad-level',from:'1-1',apply:true});fs.writeFileSync(path.join(p,'content/forks/bad-level.json'),'{}');assert.throws(()=>build(p,{check:true}));});
test('a late generated conflict causes zero earlier writes',t=>{const p=kit(t);const source=JSON.parse(fs.readFileSync(path.join(p,'data/reference/world-1.json')));source.maps[0].rooms[0].title='changed room title';fs.writeFileSync(path.join(p,'data/reference/world-1.json'),JSON.stringify(source));const target=path.join(p,'tiled/1-4-main.tmj');fs.appendFileSync(target,' ');const first=fs.readFileSync(path.join(p,'data/generated/world-1.json'));assert.throws(()=>build(p),/手改/);assert.deepEqual(fs.readFileSync(path.join(p,'data/generated/world-1.json')),first);});
