import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../../assets/site-analytics.js',import.meta.url),'utf8');
function setup({host='aha-xiaoq.github.io',protocol='https:',search='',embedded=false,broken=false,disabled=false}={}){const events={},sent=[],beacons=[],data=new Map();let now=1000000000;const location={hostname:host,protocol,pathname:'/',search};const window={__XIAOQ_ANALYTICS_DISABLED__:disabled,addEventListener:(n,f)=>events[n]=f};window.self=window;window.top=embedded?{}:window;const storage={getItem:k=>{if(broken)throw Error();return data.get(k)||null;},setItem:(k,v)=>{if(broken)throw Error();data.set(k,v);},removeItem:k=>data.delete(k)};const context={window,location,sessionStorage:storage,URLSearchParams,Date:{now:()=>now},fetch:(url,o)=>{sent.push({url,...o,body:JSON.parse(o.body)});return Promise.resolve();},document:{readyState:'complete',querySelector:()=>null,addEventListener:(n,f)=>events[n]=f,createElement:()=>({setAttribute(){}}),head:{appendChild:x=>beacons.push(x)}}};vm.runInNewContext(source,context);return {sent,beacons,data,context,navigate:(path,search='')=>{location.pathname=path;location.search=search;events['xiaoq:pageview']?.();},tick:ms=>now+=ms,rerun:()=>vm.runInNewContext(source,context)};}
test('production page counts once; no private URL or cookies sent',()=>{const t=setup({search:'?secret=never-send#fragment'});assert.equal(t.sent.length,1);assert.deepEqual(t.sent[0].body,{path:'/',visitStart:true});assert.equal(t.sent[0].credentials,'omit');assert.equal(t.sent[0].referrerPolicy,'no-referrer');assert.equal(t.sent[0].keepalive,true);t.rerun();assert.equal(t.sent.length,1);});
test('successful route +1; same-path language/hash/view saves do not count',()=>{const t=setup();t.navigate('/about/');assert.equal(t.sent.length,2);assert.equal(t.sent[1].body.visitStart,false);t.navigate('/about/','?lang=en#heading');assert.equal(t.sent.length,2);t.navigate('/');assert.equal(t.sent.length,3);t.tick(31*60*1000);t.navigate('/games/');assert.equal(t.sent.at(-1).body.visitStart,true);});
test('test opt-out suppresses current and later PV plus old beacon',()=>{const t=setup({search:'?stats=off'});assert.equal(t.sent.length,0);assert.equal(t.beacons.length,0);t.navigate('/about/');assert.equal(t.sent.length,0);});
test('global disable, nonproduction and embedded pages never send',()=>{for(const options of [{disabled:true},{host:'127.0.0.1',protocol:'http:'},{embedded:true}])assert.equal(setup(options).sent.length,0);});
test('blocked storage still counts PV but marks visit coverage unknown',()=>{const t=setup({broken:true});assert.equal(t.sent.length,1);assert.equal(t.sent[0].body.visitStart,null);t.navigate('/about/');assert.equal(t.sent[1].body.visitStart,null);});
test('index.html normalization and explicit off survive storage failure',()=>{const t=setup();t.navigate('/index.html');assert.equal(t.sent.length,1);const off=setup({search:'?stats=off',broken:true});off.navigate('/about/');assert.equal(off.sent.length,0);});
test('router signal exists only at successful render commit, not saveView',()=>{const router=fs.readFileSync(new URL('../../assets/site-router.js',import.meta.url),'utf8');assert.equal((router.match(/new CustomEvent\('xiaoq:pageview'\)/g)||[]).length,1);assert.match(router,/renderRoute\(info\);restoreView\(url,targetView,navigationId\);window.dispatchEvent\(new CustomEvent\('xiaoq:pageview'\)\)/);});
