import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{createHash}from'node:crypto';
import{load,plan,apply,verify,permitted,matchesBefore,assertScope,sha}from'../../scripts/platform/delivery/lib/install.mjs';
import{zip,crc32}from'../../scripts/platform/zip.mjs';import{inspectZip}from'../../scripts/publication/archives.mjs';
const put=(root,p,b)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),b);};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'q-delivery-')),root=path.join(dir,'repo'),bundle=path.join(dir,'bundle');t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(root);fs.mkdirSync(bundle);put(root,'original.html','unchanged');put(root,'content/old.json','old');const files=[{path:'content/old.json',before:sha(Buffer.from('old')),sha256:sha(Buffer.from('new'))},{path:'content/new.json',before:null,sha256:sha(Buffer.from('added'))}];for(const[f,b]of[['content/old.json','new'],['content/new.json','added']])put(bundle,'payload/'+f,b);const m={schemaVersion:2,edition:'SITE-PLATFORM-R45',repository:'Aha-xiaoQ/Aha-xiaoQ.github.io',branch:'main',baselineCommit:'a'.repeat(40),message:'test: isolated fixture',migrationPaths:[],files,protected:[{path:'original.html',sha256:sha(Buffer.from('unchanged'))}]};put(bundle,'manifest.json',JSON.stringify(m));return{root,bundle,m,save:()=>put(bundle,'manifest.json',JSON.stringify(m))};}
test('preflight never writes; apply is repeat-safe and preserves originals',t=>{const f=fixture(t),m=load(f.bundle),changes=plan(f.root,f.bundle,m);assert.equal(fs.readFileSync(f.root+'/content/old.json','utf8'),'old');assert.equal(changes.length,2);assert.equal(apply(f.root,changes),2);verify(f.root,m,f.bundle);assert.equal(plan(f.root,f.bundle,m).length,0);});
test('late conflict stops all earlier changes',t=>{const f=fixture(t);put(f.root,'content/new.json','mine');assert.throws(()=>plan(f.root,f.bundle,load(f.bundle)),/conflicts/);assert.equal(fs.readFileSync(f.root+'/content/old.json','utf8'),'old');});
test('change between plan and apply stops transaction',t=>{const f=fixture(t),changes=plan(f.root,f.bundle,load(f.bundle));put(f.root,'content/old.json','mine');assert.throws(()=>apply(f.root,changes),/after preflight/);assert.equal(fs.existsSync(f.root+'/content/new.json'),false);});
test('corrupt payload fails before writes',t=>{const f=fixture(t);put(f.bundle,'payload/content/new.json','bad');assert.throws(()=>load(f.bundle),/Damaged/);});
test('exact deletion has an old identity and no executable payload',t=>{const f=fixture(t);f.m.files[0].operation='delete';f.m.files[0].sha256=null;fs.unlinkSync(f.bundle+'/payload/content/old.json');f.save();const m=load(f.bundle);apply(f.root,plan(f.root,f.bundle,m));assert.equal(fs.existsSync(f.root+'/content/old.json'),false);verify(f.root,m,f.bundle);assert.equal(plan(f.root,f.bundle,m).length,0);});
test('original mismatch stops application',t=>{const f=fixture(t);put(f.root,'original.html','changed');assert.throws(()=>plan(f.root,f.bundle,load(f.bundle)),/Original artifact differs/);});
test('case collisions and absent baseline identity fail closed',t=>{for(const mutate of[m=>m.files.push({...m.files[0],path:'content/OLD.json'}),m=>delete m.files[0].before]){const f=fixture(t);mutate(f.m);f.save();assert.throws(()=>load(f.bundle));}});
test('Git blob baseline verifies actual bytes, not a filename or text conversion',()=>{const b=Buffer.from('original\n'),id='git:'+createHash('sha1').update('blob '+b.length+'\0').update(b).digest('hex');assert.ok(matchesBefore(id,b));assert.ok(!matchesBefore(id,Buffer.from('original\r\n')));assert.ok(!matchesBefore(id,null));});
for(const p of['assets/fonts/a.woff2','games/a/play.html','packages/a/index.js','downloads/a.zip','.github/workflows/a.yml','../outside','config/secrets.json','a/CON.txt'])test('out-of-scope target blocked '+p,()=>assert.throws(()=>permitted(p)));
test('unknown staged files cannot ride along with an update',t=>{const f=fixture(t);assert.throws(()=>assertScope(['unrelated.json'],f.m),/Unexpected/);assert.doesNotThrow(()=>assertScope(['notes/lab/docs/new/index.html','assets/journal/data/guides/a.json'],f.m));});
test('ZIP has deterministic valid CRC and UTF-8 filenames',()=>{const rows=[['包/说明.md',Buffer.from('中文')],['包/.gitignore',Buffer.from('temp/')],['包/a.txt',Buffer.from('a')]],b=zip(rows),i=inspectZip(b);assert.ok(b.equals(zip([...rows].reverse())));assert.equal(i.entries,3);assert.ok(i.names.includes('包/说明.md'));assert.equal(crc32(Buffer.from('123456789')),0xcbf43926);});
test('ZIP refuses traversal and case collisions',()=>{for(const rows of[[['../x',Buffer.from('x')]],[['a',Buffer.from('x')],['A',Buffer.from('y')]]])assert.throws(()=>zip(rows));});
