import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {failureSummary,readFailureDetails} from '../../scripts/platform/failure-summary.mjs';
const report=()=>({ok:false,startedAt:'2026-09-24T15:55:29.608Z',finishedAt:'2026-09-24T15:59:55.359Z',phases:[{phase:'verify',ok:false,results:[{id:'publication-check',status:'passed',code:0},{id:'browser-artifact',status:'failed',code:1,log:'runs/14-browser-artifact.log'}]}],pushed:false,approved:false});
const browser=()=>({ok:false,startedAt:'2026-09-24T15:58:52.347Z',finishedAt:'2026-09-24T15:59:54.469Z',errors:[1440,390,320].map(width=>({page:'404.html',language:'en',width,problem:'untranslated-placeholder',samples:['作品名称或关键词']}))});
test('summary names the actual failing gate, page, language, width and source value',()=>{const r=report(),before=structuredClone(r),s=failureSummary(r,{'browser-artifact':browser()}).join('\n');for(const value of ['browser-artifact','404.html','en','1440px','390px','320px','作品名称或关键词','14-browser-artifact.log'])assert.ok(s.includes(value),value);assert.deepEqual(r,before);assert.ok(s.split('\n').length<20);});
test('a passed pipeline never produces a failure summary',()=>assert.deepEqual(failureSummary({...report(),ok:true}),[]));
test('flow-level errors and dependency blocks remain failures rather than inferred success',()=>{const r=report();r.error='Workspace sources changed during verification';r.phases[0].results.push({id:'other',status:'blocked'});const s=failureSummary(r).join('\n');assert.match(s,/sources changed/);assert.match(s,/1 项检查/);assert.equal(r.ok,false);});
test('summary is bounded and strips terminal control codes in diagnostic values',()=>{const b=browser();b.errors=Array.from({length:80},()=>({page:'404.html\nINJECTED',problem:'bad\u001b[31m',detail:'x'.repeat(500)}));const lines=failureSummary(report(),{'browser-artifact':b});assert.ok(lines.length<20);assert.ok(lines.every(s=>!/[\r\n\x1b]/.test(s)));assert.ok(lines.some(s=>s.includes('74')));});
function workspace(t){const r=fs.mkdtempSync(path.join(os.tmpdir(),'q-summary-'));t.after(()=>fs.rmSync(r,{recursive:true,force:true}));fs.mkdirSync(r+'/.local/platform',{recursive:true});return r;}
test('only a failed browser gate reads a same-run unsuccessful browser report',t=>{const r=workspace(t);fs.writeFileSync(r+'/.local/platform/browser-report.json',JSON.stringify(browser()));assert.equal(readFailureDetails(r,report())['browser-artifact'].errors.length,3);const p=report();p.phases[0].results[1].status='blocked';assert.deepEqual(readFailureDetails(r,p),{});});
for(const [name,patch]of [['old',{finishedAt:'2026-09-23T15:59:54Z'}],['future',{finishedAt:'2026-09-25T15:59:54Z'}],['successful',{ok:true}],['invalid-date',{finishedAt:'invalid'}]])test('ignores '+name+' browser report instead of citing it as current failure',t=>{const r=workspace(t);fs.writeFileSync(r+'/.local/platform/browser-report.json',JSON.stringify({...browser(),...patch}));assert.deepEqual(readFailureDetails(r,report()),{});});
test('missing or invalid report does not hide the failed-step log or throw',t=>{const r=workspace(t);assert.deepEqual(readFailureDetails(r,report()),{});fs.writeFileSync(r+'/.local/platform/browser-report.json','bad json');assert.deepEqual(readFailureDetails(r,report()),{});assert.match(failureSummary(report()).join('\n'),/14-browser-artifact.log/);});
