import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import {spawnSync}from'node:child_process';import {fileURLToPath}from'node:url';
import {fixture}from'./helpers/font-fixture.mjs';import {buildFontSupport,RECORD,generatedFont}from'../../scripts/platform/font-support.mjs';
import {planPackage}from'../../scripts/platform/pack.mjs';import {sourceFingerprint}from'../../scripts/platform/source-identity.mjs';import{stageAndCheck}from'../../scripts/platform/delivery/lib/git-stage.mjs';
const ACTUAL=fileURLToPath(new URL('../../',import.meta.url));
function prepare(t){const f=fixture(t);f.write('.gitignore','.local/\n');f.write('original.html','protected');f.write('README.md','before\n');const c=JSON.parse(fs.readFileSync(ACTUAL+'config/site-platform.json'));c.protectedArtifacts=['original.html'];f.write('config/site-platform.json',JSON.stringify(c));fs.cpSync(ACTUAL+'scripts/platform/delivery',f.root+'/scripts/platform/delivery',{recursive:true});const config=f.root+'/../isolated-'+path.basename(f.root)+'.gitconfig';fs.writeFileSync(config,'');t.after(()=>fs.rmSync(config,{force:true}));const env={...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:config};const g=args=>{const r=spawnSync('git',args,{cwd:f.root,encoding:'utf8',shell:false,env});assert.equal(r.status,0,r.stderr);return r.stdout;};g(['init','-b','main']);g(['config','user.name','Fixture']);g(['config','user.email','fixture@example.invalid']);g(['add','.']);g(['commit','-m','baseline']);return{...f,g,base:g(['rev-parse','HEAD']).trim()};}
const opts=f=>({provider:f.provider,pin:f.pin,primary:f.primary,corpus:f.corpus,fetcher:f.fetcher});
test('future delta packaging excludes generated font bytes while retaining authored fixes',async t=>{const f=prepare(t);await buildFontSupport(f.root,opts(f));f.write('README.md','after\n');f.write('.local/platform/latest.json',JSON.stringify({mode:'verify',ok:true,protectedArtifactsUnchanged:true,phases:[{phase:'verify',ok:true}],sourceFingerprint:sourceFingerprint(f.root),scope:'Synthetic evidence for pack authorization unit test only'}));const p=planPackage(f.root,{base:f.base});assert.deepEqual(p.manifest.files.map(f=>f.path),['README.md']);assert.ok(p.entries.every(([p])=>!/\.(?:woff2?|ttf|otf|ttc)$/i.test(p)));});
test('real Git stages only the verified generated typography closure with unchanged whitespace checks',async t=>{const f=prepare(t);await buildFontSupport(f.root,opts(f));const r=JSON.parse(fs.readFileSync(f.root+'/'+RECORD));const paths=[...Object.keys(r.files),RECORD];const m={files:[],protected:[{path:'original.html'}]};fs.mkdirSync(f.root+'/.local',{recursive:true});const staged=await stageAndCheck(async args=>({stdout:f.g(args)}),paths,m,{repositoryRoot:f.root,pathspecFile:f.root+'/.local/pathspec.txt',logFile:f.root+'/.local/git.log'});assert.ok(staged.some(generatedFont));assert.equal(f.g(['diff','--cached','--check']),'');assert.equal(f.g(['rev-parse','HEAD']).trim(),f.base);});
test('tampered generated font stops real staging before a git add call',async t=>{const f=prepare(t);await buildFontSupport(f.root,opts(f));const r=JSON.parse(fs.readFileSync(f.root+'/'+RECORD));f.write(r.faces[0].file,'wOF2tampered');let calls=0;await assert.rejects(stageAndCheck(async()=>{calls++;return{stdout:''};},[r.faces[0].file],{files:[],protected:[]},{repositoryRoot:f.root,pathspecFile:f.root+'/.local/pathspec.txt'}),/mismatch/);assert.equal(calls,0);});
