import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';
import{validateMessages,planContent,build}from'../../scripts/platform/content.mjs';
const root=new URL('../../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root));
test('current bilingual source compiles deterministically without mutating source',()=>{const a=planContent(),b=planContent();assert.deepEqual([...a.files],[...b.files]);assert.ok(a.messages>300);const s=a.files.get('assets/i18n/messages.js').toString();assert.ok(s.includes('SITE_LOCALE_MESSAGES'));assert.ok(!s.includes('SITE_EN ='));});
test('duplicate IDs and conflicting source translations are errors',()=>{const item={id:'one',source:'测试',text:'Test'};for(const extra of [{...item},{id:'two',source:'测试',text:'Other'}])assert.throws(()=>validateMessages({schemaVersion:1,language:'en',messages:[item,extra]}));});
for(const value of ['__proto__','prototype','constructor'])test('prototype key is refused '+value,()=>assert.throws(()=>validateMessages({schemaVersion:1,language:'en',messages:[{id:'one',source:value,text:'x'}]})));
test('generation uses data, keeps originals intact, and stale checks never write',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'q-locale-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));for(const p of ['config/site-platform.json','content/locales/en.json']){fs.mkdirSync(path.dirname(dir+'/'+p),{recursive:true});fs.writeFileSync(dir+'/'+p,read(p));}const before=fs.readFileSync(dir+'/content/locales/en.json');assert.throws(()=>build(dir,{check:true}));assert.ok(!fs.existsSync(dir+'/assets'));build(dir);assert.equal(build(dir,{check:true}).changed,0);assert.deepEqual(fs.readFileSync(dir+'/content/locales/en.json'),before);fs.appendFileSync(dir+'/assets/i18n/messages.js','broken');assert.throws(()=>build(dir,{check:true}));});
test('messages cannot inject a script end tag into the generated dictionary',()=>{const source={schemaVersion:1,language:'en',messages:[{id:'one',source:'原文',text:'</script><img onerror=x>'}]},plan=planContent(undefined,{reader:p=>p==='content/locales/en.json'?Buffer.from(JSON.stringify(source)):read(p)});assert.ok(!plan.files.get('assets/i18n/messages.js').toString().includes('</script>'));});

test('named message values cannot disappear or change between languages',()=>{assert.throws(()=>validateMessages({schemaVersion:1,language:'en',messages:[{id:'status.loading',source:'载入 {name}',text:'Loading {other}'}]}),/parameter mismatch/);});
