import test,{after}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{spawnSync}from'node:child_process';
import{sourceFingerprint,sourceFiles}from'../../scripts/platform/source-identity.mjs';import{planPackage,writePackage}from'../../scripts/platform/pack.mjs';import{load,plan,apply,verify}from'../../scripts/platform/delivery/lib/install.mjs';import{runPipeline}from'../../scripts/platform/cli.mjs';import{inspectZip}from'../../scripts/publication/archives.mjs';
const actual=fileURLToPath(new URL('../../',import.meta.url));const put=(root,p,b)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,b);};
const gitConfigDir=fs.mkdtempSync(path.join(os.tmpdir(),'q-pack-git-config-')),gitConfig=gitConfigDir+'/isolated.gitconfig';fs.writeFileSync(gitConfig,'');after(()=>fs.rmSync(gitConfigDir,{recursive:true,force:true}));
function g(root,args){const r=spawnSync('git',args,{cwd:root,encoding:'utf8',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:gitConfig},shell:false});assert.equal(r.status,0,r.stderr);return r.stdout.trim();}
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'q-pack-')),root=dir+'/source';t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(root);g(root,['init','-b','main']);g(root,['config','user.name','Fixture']);g(root,['config','user.email','fixture@example.invalid']);put(root,'.gitignore','.local/\n');put(root,'original.html','original artifact');put(root,'docs/guide.md','before\n');const config=JSON.parse(fs.readFileSync(actual+'config/site-platform.json'));config.protectedArtifacts=['original.html'];put(root,'config/site-platform.json',JSON.stringify(config));fs.cpSync(actual+'scripts/platform/delivery',root+'/scripts/platform/delivery',{recursive:true});g(root,['add','.']);g(root,['commit','-m','fixture baseline']);const base=g(root,['rev-parse','HEAD']);const save=()=>put(root,'.local/platform/latest.json',JSON.stringify({schemaVersion:1,mode:'verify',ok:true,protectedArtifactsUnchanged:true,phases:[{phase:'verify',ok:true}],sourceFingerprint:sourceFingerprint(root),finishedAt:new Date().toISOString(),scope:'Synthetic saved report for pack unit testing only'}));return{dir,root,base,save,config};}
test('read-only Git fingerprint includes tracked deletions and nonignored new sources',t=>{const f=fixture(t),a=sourceFingerprint(f.root);put(f.root,'docs/new.md','new');assert.notEqual(sourceFingerprint(f.root).sha256,a.sha256);assert.ok(sourceFiles(f.root).includes('docs/new.md'));fs.unlinkSync(f.root+'/docs/new.md');fs.unlinkSync(f.root+'/docs/guide.md');assert.notEqual(sourceFingerprint(f.root).sha256,a.sha256);assert.ok(sourceFiles(f.root).includes('docs/guide.md'));});
test('private reports do not invalidate their own source fingerprint',t=>{const f=fixture(t),a=sourceFingerprint(f.root);f.save();assert.deepEqual(sourceFingerprint(f.root),a);});
test('future tested delta packages writes/deletions and installs onto its actual Git baseline',t=>{const f=fixture(t);fs.unlinkSync(f.root+'/docs/guide.md');put(f.root,'docs/new.md','after\n');f.save();const p=planPackage(f.root,{base:f.base});assert.deepEqual(p.manifest.files.map(x=>[x.path,x.operation]),[['docs/guide.md','delete'],['docs/new.md','write']]);const bundle=f.dir+'/bundle';fs.mkdirSync(bundle);for(const[file,b]of p.entries)put(bundle,file,b);const target=f.dir+'/target';g(f.dir,['clone','--no-hardlinks',f.root,target]);const m=load(bundle);apply(target,plan(target,bundle,m));verify(target,m,bundle);assert.equal(fs.existsSync(target+'/docs/guide.md'),false);assert.equal(fs.readFileSync(target+'/docs/new.md','utf8'),'after\n');assert.equal(g(target,['rev-parse','HEAD']),f.base);});
test('stale or missing successful verification cannot authorize a package',t=>{const f=fixture(t);put(f.root,'docs/guide.md','changed');assert.throws(()=>planPackage(f.root,{base:f.base}));f.save();put(f.root,'docs/new.md','later');assert.throws(()=>planPackage(f.root,{base:f.base}),/changed after verification/);});
test('protected original changes are not hidden by a synthetic successful report',t=>{const f=fixture(t);put(f.root,'original.html','changed');f.save();assert.throws(()=>planPackage(f.root,{base:f.base}),/Original artifact/);});
test('font bytes never enter a website update ZIP even with an otherwise valid report',t=>{const f=fixture(t);put(f.root,'assets/fonts/sample.woff2','fake');f.save();assert.throws(()=>planPackage(f.root,{base:f.base}),/Outside website/);});
test('generated records are excluded while authored source changes are retained',t=>{const f=fixture(t);put(f.root,'docs/platform/generated-files.json',JSON.stringify({files:{'generated-page.html':'a'}}));put(f.root,'generated-page.html','generated');put(f.root,'docs/guide.md','changed');f.save();const p=planPackage(f.root,{base:f.base});assert.deepEqual(p.manifest.files.map(x=>x.path),['docs/guide.md']);});
test('archive is deterministic, inspectable, outside repository and refuses overwrite',t=>{const f=fixture(t);put(f.root,'docs/guide.md','changed');f.save();const output=f.dir+'/update.zip',r=writePackage(f.root,{base:f.base,output});assert.equal(r.pushed,false);assert.ok(inspectZip(fs.readFileSync(output)).names.includes('XiaoQ_Site_Update/payload/docs/guide.md'));assert.throws(()=>writePackage(f.root,{base:f.base,output}),/already exists/);assert.throws(()=>writePackage(f.root,{base:f.base,output:f.root+'/inside.zip'}),/outside/);});
test('pipeline plan never invokes a command or requires protected files to be opened',async t=>{const f=fixture(t);fs.unlinkSync(f.root+'/original.html');const r=await runPipeline(f.root,'plan',{execute:()=>{throw Error('not called');}});assert.equal(r.remoteOperations,false);});
test('pipeline collects independent failures and blocks publication/browser dependents',async t=>{const f=fixture(t),ran=[];const r=await runPipeline(f.root,'verify',{save:false,execute:async step=>{ran.push(step.id);return{code:step.id==='source-tests'?1:0};}});assert.equal(r.ok,false);assert.ok(ran.includes('publication-plan'));assert.ok(ran.includes('font-coverage'));assert.ok(!ran.includes('publication-build'));assert.ok(!ran.includes('browser-artifact'));assert.equal(r.pushed,false);assert.equal(r.approved,false);});
test('pipeline cannot pass when a verification step silently edits a source',async t=>{const f=fixture(t);const r=await runPipeline(f.root,'verify',{save:false,execute:async step=>{if(step.id==='source-tests')put(f.root,'docs/guide.md','unexpected');return{code:0};}});assert.equal(r.ok,false);assert.match(r.error,/sources changed/);});
test('build cannot pass after changing a protected artifact',async t=>{const f=fixture(t);const r=await runPipeline(f.root,'build',{save:false,execute:async()=>{put(f.root,'original.html','bad');return{code:0};}});assert.equal(r.ok,false);assert.match(r.error,/Protected original changed/);});

test('repository launch templates use LF; Windows delivery uses CRLF with PowerShell BOM retained',t=>{const f=fixture(t);put(f.root,'docs/guide.md','changed');f.save();const p=planPackage(f.root,{base:f.base});for(const [name,bytes] of p.entries.filter(([name])=>/\.(?:cmd|ps1)$/.test(name))){assert.doesNotMatch(fs.readFileSync(f.root+'/scripts/platform/delivery/'+name,'utf8'),/\r/);assert.match(bytes.toString('utf8'),/\r\n/);assert.doesNotMatch(bytes.toString('utf8'),/(?<!\r)\n/);if(name.endsWith('.ps1'))assert.equal(bytes.toString('utf8')[0],'\ufeff');}});
