import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import{fileURLToPath}from'node:url';
import {checkSourcePlayback}from'../../scripts/platform/source-playback.mjs';import {zip}from'../../scripts/platform/zip.mjs';import {inspectZip}from'../../scripts/publication/archives.mjs';
const ROOT=fileURLToPath(new URL('../../',import.meta.url));
function mock(edit=()=>{}){
 const html=Buffer.from('<!doctype html><html lang="zh"><head><title>Film</title></head><body><video poster="poster.jpg"><source src="final.mp4"></video></body></html>');
 const source=new Map([['Film/index.html',html],['Film/player.template.html',html],['Film/final.mp4',Buffer.from('fixture-film')],['Film/poster.jpg',Buffer.from('fixture-poster')],['Film/PLAY.cmd',Buffer.from('@echo off')]]);
 const cfg={schemaVersion:1,archives:[{path:'experiments/releases/movie/source-r49.zip',root:'Film',entry:'index.html',members:{'index.html':'experiments/releases/movie/index.html','final.mp4':'experiments/releases/movie/final.mp4','poster.jpg':'experiments/releases/movie/poster.jpg'},required:['PLAY.cmd','player.template.html']}]};
 const files=new Map([...Object.entries(cfg.archives[0].members)].map(([member,p])=>[p,source.get('Film/'+member)]));
 edit(source,files,cfg);files.set(cfg.archives[0].path,zip([...source]));return{reader:p=>files.get(p)||null,configuration:cfg};
}
test('the actual downloadable R49 ZIP has all playback companions and byte-identical final film',()=>{const r=checkSourcePlayback(ROOT);assert.equal(r.length,1);assert.equal(r[0].companionIdentities,'matched');assert.ok(r[0].files>=27);});
test('the previous source ZIP reproduces the absent index.html problem',()=>{const c=JSON.parse(fs.readFileSync(ROOT+'config/lab-source-playback.json'));c.archives[0].path='experiments/releases/mid-autumn-special/source.zip';assert.throws(()=>checkSourcePlayback(ROOT,{configuration:c}),/index.html/);});
test('a self-contained synthetic source player passes its declared companion contract',()=>assert.equal(checkSourcePlayback('',mock())[0].files,5));
for(const member of['index.html','final.mp4','poster.jpg','player.template.html','PLAY.cmd'])test('missing source companion is rejected: '+member,()=>assert.throws(()=>checkSourcePlayback('',mock(s=>s.delete('Film/'+member))),/absent|different/));
for(const member of['index.html','final.mp4','poster.jpg'])test('different bytes cannot masquerade as the final source companion: '+member,()=>assert.throws(()=>checkSourcePlayback('',mock(s=>s.set('Film/'+member,Buffer.from('changed')))),/different/));
test('a valid ZIP with an unresolved media path is still rejected',()=>assert.throws(()=>checkSourcePlayback('',mock((s,f)=>{const h=Buffer.from('<video src="lost.mp4"></video>');s.set('Film/index.html',h);s.set('Film/player.template.html',h);f.set('experiments/releases/movie/index.html',h);})),/broken relative/));
for(const src of['https://outside.invalid/movie.mp4','/final.mp4','../final.mp4','file:///final.mp4'])test('offline source player cannot require an external or escaping video: '+src,()=>assert.throws(()=>checkSourcePlayback('',mock((s,f)=>{const h=Buffer.from('<video src="'+src+'"></video>');s.set('Film/index.html',h);s.set('Film/player.template.html',h);f.set('experiments/releases/movie/index.html',h);}))));
test('a mismatched rebuild template is not accepted as a standalone player',()=>assert.throws(()=>checkSourcePlayback('',mock(s=>s.set('Film/player.template.html',Buffer.from('different')))),/template differ/));
test('downloadable source archive cannot include fonts',()=>assert.throws(()=>checkSourcePlayback('',mock(s=>s.set('Film/font.woff2',Buffer.from('font')))),/Unsafe/));
test('case-colliding companion names fail in the ZIP reader on every platform',()=>{const o=mock(s=>s.set('Film/other.mp4',Buffer.from('case'))),reader=o.reader,target=o.configuration.archives[0].path;const data=Buffer.from(reader(target));for(let at=data.indexOf('other.mp4');at>=0;at=data.indexOf('other.mp4',at+1))data.write('FINAL.mp4',at);o.reader=p=>p===target?data:reader(p);assert.throws(()=>checkSourcePlayback('',o),/case/);});
test('real source archive preserves uploaded final soundtrack and no fonts or dependency caches',()=>{const p=JSON.parse(fs.readFileSync(ROOT+'content/experiments/mid-autumn-special.json')).resources.find(r=>r.role==='source').href.slice(1);const z=inspectZip(fs.readFileSync(ROOT+p));assert.equal(z.hashes['MidAutumn_Final_Source/final.mp4'],'be887d2ca180e2e0b7849d816075b03dc19347eb0b25e627111422d8d00a6da1');assert.ok(z.names.every(p=>!/\.(?:ttf|ttc|otf|woff2?|pyc)$|__pycache__|node_modules/.test(p)));});
