#!/usr/bin/env node
/** R25. Explicit About source, generated public view, safe first migration. */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {safe, readOptional, writeAtomic} from '../lib/safe-path.mjs';
import {matchesTextHash, equalText} from '../lib/text-records.mjs';
import {wireHTML} from '../workshop/build.mjs';
export const ROOT=fileURLToPath(new URL('../../',import.meta.url));
export const RECORD='docs/showcase-r25/generated-files.json';
export const CONFIG='content/about-view.json';
const sha=b=>createHash('sha256').update(b).digest('hex');
const json=o=>Buffer.from(JSON.stringify(o,null,2)+'\n');
const unesc=s=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const plain=s=>unesc(s.replace(/<[^>]*>/g,'')).replace(/[↗→]/g,'').replace(/\s+/g,' ').trim();
const attr=(s,k)=>{const m=s.match(new RegExp('\\b'+k+'=["\\\']([^"\\\']*)["\\\']','i'));return m?unesc(m[1]):'';};
export function validateConfig(c) {
  if(c?.schemaVersion!==1 || typeof c.avatar?.src!=='string' || typeof c.avatar?.alt!=='string')throw Error('about-view.json 格式无效');
  for(const u of [c.avatar.src,c.guestbookHref])if(typeof u!=='string'||!u.startsWith('/')||u.startsWith('//')||/[\\\x00-\x20<>"'`]/.test(u)||/%(?:2e|2f|5c)/i.test(u)||u.split(/[?#]/)[0].split('/').some(p=>p==='.'||p==='..'))throw Error('关于页资源必须是有效站内地址');
  for(const h of [c.beforeHtml,c.afterHtml])if(typeof h!=='string'||/<(?:main|script|style|base|iframe)\b|\bon\w+\s*=|(?:javascript|data):/i.test(h))throw Error('关于页附加内容含需人工合并的活动内容');
  return c;
}
export function migrateLegacy(html,profile) {
  const matches=[...html.matchAll(/<main\b[^>]*>[\s\S]*?<\/main>/gi)];
  if(matches.length!==1)throw Error('关于页 main 边界不唯一');
  const main=matches[0][0],inner=main.replace(/^<main\b[^>]*>/i,'').replace(/<\/main>$/i,'');
  const old=inner.match(/<section class="section"><div class="shell article about-intro">(<img\b[^>]*>)(<div class="about-contact">[\s\S]*?)<\/div><\/div><\/section>/);
  if(!old)throw Error('关于页已定制，不能覆盖：请先合并 content/about-view.json');
  const contact=old[2],head=contact.match(/<h2>([\s\S]*?)<\/h2>/),intro=contact.match(/<p>([\s\S]*?)<\/p>/);
  if(plain(head?.[1]||'')!=='欢迎关注'||plain(intro?.[1]||'')!=='分享做项目、做工具和做游戏的日常。')throw Error('关于页介绍已有手工修改，请先合并');
  const links=[...contact.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/g)];
  const book=links.find(m=>/\bdata-guestbook-link\b/.test(m[1]));
  if(!book||plain(book[2])!=='留言墙 · 留一句话')throw Error('留言入口已定制，请先合并');
  const social=links.filter(m=>m!==book).map(m=>({label:plain(m[2]),url:attr(m[1],'href')}));
  const wanted=(profile.links||[]).map(l=>({label:l.label,url:l.url}));
  if(JSON.stringify(social)!==JSON.stringify(wanted))throw Error('关于页与 profile 联系地址不同，请先核对；不覆盖联系方式');
  const rest=contact.replace(/<h2>[\s\S]*?<\/h2>/,'').replace(/<p>[\s\S]*?<\/p>/,'').replace(/<a\b[^>]*>[\s\S]*?<\/a>/g,'');
  if(plain(rest))throw Error('关于页联系区有额外文字，请先合并');
  const src=attr(old[1],'src'),alt=attr(old[1],'alt');
  if(!/^(?:\.\.\/|\/)assets\/identity\/xiaoq-avatar-p63a\.svg(?:\?[^\s]*)?$/.test(src))throw Error('关于页头像已有修改，请先合并并确认');
  const c={schemaVersion:1,avatar:{src:src.replace(/^\.\.\//,'/'),alt},guestbookHref:attr(book[1],'href'),beforeHtml:inner.slice(0,old.index),afterHtml:inner.slice(old.index+old[0].length)};
  return validateConfig(c);
}
export async function planShowcase(root=ROOT,{reader=p=>readOptional(root,p),initialize=false}={}) {
  const get=async p=>{safe(root,p);const b=await reader(p);if(!b)throw Error('缺少界面输入：'+p);return b;};
  const context=vm.createContext({URL});
  for(const p of ['content/site-data.js','assets/ui/site-actions.js','assets/ui/site-showcase.js'])new vm.Script((await get(p)).toString(),{filename:p}).runInContext(context,{timeout:1000});
  const profile=context.SITE_DATA?.profile;if(!profile)throw Error('缺少公开 profile');
  const html=(await get('about/index.html')).toString();
  let config=await reader(CONFIG),created=false;
  if(config)config=validateConfig(JSON.parse(config));
  else {if(!initialize)throw Error('需先由 R25 安装器迁移关于页');config=migrateLegacy(html,profile);created=true;}
  if((html.match(/<main\b/g)||[]).length!==1)throw Error('关于页 main 边界不唯一');
  const body=context.SITE_SHOWCASE.aboutMain(profile,'../',config),files=new Map();
  let next=html.replace(/<main\b[\s\S]*?<\/main>/i,body).replace(/data-prerendered="[^"]*"/,'data-prerendered="true"');
  next=wireHTML(next);
  files.set('about/index.html',Buffer.from(next));
  const content=JSON.stringify(config).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  files.set('content/about-support.js',Buffer.from('// Generated by showcase:build; edit content/about-view.json.\nglobalThis.SITE_ABOUT_SUPPORT = Object.freeze('+content+');\n'));
  return{files,config:json(config),created};
}
export async function build(root=ROOT,{check=false}={}) {
  const {files}=await planShowcase(root),prior=JSON.parse(readOptional(root,RECORD)||'{"files":{}}'),changes=[];
  for(const [p,b]of files){const old=readOptional(root,p);if(old&&(!prior.files[p]||!matchesTextHash(old,prior.files[p])))throw Error('关于页生成文件有手工修改：'+p);if(!equalText(old,b))changes.push({p,b,old});}
  const record=json({schemaVersion:1,version:'showcase-r25',files:Object.fromEntries([...files].map(([p,b])=>[p,sha(b)]))});
  if(!equalText(readOptional(root,RECORD),record))changes.push({p:RECORD,b:record,old:readOptional(root,RECORD)});
  if(check&&changes.length)throw Error('关于页尚未构建：npm run showcase:build');
  if(!check){for(const c of changes){const old=readOptional(root,c.p);if((old?sha(old):null)!==(c.old?sha(c.old):null))throw Error('构建期间文件已修改：'+c.p);}
    const done=[];try{for(const c of changes){writeAtomic(root,c.p,c.b);done.push(c);}}catch(e){for(const c of done.reverse()){const b=readOptional(root,c.p);if(b&&!b.equals(c.b))continue;if(c.old)writeAtomic(root,c.p,c.old);else fs.unlinkSync(safe(root,c.p));}throw e;}}
  return{changed:changes.length,files:files.size};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const args=process.argv.slice(2);if(args.some(x=>x!=='--check')){console.error('未知参数');process.exitCode=1;}else build(ROOT,{check:args.includes('--check')}).then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(e.message);process.exitCode=1;});
}
