import test from'node:test';import assert from'node:assert/strict';import{cp,mkdtemp,rm,readFile,writeFile,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import{fileURLToPath}from'node:url';import path from'node:path';
import{build,planPages,sha}from'../../scripts/journal/build.mjs';import{addProject}from'../../scripts/journal/add-project.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
async function temp(fn){const dst=await mkdtemp(path.join(tmpdir(),'journal-r04-test-'));try{for(const p of ['content','assets/journal','scripts/journal','docs/development','notes'])await cp(path.join(root,p),path.join(dst,p),{recursive:true});const record=JSON.parse(await readFile(path.join(root,'docs/development/STATE_SOURCES.json'),'utf8'));await mkdir(path.dirname(path.join(dst,record.source)),{recursive:true});await cp(path.join(root,record.source),path.join(dst,record.source));return await fn(dst);}finally{await rm(dst,{recursive:true,force:true});}}
test('generated pages are reproducible without source edits',()=>temp(async root=>{await build(root);const second=await build(root,{check:true});assert.equal(second.changed,0);}));
test('new draft does not create public routes',()=>temp(async root=>{await addProject(root,{id:'third-fixture',title:'仅测试项目',category:'tool'});const {pages}=await planPages(root);assert.ok(!pages.has('notes/third-fixture/index.html'));}));
test('publish third project only by data, then archive and withdraw',()=>temp(async root=>{await addProject(root,{id:'third-fixture',title:'仅测试项目',category:'tool'});const file=path.join(root,'content/development/projects/third-fixture.json'),p=JSON.parse(await readFile(file,'utf8'));p.visibility='public';await writeFile(file,JSON.stringify(p));await build(root);assert.ok((await readFile(path.join(root,'notes/third-fixture/index.html'),'utf8')).includes('仅测试项目'));p.visibility='archived';await writeFile(file,JSON.stringify(p));await build(root);assert.ok((await readFile(path.join(root,'notes/third-fixture/index.html'),'utf8')).includes('已归档'));p.visibility='draft';await writeFile(file,JSON.stringify(p));await build(root);await assert.rejects(()=>readFile(path.join(root,'notes/third-fixture/index.html')));assert.ok(await readFile(path.join(root,'content/development/states/third-fixture.json')));}));
test('duplicate scaffold rejected without catalog changes',()=>temp(async root=>{await addProject(root,{id:'third-fixture',title:'仅测试项目'});const file=path.join(root,'content/development/catalog.json'),before=await readFile(file);await assert.rejects(()=>addProject(root,{id:'third-fixture',title:'different'}));assert.deepEqual(await readFile(file),before);}));
test('manual edits in generated page stop rebuild',()=>temp(async root=>{const f=path.join(root,'notes/pixel-workshop/index.html');await writeFile(f,(await readFile(f,'utf8'))+'<!-- user edit -->');await assert.rejects(()=>build(root),/本地编辑/);assert.ok((await readFile(f,'utf8')).includes('user edit'));}));
test('old note source is retained in generated landing',()=>temp(async root=>{await writeFile(path.join(root,'content/site-data.js'),"globalThis.SITE_DATA={notes:[{title:'KEEP-ORIGINAL-NOTE',summary:'test',visibility:'public'}]};");const {pages}=await planPages(root);assert.ok(pages.get('notes/index.html').toString().includes('KEEP-ORIGINAL-NOTE'));}));
test('one failed state source fails build, not silent zero state',()=>temp(async root=>{const file=path.join(root,'content/development/states/pixel-workshop.json');await writeFile(file,'invalid json');await assert.rejects(()=>planPages(root));}));

test('handoff reads selected project without writing files',()=>temp(async root=>{const {handoff}=await import('../../scripts/journal/handoff.mjs');const text=await handoff(root,'pixel-workshop');assert.ok(text.includes('SITE-001'));assert.ok(!text.includes('GAME-001'));await assert.rejects(()=>handoff(root,'unknown'));}));
