import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {developmentNav,labSpotlight,websiteOverview,documentDirectory,experimentGallery,experimentDetail,projectOverview} from '../../assets/journal/public-layout.mjs';
import {CATALOG} from '../../assets/journal/data/catalog.mjs';
import {EXPERIMENTS} from '../../assets/journal/data/experiments.mjs';
import {validateProject,validateState} from '../../assets/journal/model.mjs';
const root=new URL('../../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8');
const website=JSON.parse(read('content/development/projects/pixel-workshop.json'));
const lab=JSON.parse(read('content/development/projects/lab.json'));
test('website and lab declarations remain compatible with the project model',()=>{validateProject(website);validateProject(lab);validateState(JSON.parse(read('content/development/states/lab.json')),'lab');});
test('lab reuses the development column, without a seventh primary navigation item',()=>{const h=developmentNav('lab');assert.equal((h.match(/aria-current="page"/g)||[]).length,1);assert.match(h,/href="\/notes\/lab\/" aria-current="page"/);assert.doesNotMatch(h,/data-nav-key=/);});
test('development landing page and lab gallery never load the animation automatically',()=>{for(const h of [labSpotlight(),experimentGallery()])assert.doesNotMatch(h,/<iframe|<script|<video|<audio/);});
test('the experiment detail initially contains an explicit play button rather than an iframe',()=>{const h=experimentDetail('pelican-bicycle');assert.match(h,/data-lab-play/);assert.match(h,/data-copy-prompt/);assert.doesNotMatch(h,/<iframe/);assert.match(h,/download="pelican_bicycle.html"/);});
test('the full original prompt is preserved in the metadata',()=>assert.equal(EXPERIMENTS[0].prompt,'生成一个鹈鹕骑自行车的SVG动画，用html实现，不用做任何测试'));
test('unrecorded reasoning effort is not replaced with a fabricated setting or score',()=>{assert.equal(EXPERIMENTS[0].reasoningEffort,null);assert.match(experimentDetail('pelican-bicycle'),/未记录/);assert.doesNotMatch(experimentDetail('pelican-bicycle'),/100\/100|SOTA|全球第一/);});
test('unknown experiments return no invented artifact',()=>assert.equal(experimentDetail('missing'),null));
test('website overview promotes three starting points, not every full guide twice',()=>{const h=websiteOverview(website);for(const id of ['start','content','publishing'])assert.match(h,new RegExp('/docs/'+id+'/'));assert.doesNotMatch(h,/q-doc-directory/);assert.match(h,/浏览全部网站资料/);});
test('document directory retains existing website route IDs and adds authored groups',()=>{const h=documentDirectory(website);for(const id of ['start','architecture','add-project'])assert.match(h,new RegExp('/docs/'+id+'/'));for(const t of ['入门与结构','内容与扩展','构建与发布'])assert.ok(h.includes(t));});
test('history and reference children stay reachable without duplicating active guide cards',()=>{const p={id:'sample',docs:[{id:'start',title:'Start',summary:'S'},{id:'reference',title:'R',readingDocument:true,parentDoc:'start'},{id:'old',title:'Old',archived:true,summary:'Archive'}]};const h=documentDirectory(p);assert.match(h,/data-history-docs/);assert.match(h,/\/docs\/reference\//);assert.match(h,/\/docs\/old\//);assert.equal((h.match(/j-destination-link/g)||[]).length,1);});
test('guide text is escaped and is not emitted as executable markup',()=>{const h=documentDirectory({id:'sample',docs:[{id:'start',title:'<img src=x onerror=bad()>',summary:'<script>bad()</script>'}]});assert.doesNotMatch(h,/<img|<script>/);assert.match(h,/&lt;script&gt;/);});
test('custom layouts use a declared layout rather than hard-coded IDs in the shared renderer',()=>{assert.equal(projectOverview({id:'other',layout:'other'}),null);assert.doesNotMatch(read('assets/journal/render.mjs'),/p\.id\s*===\s*['"]/);});
test('compiled navigation contains no regular guide paragraphs',()=>{for(const p of CATALOG.projects)for(const d of p.docs){if(d.readingDocument)continue;assert.deepEqual(d.sections,[]);assert.match(d.deferredGuide,/\.json\?v=dev-r44-[0-9a-f]{16}$/);}});
test('preview teardown and sandbox are explicit in the wrapper, without editing the animation',()=>{const s=read('assets/journal/experiment.mjs');assert.match(s,/setAttribute\('sandbox','allow-scripts'\)/);assert.doesNotMatch(s,/allow-same-origin/);assert.match(s,/querySelector\('iframe'\)\?\.remove\(\)/);});
test('new organization styles remain scoped to the journal and add no fonts or animation engine',()=>{const s=read('assets/journal/organization.css');assert.doesNotMatch(s,/@font-face|@keyframes|@import|:root/);assert.match(s,/prefers-reduced-motion/);assert.match(s,/max-width:760px/);});
