import test from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import fs from'node:fs';import{fileURLToPath}from'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),context=vm.createContext({URL});
new vm.Script(fs.readFileSync(root+'assets/workshop-media.js','utf8')).runInContext(context);
const M=context.SITE_MEDIA,entry={kind:'image',preset:'poster',src:'games/a/original.png',srcset:[{src:'assets/previews/a-640.webp',width:640},{src:'assets/previews/a-1280.webp',width:1280}]};
test('responsive picture retains original fallback and eager first cover',()=>{const h=M.render(entry,{base:'../',index:0});assert.ok(h.includes('<picture><source type="image/webp"'));assert.ok(h.includes('../assets/previews/a-640.webp 640w'));assert.ok(h.includes('src="../games/a/original.png"'));assert.ok(h.includes('loading="eager"'));assert.ok(h.includes('fetchpriority="high"'));assert.ok(h.includes('width="1600" height="900"'));});
test('later covers keep native lazy loading',()=>assert.ok(M.render(entry,{index:2}).includes('loading="lazy"')));
test('responsive metadata rejects malformed paths and widths',()=>{for(const source of [{src:'javascript:x',width:640},{src:'../a.webp',width:640},{src:'x.png',width:640},{src:'a.webp',width:0},{src:'a.webp',width:640.5},{src:'a.webp',width:9000}])assert.throws(()=>M.validateEntry({...entry,srcset:[source]}));assert.throws(()=>M.validateEntry({...entry,srcset:[entry.srcset[1],entry.srcset[0]]}));assert.throws(()=>M.validateEntry({...entry,kind:'diagram'}));});
test('preview integrity gate verifies originals and encoded assets',async()=>{await import('../../scripts/images/check.mjs');});
test('Q mimi preview keeps frame geometry, timing, and first-row animation',()=>{const p=JSON.parse(fs.readFileSync(root+'content/presentation.json')).entries['project-q-mimi'];assert.equal(p.sprite.rows,1);assert.equal(p.sprite.columns,8);assert.equal(p.sprite.frames,6);assert.equal(p.sprite.durationMs,1560);const h=M.render(p);assert.ok(h.includes('--pw-strip-end:-75%'));assert.ok(h.includes('--pw-rows:1'));});

test('homepage preloads the displayed lossless portrait without unused SVG',()=>{const h=fs.readFileSync(root+'index.html','utf8');assert.ok(/rel="preload"[^>]*xiaoq-avatar-p63a-512-lossless\.webp/.test(h));assert.ok(!/rel="preload"[^>]*xiaoq-avatar-p63a\.svg/.test(h));assert.ok(!fs.readFileSync(root+'assets/site-router.js','utf8').includes('add("image", "identity/xiaoq-avatar-p63a.svg")'));});

test('image failure messages have English copy',()=>{const c=vm.createContext({});new vm.Script(fs.readFileSync(root+'assets/site-i18n-data.js','utf8')).runInContext(c);assert.equal(c.SITE_EN['预览暂不可用'],'Preview unavailable');assert.equal(c.SITE_EN['作品介绍与入口仍可使用'],'Project details and links are still available.');});
