import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';
import{chapterSummary,chapterAtlas,validateChapterPlan}from'../../assets/chapters/view.mjs';
import{projectSnapshot,initializeProject,planWorldSite,sync}from'../../scripts/worlds/sync.mjs';
import{plan as kitPlan}from'../../packages/mario-mix-worlds/scripts/build.mjs';
import{updateRows,render}from'../../assets/journal/render.mjs';
import{validateProject}from'../../assets/journal/model.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),kit=path.join(root,'packages/mario-mix-worlds');
const {catalog,worlds}=kitPlan(kit),get=()=>projectSnapshot(catalog,worlds),project=()=>JSON.parse(fs.readFileSync(path.join(root,'content/development/projects/mario-mix.json')));
test('32 distinct slots with 32 reference templates',()=>{const p=get();assert.equal(p.levels.length,32);assert.equal(p.levels.filter(x=>x.templateHref).length,32);});
test('chapter summary shows actual four rosters',()=>{const h=chapterSummary(get());for(const x of ['魂斗罗','洛克人','忍者龙剑传','坦克大战','泰拉瑞亚','奥日'])assert.ok(h.includes(x));assert.equal((h.match(/data-level-id/g)||[]).length,4);});
test('Ori remains active without a playable anchor',()=>{const l=get().levels[3];assert.equal(l.status,'active');assert.equal(l.playHref,null);assert.match(chapterSummary(get()),/暂未开放试玩/);});
test('three released chapters link to separate existing games',()=>{const h=chapterSummary(get());for(const p of ['/games/mario-mix/play.html','/games/mario-mix-2/play.html','/games/mario-mix-3/play.html'])assert.ok(h.includes(p));assert.equal((h.match(/>开始试玩</g)||[]).length,3);});
test('all 96 area and section views shown as real static previews',()=>{const h=chapterAtlas(get());assert.equal((h.match(/class="q-map-scroll"/g)||[]).length,96);assert.ok(!h.includes('<canvas'));});
test('mechanic and fidelity limits remain in public page',()=>{const h=chapterAtlas(get());for(const x of ['社区参考','不是官方','自然通关','火焰棒'])assert.ok(h.includes(x));});
test('future games remain unplayable while real template downloads exist',()=>{const p=get();for(const x of p.levels.slice(4)){assert.match(x.templateHref,/_W02\.zip$/);assert.equal(x.playHref,null);assert.deepEqual(x.characters,[]);}assert.match(chapterAtlas(p),/32 张底图/);});
test('only first world expanded; individual map details closed and keyboard scrollable',()=>{const h=chapterAtlas(get());assert.equal((h.match(/<details[^>]*\bopen/g)||[]).length,1);assert.ok(!/<details class="q-map-details"[^>]*\bopen/.test(h));assert.match(h,/tabindex="0" role="region"/);});
test('template downloads are actual native download anchors',()=>{const h=chapterAtlas(get());assert.equal((h.match(/ download/g)||[]).length,41);assert.ok(!h.includes('onclick'));});
test('unsafe instructions target rejected',()=>{const p=get();p.instructionsHref='javascript:alert(1)';assert.throws(()=>validateChapterPlan(p));});
test('unsafe image and traversal target rejected',()=>{for(const u of ['//evil','/a/../bad','/%2e%2e/a']){const p=get();p.levels[0].previews[0].src=u;assert.throws(()=>validateChapterPlan(p));}});
test('plain text is escaped',()=>{const p=get();p.levels[0].characters=['<img onerror=x>'];assert.ok(chapterSummary(p).includes('&lt;img'));assert.ok(!chapterSummary(p).includes('<img onerror'));});
test('optional chapter data leaves other project render unchanged',()=>{assert.equal(chapterSummary(undefined),'');assert.equal(chapterAtlas(undefined),'');validateChapterPlan(undefined);});
test('initializing project preserves game release and task source',()=>{const p=project(),next=initializeProject(p);assert.deepEqual(next.currentRelease,p.currentRelease);assert.deepEqual(next.state,p.state);assert.equal(next.docs.filter(d=>!d.archived).length,3);});
test('project update may be newer than current game release',()=>{const p=project(),release=structuredClone(p.currentRelease);p.updates.push({id:'synthetic-content-check',kind:'content',date:'2099-01-01',revision:999,title:'Content update example',summary:'Synthetic fixture only',status:'local-review'});validateProject(p);assert.match(updateRows([p],{limit:1}),/Content update example/);assert.deepEqual(p.currentRelease,release);});
test('public atlas content is sourced from canonical catalog',async()=>{const plan=await planWorldSite(root);const p=JSON.parse(plan.files.get('content/development/projects/mario-mix.json'));assert.deepEqual(p.chapterPlan,get());assert.equal(plan.files.size,137);});
test('sync check is idempotent and does not write',async()=>{assert.equal((await sync(root,{check:true})).changed,0);});
test('current pages use document code but retain compact icons',()=>{const read=n=>fs.readFileSync(path.join(root,n),'utf8');assert.match(read('assets/journal/runtime.mjs'),/render\.mjs\?v=align-r27/);assert.match(read('notes/index.html'),/data-chapters-css/);assert.match(read('notes/index.html'),/controller\.svg\?v=workshop-r12/);});
